import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { GAMES } from "@/lib/games.ts";
import { viewer } from "@/server/viewer.ts";
import { p2pOverview, P2P_GAME, iceConfiguration } from "@/server/p2p.ts";
import { ActionForm, Check, DbDown, Field, Flash, PageHead, type SearchParams } from "@/components/ui";
export const metadata = { title: "MAXIMUS · P2P cloud gaming" };
export default async function CloudGaming({ params, searchParams }: { params: Promise<{ lang: string }>; searchParams: SearchParams }) {
  const { lang } = await params; if (!isLocale(lang)) notFound(); const T = (ru: string, en: string) => lang === "ru" ? ru : en, back = `/${lang}/cloud-gaming`;
  const { db, user } = await viewer(); if (!db) return <DbDown lang={lang} />; const data = await p2pOverview(db, user?.id);
  const games = [{ slug: P2P_GAME, name: "MAXIMUS Arena" }, ...GAMES];
  const network = iceConfiguration(user?.id ?? "public");
  return <div className="container page"><PageHead title={T("P2P игровые сеансы", "P2P game sessions")} lead={T("Подключитесь к свободной машине сообщества или предоставьте собственный игровой хост.", "Connect to an available community machine or provide your own gaming host.")} /><Flash lang={lang} params={await searchParams} />
    {!network.iceServers?.some(s => s.credential) && <p className="notice">{T("Ретранслятор для сложных сетей пока не подключён. Возможность прямого соединения зависит от сетей обоих участников.", "A relay for restrictive networks is not connected yet. Direct connectivity depends on both participants' networks.")}</p>}
    <h2>{T("Доступные хосты", "Available hosts")}</h2>{!data.available.length ? <p className="notice">{T("Сейчас нет свободных подтверждённых хостов. Владельцы могут зарегистрировать машину ниже.", "No verified hosts are available right now. Owners can register a machine below.")}</p> : <div className="grid grid-3">{data.available.map(h => <article key={h.id} className="card"><h3>{h.name}</h3><p>{h.region}</p><p>{h.cpu} · {h.gpu} · {h.ram_gb} GB</p><p>{h.games.map(g => games.find(x => x.slug === g)?.name ?? g).join(", ")}</p></article>)}</div>}
    {user ? <><section className="card section-tight"><h2>{T("Запросить сеанс", "Request a session")}</h2><ActionForm action="p2p.allocate" lang={lang} back={back}><Field label={T("Игра", "Game")}><select name="game">{games.map(g => <option key={g.slug} value={g.slug}>{g.name}</option>)}</select></Field><Field label={T("Регион хоста (необязательно)", "Host region (optional)")}><input name="region" maxLength={60} list="host-regions" /><datalist id="host-regions">{[...new Set(data.available.map(h => h.region))].map(r => <option key={r} value={r} />)}</datalist></Field><Check name="consent" required label={T("Согласен на соединение с выбранным хостом. При прямом соединении стороны могут видеть сетевые адреса друг друга. Не передаю хосту пароли или платёжные данные.", "I agree to connect to the allocated host. Direct connections can reveal network addresses to the other participant. I will not share passwords or payment details with the host.")} /><button className="btn btn-primary" disabled={!data.available.length}>{T("Найти свободный хост", "Find an available host")}</button></ActionForm><p className="small muted">{T("Ожидание ответа — 2 минуты, сеанс — до 60 минут. MAXIMUS Arena работает в браузере хоста; установленные игры требуют хост-агента и разрешения правообладателя.", "Hosts have 2 minutes to respond; sessions last up to 60 minutes. MAXIMUS Arena runs in the host browser; installed games require the host agent and publisher permission.")}</p></section>
    <section className="section-tight"><h2>{T("Ваши сеансы", "Your sessions")}</h2><ul className="list">{data.sessions.map(s => <li key={s.id}><Link href={`${back}/session/${s.id}`}>{s.name} · {games.find(g => g.slug === s.game)?.name}</Link><span>{({ requested: T("Ожидает ответа", "Requested"), connecting: T("Подключение", "Connecting"), active: T("Идёт", "Active"), ended: T("Завершён", "Ended"), failed: T("Прерван", "Failed"), rejected: T("Отклонён", "Declined") })[s.status]}</span></li>)}</ul></section>
    <section className="section-tight"><h2>{T("Ваши машины", "Your hosts")}</h2><ul className="list">{data.mine.map(h => <li key={h.id}><Link href={`${back}/host/${h.id}`}>{h.name}</Link><span>{h.status === "approved" ? T("Подтверждён", "Approved") : h.status === "pending" ? T("На проверке", "Under review") : T("Приостановлен", "Suspended")}</span></li>)}</ul></section>
    <details className="card section-tight"><summary>{T("Зарегистрировать хост", "Register host")}</summary><ActionForm action="p2p.register" lang={lang} back={back}><div className="grid grid-2"><Field label={T("Название машины", "Host name")}><input name="name" minLength={2} maxLength={80} required /></Field><Field label={T("Регион или город", "Region or city")}><input name="region" minLength={2} maxLength={60} required /></Field><Field label="CPU"><input name="cpu" minLength={2} maxLength={100} required /></Field><Field label="GPU"><input name="gpu" minLength={2} maxLength={100} required /></Field><Field label="RAM (GB)"><input name="ram" type="number" min="2" max="2048" required /></Field></div><fieldset><legend>{T("Игры, которые хост может предоставить", "Games this host can provide")}</legend>{games.map(g => <Check key={g.slug} name="games" value={g.slug} label={g.name} defaultChecked={g.slug === P2P_GAME} />)}</fieldset><Check name="consent" required label={T("Я управляю этой машиной, подтверждаю указанные параметры и право запускать выбранные игры. Понимаю, что подключение станет доступно после проверки и включения хоста.", "I control this machine and confirm its specifications and my right to run the selected games. Connections become available after review and after I enable the host.")} /><button className="btn btn-primary">{T("Отправить на проверку", "Submit for review")}</button></ActionForm></details></> : <Link className="btn btn-primary" href={`/${lang}/signin?next=${back}`}>{T("Войти для подключения или регистрации хоста", "Sign in to connect or register a host")}</Link>}
  </div>;
}
