/** Texts of the academy: programmes, coaches, training requests, sessions and progress (MV-ACADEMY-1), RU / EN. */
export const academyText = {
  ru: {
    academy: "Академия MAXIMUS",
    academyLead: "Программы тренеров по играм и уровням, заявки на обучение, занятия и записи прогресса. Тренеры видны только после проверки опыта командой портала.",
    boundaries:
      "Без гарантий роста рейтинга, контракта или стипендии. Портал не принимает оплату занятий: условия тренер и игрок обсуждают сами. Все аккаунты портала — совершеннолетние; работа с несовершеннолетними не предлагается.",
    programmes: "Программы",
    noProgrammes: "Опубликованных программ пока нет.",
    coaches: "Тренеры",
    coachesLead: "Тренеры с опытом, проверенным командой портала. Заявка на обучение попадает в очередь тренера, ответ приходит уведомлением.",
    noCoaches: "Проверенных тренеров пока нет.",
    becomeCoach: "Стать тренером",
    allGames: "Все игры",
    anyLevel: "Любой уровень",
    anyFormat: "Любой формат",
    anyLanguage: "Любой язык",
    show: "Показать",
    levels: { beginner: "Начальный", intermediate: "Средний", advanced: "Продвинутый" } as Record<string, string>,
    formats: { online: "Онлайн", offline: "Очно" } as Record<string, string>,
    languages: { ru: "Русский", en: "English", other: "Другой" } as Record<string, string>,
    sessionsOf: "{n} занятий по {m} мин",
    verified: "Опыт проверен командой портала",
    accepting: "Принимает заявки",
    notAccepting: "Сейчас не принимает заявки",
    experience: "Опыт",
    games: "Игры",
    city: "Город (для очных занятий)",
    requestTitle: "Заявка на обучение",
    requestLead: "Опишите цель: что хотите улучшить и в какой игре. Тренер ответит уведомлением.",
    programme: "Программа",
    noProgramme: "Без программы",
    game: "Игра",
    goal: "Цель (от 10 символов)",
    availability: "Когда вам удобно (необязательно)",
    send: "Отправить заявку",
    signIn: "Войдите, чтобы отправить заявку.",
    ownProfile: "Это ваш профиль тренера.",
    existing: "У вас уже есть открытая заявка этому тренеру.",
    workspace: "Кабинет тренера",
    workspaceLead: "Профиль, программы, очередь заявок и занятия. Профиль и программы видны всем только после проверки опыта.",
    profile: "Профиль",
    headline: "Кратко о себе (3–80 символов)",
    bio: "О себе",
    experienceField: "Опыт: результаты, команды, стаж — то, что команда портала может проверить (20–1000 символов)",
    gamesField: "Игры (до 5)",
    languagesField: "Языки",
    formatsField: "Форматы",
    acceptingField: "Принимаю заявки",
    save: "Сохранить",
    submit: "Отправить на проверку",
    statuses: { draft: "Черновик", submitted: "На проверке", verified: "Проверен", rejected: "Не подтверждён", suspended: "Приостановлен" } as Record<string, string>,
    reviewNote: "Ответ команды портала",
    publicPage: "Публичная страница",
    newProgramme: "Новая программа",
    title: "Название",
    level: "Уровень",
    format: "Формат",
    description: "Описание",
    sessions: "Занятий",
    minutes: "Минут на занятие",
    programmeStatuses: { draft: "Черновик", published: "Опубликована", archived: "В архиве" } as Record<string, string>,
    publish: "Опубликовать",
    archive: "В архив",
    toDraft: "Снять с публикации",
    edit: "Изменить",
    queue: "Очередь заявок",
    noQueue: "Новых заявок нет.",
    active: "Идёт обучение",
    noActive: "Активных учеников нет.",
    closed: "Закрытые",
    accept: "Принять",
    decline: "Отклонить",
    answerNote: "Ответ игроку (необязательно)",
    open: "Открыть",
    upcoming: "Ближайшие занятия",
    noUpcoming: "Занятий не назначено.",
    myTraining: "Моё обучение",
    myTrainingLead: "Ваши заявки тренерам, занятия и записи прогресса.",
    noRequests: "Заявок пока нет.",
    findCoach: "Найти тренера",
    requestStatuses: { pending: "Ждёт ответа", accepted: "Идёт", declined: "Отклонена", cancelled: "Отменена", completed: "Завершена" } as Record<string, string>,
    coach: "Тренер",
    student: "Игрок",
    cancel: "Отменить заявку",
    complete: "Завершить обучение",
    sessionsTitle: "Занятия",
    noSessions: "Занятий пока нет.",
    book: "Назначить занятие",
    when: "Начало",
    duration: "Длительность, мин",
    place: "Ссылка на звонок или место",
    sessionStatuses: { scheduled: "Запланировано", done: "Проведено", cancelled: "Отменено", no_show: "Неявка" } as Record<string, string>,
    markDone: "Проведено",
    markNoShow: "Неявка",
    cancelSession: "Отменить",
    progress: "Прогресс",
    progressLead: "Факт, рекомендация и замер записываются раздельно: наблюдение тренера с отметкой времени, упражнение от тренера и показатель с числом.",
    noProgress: "Записей пока нет.",
    kinds: { observation: "Наблюдение (факт)", exercise: "Рекомендация тренера", measure: "Замер" } as Record<string, string>,
    addRecord: "Добавить запись",
    kind: "Вид записи",
    body: "Текст",
    evidence: "Ссылка на запись или replay (https://, необязательно)",
    timeMark: "Отметка времени (например, 12:34)",
    metric: "Показатель (для замера)",
    value: "Значение (для замера)",
    session: "Занятие",
    noSession: "Без привязки",
    portalFacts: "Данные портала",
    portalFactsLead: "Рейтинг быстрого матча игрока в этой игре — данные портала, не оценка тренера.",
    rating: "Рейтинг",
    matches: "матчей",
    noRating: "Рейтинга в этой игре пока нет.",
    staffView: "Вы видите обучение как сотрудник портала; просмотр записан в журнал.",
    goalTitle: "Цель",
    note: "Ответ тренера",
    queueTab: "Тренеры",
    queueLead: "Подтверждайте опыт, который можно проверить: результаты, команды, сертификаты. Опубликованный тренер получает заявки игроков.",
    review: "На проверке",
    live: "Проверенные и приостановленные",
    none: "Тренеров на проверке нет.",
    staffNote: "Ответ (для отклонения и приостановки — от 10 символов)",
    verify: "Подтвердить",
    reject: "Отклонить",
    suspend: "Приостановить",
  },
  en: {
    academy: "MAXIMUS Academy",
    academyLead: "Coaches' programmes by game and level, training requests, sessions and progress records. Coaches appear only once the portal team has verified their experience.",
    boundaries:
      "No guaranteed rating gains, contracts or scholarships. The portal takes no payment for sessions: the coach and the player agree the terms themselves. Every portal account is adult; work with minors is not offered.",
    programmes: "Programmes",
    noProgrammes: "No published programmes yet.",
    coaches: "Coaches",
    coachesLead: "Coaches whose experience the portal team has verified. A training request goes to the coach's queue; the answer arrives as a notification.",
    noCoaches: "No verified coaches yet.",
    becomeCoach: "Become a coach",
    allGames: "All games",
    anyLevel: "Any level",
    anyFormat: "Any format",
    anyLanguage: "Any language",
    show: "Show",
    levels: { beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" } as Record<string, string>,
    formats: { online: "Online", offline: "In person" } as Record<string, string>,
    languages: { ru: "Russian", en: "English", other: "Other" } as Record<string, string>,
    sessionsOf: "{n} sessions of {m} min",
    verified: "Experience verified by the portal team",
    accepting: "Taking requests",
    notAccepting: "Not taking requests now",
    experience: "Experience",
    games: "Games",
    city: "City (for in-person sessions)",
    requestTitle: "Training request",
    requestLead: "Describe the goal: what you want to improve and in which game. The coach answers with a notification.",
    programme: "Programme",
    noProgramme: "No programme",
    game: "Game",
    goal: "Goal (10 characters or more)",
    availability: "When suits you (optional)",
    send: "Send request",
    signIn: "Sign in to send a request.",
    ownProfile: "This is your coach profile.",
    existing: "You already have an open request to this coach.",
    workspace: "Coach workspace",
    workspaceLead: "Profile, programmes, request queue and sessions. The profile and programmes are public only once the experience is verified.",
    profile: "Profile",
    headline: "Headline (3–80 characters)",
    bio: "About",
    experienceField: "Experience: results, teams, years — what the portal team can check (20–1000 characters)",
    gamesField: "Games (up to 5)",
    languagesField: "Languages",
    formatsField: "Formats",
    acceptingField: "Taking requests",
    save: "Save",
    submit: "Send for review",
    statuses: { draft: "Draft", submitted: "In review", verified: "Verified", rejected: "Not verified", suspended: "Suspended" } as Record<string, string>,
    reviewNote: "The portal team's answer",
    publicPage: "Public page",
    newProgramme: "New programme",
    title: "Title",
    level: "Level",
    format: "Format",
    description: "Description",
    sessions: "Sessions",
    minutes: "Minutes per session",
    programmeStatuses: { draft: "Draft", published: "Published", archived: "Archived" } as Record<string, string>,
    publish: "Publish",
    archive: "Archive",
    toDraft: "Unpublish",
    edit: "Edit",
    queue: "Request queue",
    noQueue: "No new requests.",
    active: "In training",
    noActive: "No active students.",
    closed: "Closed",
    accept: "Accept",
    decline: "Decline",
    answerNote: "Answer to the player (optional)",
    open: "Open",
    upcoming: "Next sessions",
    noUpcoming: "No sessions booked.",
    myTraining: "My training",
    myTrainingLead: "Your requests to coaches, sessions and progress records.",
    noRequests: "No requests yet.",
    findCoach: "Find a coach",
    requestStatuses: { pending: "Waiting", accepted: "In progress", declined: "Declined", cancelled: "Cancelled", completed: "Completed" } as Record<string, string>,
    coach: "Coach",
    student: "Player",
    cancel: "Cancel request",
    complete: "Complete training",
    sessionsTitle: "Sessions",
    noSessions: "No sessions yet.",
    book: "Book a session",
    when: "Starts",
    duration: "Length, min",
    place: "Call link or place",
    sessionStatuses: { scheduled: "Scheduled", done: "Held", cancelled: "Cancelled", no_show: "No-show" } as Record<string, string>,
    markDone: "Held",
    markNoShow: "No-show",
    cancelSession: "Cancel",
    progress: "Progress",
    progressLead: "Fact, recommendation and measurement are recorded apart: the coach's observation with a time mark, the coach's exercise and a metric with a number.",
    noProgress: "No records yet.",
    kinds: { observation: "Observation (fact)", exercise: "Coach's recommendation", measure: "Measurement" } as Record<string, string>,
    addRecord: "Add a record",
    kind: "Record type",
    body: "Text",
    evidence: "Link to a recording or replay (https://, optional)",
    timeMark: "Time mark (e.g. 12:34)",
    metric: "Metric (for a measurement)",
    value: "Value (for a measurement)",
    session: "Session",
    noSession: "Not linked",
    portalFacts: "Portal data",
    portalFactsLead: "The player's quick-match rating in this game — portal data, not the coach's assessment.",
    rating: "Rating",
    matches: "matches",
    noRating: "No rating in this game yet.",
    staffView: "You see this training as portal staff; the view is recorded in the log.",
    goalTitle: "Goal",
    note: "The coach's answer",
    queueTab: "Coaches",
    queueLead: "Confirm experience that can be checked: results, teams, certificates. A published coach receives players' requests.",
    review: "In review",
    live: "Verified and suspended",
    none: "No coaches in review.",
    staffNote: "Answer (10 characters or more to reject or suspend)",
    verify: "Verify",
    reject: "Reject",
    suspend: "Suspend",
  },
};
