import type { Locale } from "./i18n.ts";

/** Texts of clans, clan wars and seasonal ladders (RU / EN). */
export const clanText = {
  ru: {
    title: "Кланы",
    lead: "Клан объединяет игроков разных игр. Владелец и офицеры приглашают игроков и ведут клановые войны; результаты войн идут в сезонный рейтинг кланов по игре.",
    search: "Название или тег",
    find: "Найти",
    none: "Кланов пока нет — создайте первый.",
    noMatch: "Таких кланов нет.",
    members: "Игроки",
    yourClan: "Ваш клан",
    invites: "Приглашения в кланы",
    accept: "Вступить",
    decline: "Отказаться",
    from: "от",
    create: "Создать клан",
    createLead: "Состоять можно только в одном клане. Тег — 2–5 латинских букв или цифр, его видно рядом с названием.",
    name: "Название",
    tag: "Тег",
    description: "Описание (необязательно)",
    ladders: "Сезонные рейтинги",
    disbanded: "распущен",
    roles: { owner: "владелец", officer: "офицер", member: "игрок" } as Record<string, string>,
    makeOfficer: "Сделать офицером",
    makeMember: "Снять с офицеров",
    makeOwner: "Передать владение",
    remove: "Исключить",
    leave: "Выйти из клана",
    disband: "Распустить клан",
    disbandHint: "Вы последний игрок клана: выход распускает клан, открытые вызовы и назначенные войны отменяются.",
    invite: "Пригласить игрока",
    inviteUsername: "Имя пользователя",
    send: "Отправить",
    pendingInvites: "Ждут ответа",
    revoke: "Отозвать",
    save: "Сохранить",
    editDescription: "Описание клана",
    since: "в клане с",
    season: "Сезон",
    rank: "место",
    rating: "рейтинг",
    noSeason: "В этом сезоне рейтинговых войн ещё не было.",
    wars: "Клановые войны",
    warsLead: "Серия между кланами в одной игре, составы одинакового размера. Вызов ждёт ответа до 72 часов, но не позже начала. После начала счёт отправляет любой клан, второй подтверждает или оспаривает его за 48 часов — потом счёт засчитывается. Без счёта через 72 часа после начала война закрывается без результата.",
    noWars: "Войн пока не было.",
    propose: "Вызвать клан на войну",
    proposeTo: "Вызвать «{name}» на войну",
    opponent: "Тег клана-соперника",
    game: "Игра",
    size: "Игроков в составе",
    bestOf: "Серия",
    bo: "до {n} побед",
    boShort: "Bo{n}",
    start: "Начало (ваше местное время)",
    lineup: "Состав",
    lineupHint: "Отметьте ровно столько игроков, сколько в составе. Игроки с ограничением быстрого матча и вызовов не участвуют.",
    message: "Сообщение (необязательно)",
    sendChallenge: "Отправить вызов",
    statuses: {
      proposed: "вызов",
      accepted: "назначена",
      reported: "счёт ждёт подтверждения",
      completed: "завершена",
      disputed: "спор",
      declined: "отклонена",
      cancelled: "отменена",
      expired: "без результата",
      void: "аннулирована",
    } as Record<string, string>,
    vs: "против",
    answerUntil: "ответ до",
    startsAt: "начало",
    reportUntil: "счёт до",
    confirmUntil: "подтверждение до",
    acceptWith: "Принять с составом",
    cancel: "Отменить войну",
    withdraw: "Отозвать вызов",
    changeLineup: "Сменить состав",
    report: "Отправить счёт",
    ourScore: "Наш счёт",
    theirScore: "Счёт соперника",
    confirm: "Подтвердить счёт",
    dispute: "Оспорить счёт",
    disputeReason: "Что не так (от 20 символов; решает команда портала)",
    reportedBy: "счёт отправил клан",
    waitingOther: "ждём подтверждения соперника",
    winner: "победил",
    unrated: "без рейтинга: эти кланы уже играли рейтинговую войну в этой игре меньше 7 дней назад",
    shortLineup: "состав неполный — замените игроков до начала",
    decision: "решение команды портала",
    laddersTitle: "Сезонные рейтинги",
    laddersLead: "Сезон — календарный квартал по UTC. Кланы: каждый сезон начинают с 1000; рейтинговая клановая война меняет рейтинг обоих кланов по Эло (K = 32, не ниже 100); одна пара кланов получает рейтинг за войну в игре не чаще раза в 7 дней. Игроки: рейтинг быстрого матча после последнего матча сезона, в таблице — открытые профили с 5 и более матчами за сезон.",
    clansBoard: "Кланы",
    playersBoard: "Игроки",
    clan: "Клан",
    player: "Игрок",
    warsCol: "Войны",
    matches: "Матчи",
    wins: "Победы",
    losses: "Поражения",
    noClanBoard: "В этом сезоне по этой игре рейтинговых клановых войн нет.",
    noDuel: "Клановые войны проводятся только в играх с матчами один на один или команда на команду.",
    noPlayerBoard: "В этом сезоне ни у одного открытого профиля нет 5 рейтинговых матчей в этой игре.",
    seasonLabel: (season: string) => {
      const [year, q] = season.split("-Q");
      return `${q}-й квартал ${year}`;
    },
    mine: "ваш",
  },
  en: {
    title: "Clans",
    lead: "A clan brings together players of different games. The owner and officers invite players and run clan wars; war results go to the clans' seasonal ladder of each game.",
    search: "Name or tag",
    find: "Find",
    none: "No clans yet — create the first one.",
    noMatch: "No such clans.",
    members: "Players",
    yourClan: "Your clan",
    invites: "Clan invitations",
    accept: "Join",
    decline: "Decline",
    from: "from",
    create: "Create a clan",
    createLead: "You can belong to one clan at a time. The tag is 2–5 Latin letters or digits, shown next to the name.",
    name: "Name",
    tag: "Tag",
    description: "Description (optional)",
    ladders: "Seasonal ladders",
    disbanded: "disbanded",
    roles: { owner: "owner", officer: "officer", member: "player" } as Record<string, string>,
    makeOfficer: "Make officer",
    makeMember: "Remove officer role",
    makeOwner: "Hand over ownership",
    remove: "Remove",
    leave: "Leave the clan",
    disband: "Disband the clan",
    disbandHint: "You are the clan's last player: leaving disbands it, and open challenges and scheduled wars are called off.",
    invite: "Invite a player",
    inviteUsername: "Username",
    send: "Send",
    pendingInvites: "Waiting for an answer",
    revoke: "Revoke",
    save: "Save",
    editDescription: "Clan description",
    since: "in the clan since",
    season: "Season",
    rank: "rank",
    rating: "rating",
    noSeason: "No rated wars this season yet.",
    wars: "Clan wars",
    warsLead: "A series between clans in one game with lineups of the same size. A challenge waits up to 72 hours for an answer, and no later than the start. After the start either clan sends the score; the other confirms or disputes it within 48 hours, after which it stands. With no score 72 hours after the start, the war closes without a result.",
    noWars: "No wars yet.",
    propose: "Challenge a clan to a war",
    proposeTo: "Challenge “{name}” to a war",
    opponent: "Opposing clan's tag",
    game: "Game",
    size: "Players per lineup",
    bestOf: "Series",
    bo: "first to {n}",
    boShort: "Bo{n}",
    start: "Start (your local time)",
    lineup: "Lineup",
    lineupHint: "Tick exactly as many players as the lineup size. Players restricted from quick match and challenges cannot take part.",
    message: "Message (optional)",
    sendChallenge: "Send the challenge",
    statuses: {
      proposed: "challenge",
      accepted: "scheduled",
      reported: "score awaiting confirmation",
      completed: "finished",
      disputed: "dispute",
      declined: "declined",
      cancelled: "called off",
      expired: "no result",
      void: "void",
    } as Record<string, string>,
    vs: "vs",
    answerUntil: "answer by",
    startsAt: "start",
    reportUntil: "score by",
    confirmUntil: "confirm by",
    acceptWith: "Accept with lineup",
    cancel: "Call off the war",
    withdraw: "Withdraw the challenge",
    changeLineup: "Change lineup",
    report: "Send the score",
    ourScore: "Our score",
    theirScore: "Opponent's score",
    confirm: "Confirm the score",
    dispute: "Dispute the score",
    disputeReason: "What is wrong (20 characters or more; the portal team decides)",
    reportedBy: "score sent by",
    waitingOther: "waiting for the opponent to confirm",
    winner: "won",
    unrated: "unrated: these clans played a rated war in this game less than 7 days earlier",
    shortLineup: "lineup incomplete — replace players before the start",
    decision: "portal team's decision",
    laddersTitle: "Seasonal ladders",
    laddersLead: "A season is a calendar quarter in UTC. Clans: every season starts at 1000; a rated clan war moves both clans by Elo (K = 32, never below 100); a pair of clans earns rating for a war in a game at most once in 7 days. Players: the quick match rating after the last match of the season; the table lists public profiles with 5 or more matches in the season.",
    clansBoard: "Clans",
    playersBoard: "Players",
    clan: "Clan",
    player: "Player",
    warsCol: "Wars",
    matches: "Matches",
    wins: "Wins",
    losses: "Losses",
    noClanBoard: "No rated clan wars in this game this season.",
    noDuel: "Clan wars are played only in games with one-on-one or team-versus-team matches.",
    noPlayerBoard: "No public profile has 5 rated matches in this game this season.",
    seasonLabel: (season: string) => {
      const [year, q] = season.split("-Q");
      return `Q${q} ${year}`;
    },
    mine: "yours",
  },
} satisfies Record<Locale, Record<string, unknown>>;
