import type { Locale } from "./i18n.ts";

/** Texts of fair play: the player's page, the staff tab and the public trust centre (RU / EN). */
export const conductText = {
  ru: {
    title: "Честная игра: мой статус",
    lead: "Меры по вашему аккаунту с правилом, доказательствами и сроком, апелляции и ваши обращения о нарушениях.",
    restricted: "Аккаунт ограничен решением по честной игре: вы можете читать портал и подать апелляцию, другие действия недоступны до конца срока или решения по апелляции.",
    sanctions: "Меры по моему аккаунту",
    noSanctions: "Мер нет.",
    kinds: { warning: "Предупреждение", queue_ban: "Запрет быстрого матча и вызовов", tournament_ban: "Запрет участия в турнирах", suspension: "Ограничение аккаунта" } as Record<string, string>,
    protective: "Защитная блокировка на время проверки",
    confidence: "Уверенность",
    confidences: { low: "низкая", medium: "средняя", high: "высокая" } as Record<string, string>,
    rule: "Правило",
    version: "редакция",
    decision: "Решение",
    evidence: "Доказательства",
    term: "Срок",
    from: "с",
    until: "до",
    noEnd: "без срока окончания",
    live: "действует",
    ended: "закончилась",
    revoked: "отменена",
    revokeReason: "Причина отмены",
    integrity: "Хеш доказательств совпадает с журналом решений",
    appeal: "Подать апелляцию",
    appealNote: "Апелляцию можно подать один раз в течение 14 дней. Её рассматривает сотрудник, который не принимал исходное решение.",
    statement: "Почему решение неверно (от 20 символов)",
    appealEvidence: "Ссылка на доказательство (необязательно)",
    send: "Отправить",
    appealStatus: { open: "апелляция на рассмотрении", upheld: "апелляция отклонена — мера в силе", granted: "апелляция удовлетворена — мера отменена" } as Record<string, string>,
    appealDecision: "Ответ по апелляции",
    report: "Сообщить о нарушении",
    reportLead: "Опишите, что произошло, и приложите ссылки. Обращение видит только команда портала; игрок не узнаёт, кто его подал. Вы узнаете итог: меры приняты или нарушение не подтверждено.",
    player: "Имя пользователя игрока",
    ruleOther: "Другое",
    context: "Страница портала, где это произошло (необязательно, например /ru/matches/…)",
    description: "Что произошло (от 20 символов)",
    evidenceUrl: "Ссылка на доказательство (необязательно, https)",
    sendReport: "Отправить обращение",
    myReports: "Мои обращения",
    noReports: "Обращений нет.",
    reportStatus: { open: "получено", reviewing: "на проверке", actioned: "меры приняты", dismissed: "нарушение не подтверждено" } as Record<string, string>,
    rules: "Правила честной игры",
    signIn: "Войдите, чтобы увидеть свой статус или сообщить о нарушении.",
  },
  en: {
    title: "Fair play: my status",
    lead: "Measures on your account with the rule, evidence and term, appeals, and your reports of violations.",
    restricted: "The account is restricted by a fair-play decision: you can read the portal and appeal; other actions are unavailable until the term ends or the appeal is decided.",
    sanctions: "Measures on my account",
    noSanctions: "No measures.",
    kinds: { warning: "Warning", queue_ban: "Quick match and challenge ban", tournament_ban: "Tournament ban", suspension: "Account restriction" } as Record<string, string>,
    protective: "Protective hold during an investigation",
    confidence: "Confidence",
    confidences: { low: "low", medium: "medium", high: "high" } as Record<string, string>,
    rule: "Rule",
    version: "version",
    decision: "Decision",
    evidence: "Evidence",
    term: "Term",
    from: "from",
    until: "until",
    noEnd: "no end date",
    live: "in force",
    ended: "ended",
    revoked: "revoked",
    revokeReason: "Reason for revoking",
    integrity: "The evidence digest matches the decision log",
    appeal: "Appeal",
    appealNote: "You can appeal once within 14 days. A staff member who did not take the original decision reviews it.",
    statement: "Why the decision is wrong (20 characters or more)",
    appealEvidence: "Link to evidence (optional)",
    send: "Send",
    appealStatus: { open: "appeal under review", upheld: "appeal rejected — the measure stands", granted: "appeal granted — the measure is revoked" } as Record<string, string>,
    appealDecision: "Answer to the appeal",
    report: "Report a violation",
    reportLead: "Describe what happened and add links. Only the portal team sees the report; the player does not learn who filed it. You learn the outcome: action taken or no violation found.",
    player: "Player's username",
    ruleOther: "Other",
    context: "Portal page where it happened (optional, e.g. /en/matches/…)",
    description: "What happened (20 characters or more)",
    evidenceUrl: "Link to evidence (optional, https)",
    sendReport: "Send the report",
    myReports: "My reports",
    noReports: "No reports.",
    reportStatus: { open: "received", reviewing: "under review", actioned: "action taken", dismissed: "no violation found" } as Record<string, string>,
    rules: "Fair-play rules",
    signIn: "Sign in to see your status or report a violation.",
  },
} satisfies Record<Locale, Record<string, unknown>>;

/** The public trust centre: the procedure and the anonymised counts. */
export const trustText = {
  ru: {
    rules: "Правила",
    rulesNote: "Санкция ссылается на конкретную редакцию правила. Новая редакция не меняет прежние решения.",
    source: "Источник",
    procedure: "Как принимается решение",
    steps: [
      ["Обращение", "Игрок сообщает о нарушении со ссылками. Обращение видит только команда портала; автор не раскрывается."],
      ["Проверка", "Сотрудник собирает доказательства. На время проверки возможна защитная блокировка — не дольше 72 часов; затем окончательное решение или снятие."],
      ["Решение", "Мера указывает правило и его редакцию, доказательства, уровень уверенности и обоснование. Хеш списка доказательств записывается в журнал решений с hash-цепочкой: последующее изменение обнаруживается."],
      ["Меры", "Предупреждение — без ограничений. Запрет быстрого матча и вызовов или запрет турниров — при средней или высокой уверенности, на 1–365 дней. Ограничение аккаунта — только при высокой уверенности; аккаунт сохраняет просмотр и апелляцию."],
      ["Апелляция", "Один раз в течение 14 дней. Решение принимает сотрудник, который не выносил исходную меру. Удовлетворённая апелляция отменяет меру."],
      ["Отчётность", "Ниже — только количества за 90 дней. Значения от 1 до 2 скрываются, чтобы число не указывало на человека. Незавершённые проверки не показываются."],
    ] as Array<[string, string]>,
    report: "Отчётность за 90 дней",
    fewer: "менее 3",
    counts: {
      reports_received: "Обращений получено",
      reports_actioned: "Обращений с принятыми мерами",
      reports_dismissed: "Обращений без подтверждения нарушения",
      warnings: "Предупреждений",
      queue_bans: "Запретов быстрого матча",
      tournament_bans: "Запретов турниров",
      suspensions: "Ограничений аккаунта",
      protective_holds: "Защитных блокировок",
      appeals_upheld: "Апелляций отклонено",
      appeals_granted: "Апелляций удовлетворено",
      corrections: "Мер отменено при исправлении",
    } as Record<string, string>,
    median: "Медиана от обращения до решения, дней",
    myStatus: "Сообщить о нарушении",
  },
  en: {
    rules: "Rules",
    rulesNote: "A sanction cites a specific version of a rule. A new version does not change earlier decisions.",
    source: "Source",
    procedure: "How a decision is taken",
    steps: [
      ["Report", "A player reports a violation with links. Only the portal team sees the report; the reporter is not disclosed."],
      ["Review", "A staff member gathers evidence. A protective hold of up to 72 hours is possible during the review; then a final decision or its removal."],
      ["Decision", "A measure states the rule and its version, the evidence, a confidence level and the reasoning. A digest of the evidence list is written to the hash-chained decision log, so a later change is detectable."],
      ["Measures", "A warning restricts nothing. A quick match and challenge ban or a tournament ban needs medium or high confidence and lasts 1–365 days. An account restriction needs high confidence; the account keeps reading and appealing."],
      ["Appeal", "Once within 14 days. A staff member who did not issue the measure decides. A granted appeal revokes the measure."],
      ["Reporting", "Below are counts for 90 days only. Values of 1 or 2 are hidden so that a number does not point at a person. Open reviews are not shown."],
    ] as Array<[string, string]>,
    report: "Reporting for 90 days",
    fewer: "fewer than 3",
    counts: {
      reports_received: "Reports received",
      reports_actioned: "Reports with action taken",
      reports_dismissed: "Reports with no violation found",
      warnings: "Warnings",
      queue_bans: "Quick match bans",
      tournament_bans: "Tournament bans",
      suspensions: "Account restrictions",
      protective_holds: "Protective holds",
      appeals_upheld: "Appeals rejected",
      appeals_granted: "Appeals granted",
      corrections: "Measures revoked as corrections",
    } as Record<string, string>,
    median: "Median days from report to decision",
    myStatus: "Report a violation",
  },
} satisfies Record<Locale, Record<string, unknown>>;
