import type { Locale } from "./i18n.ts";

/** Texts of the team finder (RU / EN). */
export const finderText = {
  ru: {
    title: "Поиск команды и игроков",
    lead: "Вакансии в составах, игроки, которые ищут команду, и те, кто ищет группу для игры. Без ставок и платных преимуществ.",
    tabs: { vacancy: "Вакансии команд", lft: "Ищут команду", lfg: "Ищут группу" } as Record<string, string>,
    kindShort: { vacancy: "Вакансия", lft: "LFT", lfg: "LFG" } as Record<string, string>,
    allGames: "Все игры",
    region: "Регион",
    roles: "Роли",
    languages: "Языки",
    level: "Уровень",
    schedule: "Когда играет",
    note: "О себе или о команде",
    slots: "Мест",
    show: "Показать",
    empty: "По этим условиям объявлений нет.",
    posted: "Опубликовано",
    expires: "до",
    yours: "Ваше объявление",
    ownTeam: "Вакансия вашей команды",
    applied: "Отклик отправлен, ждёт ответа.",
    moderateClose: "Снять объявление (модерация)",
    apply: "Откликнуться",
    applyMessage: "Сообщение (роли, опыт, когда можете играть)",
    send: "Отправить",
    invite: "Пригласить в команду",
    mine: "Мои объявления и отклики",
    newPost: "Разместить объявление",
    kind: "Что ищете",
    kindLft: "Команду (LFT)",
    kindLfg: "Группу для игры (LFG)",
    game: "Игра",
    publish: "Опубликовать на 30 дней",
    replaceNote: "Новое объявление того же вида и игры заменяет прежнее.",
    myPosts: "Мои открытые объявления",
    noPosts: "Открытых объявлений нет.",
    close: "Закрыть",
    toDecide: "Отклики, ждущие вашего решения",
    accept: "Принять",
    decline: "Отклонить",
    myApplications: "Мои отклики",
    noApplications: "Откликов пока нет.",
    withdraw: "Отозвать",
    statuses: { pending: "ждёт ответа", accepted: "принят", declined: "отклонён", withdrawn: "отозван" } as Record<string, string>,
    signIn: "Войдите, чтобы разместить объявление или откликнуться.",
    teamVacancies: "Вакансии команды",
    openVacancy: "Открыть вакансию",
    vacancyNote: "До трёх открытых вакансий; принятый отклик добавляет игрока в команду, вакансия закрывается, когда места заняты.",
    toFinder: "Все объявления",
  },
  en: {
    title: "Team finder",
    lead: "Roster vacancies, players looking for a team and players looking for a group to play with. No stakes, no paid advantage.",
    tabs: { vacancy: "Team vacancies", lft: "Looking for a team", lfg: "Looking for a group" } as Record<string, string>,
    kindShort: { vacancy: "Vacancy", lft: "LFT", lfg: "LFG" } as Record<string, string>,
    allGames: "All games",
    region: "Region",
    roles: "Roles",
    languages: "Languages",
    level: "Level",
    schedule: "When they play",
    note: "About you or the team",
    slots: "Places",
    show: "Show",
    empty: "No posts match these filters.",
    posted: "Posted",
    expires: "until",
    yours: "Your post",
    ownTeam: "Your team's vacancy",
    applied: "Application sent, waiting for an answer.",
    moderateClose: "Remove the post (moderation)",
    apply: "Apply",
    applyMessage: "Message (roles, experience, when you can play)",
    send: "Send",
    invite: "Invite to the team",
    mine: "My posts and applications",
    newPost: "Post an ad",
    kind: "Looking for",
    kindLft: "A team (LFT)",
    kindLfg: "A group to play with (LFG)",
    game: "Game",
    publish: "Publish for 30 days",
    replaceNote: "A new post of the same kind and game replaces the previous one.",
    myPosts: "My open posts",
    noPosts: "No open posts.",
    close: "Close",
    toDecide: "Applications waiting for your decision",
    accept: "Accept",
    decline: "Decline",
    myApplications: "My applications",
    noApplications: "No applications yet.",
    withdraw: "Withdraw",
    statuses: { pending: "waiting", accepted: "accepted", declined: "declined", withdrawn: "withdrawn" } as Record<string, string>,
    signIn: "Sign in to post or apply.",
    teamVacancies: "Team vacancies",
    openVacancy: "Open a vacancy",
    vacancyNote: "Up to three open vacancies; an accepted application adds the player to the team, and the vacancy closes when its places are filled.",
    toFinder: "All posts",
  },
} satisfies Record<Locale, Record<string, unknown>>;
