import type { Locale } from "./i18n.ts";

/** Readable names of the audit actions shown in a tournament's history; unknown actions show their code. */
const LABELS: Record<string, { ru: string; en: string }> = {
  "tournament.created": { ru: "Турнир создан", en: "Tournament created" },
  "tournament.updated": { ru: "Параметры изменены", en: "Settings changed" },
  "tournament.status": { ru: "Смена статуса", en: "Status changed" },
  "tournament.cloned": { ru: "Создана копия", en: "Copy created" },
  "tournament.seeds_set": { ru: "Посев изменён", en: "Seeds changed" },
  "tournament.started": { ru: "Турнир начат", en: "Tournament started" },
  "tournament.round_robin_started": { ru: "Старт круговой системы", en: "Round robin started" },
  "tournament.swiss_started": { ru: "Старт швейцарской системы", en: "Swiss started" },
  "tournament.swiss_round_paired": { ru: "Составлен тур швейцарской системы", en: "Swiss round paired" },
  "tournament.groups_started": { ru: "Старт групп", en: "Groups started" },
  "tournament.playoff_started": { ru: "Старт плей-офф", en: "Playoff started" },
  "tournament.playoff_skipped": { ru: "Плей-офф не проводится", en: "Playoff skipped" },
  "tournament.playoff_regenerated": { ru: "Плей-офф пересоздан", en: "Playoff regenerated" },
  "tournament.stage_started": { ru: "Старт следующего этапа", en: "Next stage started" },
  "tournament.stage_skipped": { ru: "Этап не проводится", en: "Stage skipped" },
  "tournament.stage_regenerated": { ru: "Этап пересоздан", en: "Stage regenerated" },
  "tournament.reopened_for_reset": { ru: "Назначен перезапуск финала", en: "Bracket reset scheduled" },
  "tournament.results_annulled": { ru: "Результаты аннулированы", en: "Results annulled" },
  "tournament.ffa_started": { ru: "Старт FFA", en: "FFA started" },
  "tournament.ffa_round_created": { ru: "Создан раунд FFA", en: "FFA round created" },
  "tournament.ffa_ended_early": { ru: "FFA завершён досрочно", en: "FFA ended early" },
  "tournament.leaderboard_started": { ru: "Старт leaderboard", en: "Leaderboard started" },
  "tournament.regenerated": { ru: "Структура пересоздана", en: "Structure regenerated" },
  "tournament.rescheduled": { ru: "Перенос расписания", en: "Schedule moved" },
  "tournament.waves_scheduled": { ru: "Тур распределён по площадкам", en: "Round placed on venues" },
  "tournament.venue_added": { ru: "Добавлена площадка", en: "Venue added" },
  "tournament.venue_removed": { ru: "Удалена площадка", en: "Venue removed" },
  "tournament.completed": { ru: "Турнир завершён", en: "Tournament completed" },
  "tournament.co_organizer_added": { ru: "Добавлен со-организатор", en: "Co-organiser added" },
  "tournament.co_organizer_removed": { ru: "Убран со-организатор", en: "Co-organiser removed" },
  "tournament.check_in_opened": { ru: "Открыт check-in", en: "Check-in opened" },
  "tournament.check_in_closed": { ru: "Закрыт check-in", en: "Check-in closed" },
  "tournament.prize_coins_set": { ru: "Назначена награда", en: "Award set" },
  "tournament.award_paid": { ru: "Выплачена награда", en: "Award paid" },
  "registration.created": { ru: "Заявка", en: "Application" },
  "registration.approved": { ru: "Заявка одобрена", en: "Application approved" },
  "registration.rejected": { ru: "Заявка отклонена", en: "Application rejected" },
  "registration.expired_at_start": { ru: "Нерассмотренные заявки закрыты при старте", en: "Undecided applications closed at the start" },
  "registration.withdrawn": { ru: "Заявка отозвана", en: "Application withdrawn" },
  "registration.checked_in": { ru: "Check-in участника", en: "Entrant checked in" },
  "registration.check_in_override": { ru: "Check-in отмечен организатором", en: "Check-in set by the organiser" },
  "registration.disqualified": { ru: "Дисквалификация", en: "Disqualification" },
  "registration.roster_changed": { ru: "Изменён состав", en: "Roster changed" },
  "registration.substituted": { ru: "Замена в составе", en: "Substitution" },
  "match.result_submitted": { ru: "Отправлен результат", en: "Result reported" },
  "match.result_confirmed": { ru: "Результат подтверждён", en: "Result confirmed" },
  "match.result_agreed": { ru: "Результаты сторон совпали", en: "Both sides agreed" },
  "match.results_conflict": { ru: "Результаты сторон разошлись", en: "Results conflict" },
  "match.official_result": { ru: "Решение судьи", en: "Referee decision" },
  "match.result_corrected": { ru: "Результат исправлен", en: "Result corrected" },
  "match.no_show": { ru: "Неявка", en: "No-show" },
  "match.referee_called": { ru: "Вызван судья", en: "Referee called" },
  "match.referee_call_closed": { ru: "Судья ответил на вызов", en: "Referee answered a call" },
  "match.paused": { ru: "Матч на паузе", en: "Match paused" },
  "match.bracket_repaired": { ru: "Сетка восстановлена после исправления", en: "Bracket repaired after a correction" },
  "match.veto": { ru: "Ход вето карт", en: "Map veto turn" },
  "match.veto_reset": { ru: "Вето сброшено", en: "Veto reset" },
  "match.resumed": { ru: "Матч продолжен", en: "Match resumed" },
  "tournament.incident_opened": { ru: "Записан инцидент", en: "Incident logged" },
  "tournament.incident_assigned": { ru: "Назначен ответственный за инцидент", en: "Incident assigned" },
  "tournament.incident_priority": { ru: "Изменён приоритет инцидента", en: "Incident priority changed" },
  "tournament.incident_escalated": { ru: "Инцидент эскалирован", en: "Incident escalated" },
  "tournament.incident_resolved": { ru: "Инцидент закрыт", en: "Incident closed" },
  "match.disputed": { ru: "Спор по матчу", en: "Match disputed" },
  "match.details_updated": { ru: "Изменены детали матча", en: "Match details changed" },
  "match.checked_in": { ru: "Check-in к матчу", en: "Match check-in" },
  "match.format_set": { ru: "Изменён формат матча", en: "Match format changed" },
  "match.schedule_override": { ru: "Расписание с пересечением подтверждено", en: "Schedule overlap confirmed" },
  "dispute.filed": { ru: "Оспорен решённый матч", en: "Decided match disputed" },
  "dispute.upheld": { ru: "Результат оставлен в силе", en: "Result upheld" },
  "dispute.overturned": { ru: "Результат отменён", en: "Result overturned" },
  "ffa.game_recorded": { ru: "Записан результат игры FFA", en: "FFA game recorded" },
  "ffa.game_corrected": { ru: "Исправлен результат игры FFA", en: "FFA game corrected" },
  "ffa.lobby_updated": { ru: "Изменены детали лобби", en: "Lobby details changed" },
  "ffa.dispute_filed": { ru: "Оспорена игра FFA", en: "FFA game disputed" },
  "ffa.dispute_upheld": { ru: "Игра FFA оставлена в силе", en: "FFA game upheld" },
};

export function historyLabel(action: string, lang: Locale): string {
  return LABELS[action]?.[lang] ?? action;
}
