import type { Locale } from "./i18n.ts";

/** Texts of the integrations page of an organising space and the developer documentation (RU / EN). */
export const integrationsText = {
  ru: {
    title: "API, вебхуки и виджеты",
    lead: "Подключите сайт или сервис вашего пространства к турнирам портала: чтение данных по ключу API, подписанные уведомления о событиях и встраиваемые виджеты. Работает для турниров этого пространства и только для них.",
    docs: "Документация для разработчиков",
    oneTime: "Покажется один раз",
    oneTimeKey: "Новый ключ API. Сохраните его в настройках вашего сервера: портал хранит только отпечаток ключа.",
    oneTimeSecret: "Секрет подписи вебхука. Сохраните его на сервере-получателе: им проверяется подпись каждого запроса.",
    saved: "Я сохранил",
    keys: "Ключи API",
    keysLead:
      "Ключ даёт чтение турниров, участников, матчей и таблиц этого пространства. До 10 действующих ключей, 120 запросов в минуту на ключ. Ключ — секрет сервера: не вставляйте его в код страниц.",
    keyName: "Название ключа (для себя)",
    createKey: "Создать ключ",
    noKeys: "Ключей пока нет.",
    created: "создан",
    lastUsed: "последний запрос",
    never: "не использовался",
    revoked: "отозван",
    active: "действует",
    revoke: "Отозвать",
    hooks: "Вебхуки",
    hooksLead:
      "Портал отправляет POST с JSON на ваш HTTPS-адрес при выбранных событиях турниров этого пространства. Каждый запрос подписан (заголовки MV-Webhook-Id, MV-Webhook-Timestamp, MV-Webhook-Signature); при ошибке — повтор через 1, 5, 30, 120 и 360 минут. До 5 действующих адресов.",
    url: "Адрес получателя (https://…)",
    events: "События",
    eventNames: {
      "tournament.status_changed": "статус турнира изменился",
      "registration.created": "новая заявка",
      "registration.withdrawn": "заявка отозвана",
      "match.completed": "матч завершён",
      "match.corrected": "результат матча исправлен",
    } as Record<string, string>,
    addHook: "Добавить адрес",
    noHooks: "Адресов пока нет.",
    on: "включён",
    off: "выключен",
    pending: "в очереди",
    failed: "не доставлено",
    test: "Отправить тестовое событие",
    rotate: "Новый секрет",
    disable: "Выключить",
    enable: "Включить",
    plainSecrets: "Секреты подписи хранятся без шифрования: на сервере не задан ключ шифрования секретов (MFA_SECRET_KEY).",
    deliveries: "Последние доставки",
    noDeliveries: "Доставок пока не было.",
    attempts: "попыток",
    retry: "Повторить",
    statuses: { pending: "ждёт", delivered: "доставлено", failed: "не доставлено" } as Record<string, string>,
    widgets: "Виджеты",
    widgetsLead:
      "Вставьте код на свою страницу. Виджеты показывают опубликованные турниры, обновляются при каждом открытии и ведут на портал в новой вкладке. Регистрация проходит на портале.",
    calendar: "Календарь пространства",
    bracket: "Сетка",
    registration: "Регистрация",
    standings: "Таблица",
    preview: "посмотреть",
    noTournaments: "Опубликованных турниров пока нет — виджеты турниров появятся после публикации.",
    toSpace: "Пространство",
  },
  en: {
    title: "API, webhooks and widgets",
    lead: "Connect your space's website or service to the portal's tournaments: reading data with an API key, signed event notifications and embeddable widgets. It covers this space's tournaments and nothing else.",
    docs: "Developer documentation",
    oneTime: "Shown once",
    oneTimeKey: "New API key. Store it in your server's settings: the portal keeps only the key's fingerprint.",
    oneTimeSecret: "Webhook signing secret. Store it on the receiving server: it verifies the signature of every request.",
    saved: "I have saved it",
    keys: "API keys",
    keysLead:
      "A key reads this space's tournaments, participants, matches and tables. Up to 10 active keys, 120 requests a minute per key. A key is a server secret: never put it in page code.",
    keyName: "Key name (for yourself)",
    createKey: "Create a key",
    noKeys: "No keys yet.",
    created: "created",
    lastUsed: "last request",
    never: "never used",
    revoked: "revoked",
    active: "active",
    revoke: "Revoke",
    hooks: "Webhooks",
    hooksLead:
      "The portal sends a JSON POST to your HTTPS address on the chosen events of this space's tournaments. Every request is signed (headers MV-Webhook-Id, MV-Webhook-Timestamp, MV-Webhook-Signature); a failure is retried after 1, 5, 30, 120 and 360 minutes. Up to 5 active addresses.",
    url: "Receiver address (https://…)",
    events: "Events",
    eventNames: {
      "tournament.status_changed": "tournament status changed",
      "registration.created": "new registration",
      "registration.withdrawn": "registration withdrawn",
      "match.completed": "match completed",
      "match.corrected": "match result corrected",
    } as Record<string, string>,
    addHook: "Add the address",
    noHooks: "No addresses yet.",
    on: "on",
    off: "off",
    pending: "queued",
    failed: "not delivered",
    test: "Send a test event",
    rotate: "New secret",
    disable: "Turn off",
    enable: "Turn on",
    plainSecrets: "Signing secrets are stored unencrypted: the server has no secret encryption key (MFA_SECRET_KEY).",
    deliveries: "Latest deliveries",
    noDeliveries: "No deliveries yet.",
    attempts: "attempts",
    retry: "Retry",
    statuses: { pending: "waiting", delivered: "delivered", failed: "not delivered" } as Record<string, string>,
    widgets: "Widgets",
    widgetsLead:
      "Paste the code into your page. Widgets show published tournaments, refresh on every load and open the portal in a new tab. Registration happens on the portal.",
    calendar: "Space calendar",
    bracket: "Bracket",
    registration: "Registration",
    standings: "Standings",
    preview: "preview",
    noTournaments: "No published tournaments yet — tournament widgets appear once one is published.",
    toSpace: "Space",
  },
} satisfies Record<Locale, Record<string, unknown>>;

/** The iframe code of a widget. */
export const embedCode = (src: string, title: string, height = 520) =>
  `<iframe src="${src}" title="${title.replace(/"/g, "&quot;")}" width="100%" height="${height}" style="border:0;max-width:100%" loading="lazy"></iframe>`;
