import type { Locale } from "./i18n.ts";

/** Texts of the incident queue and of the match hold (RU / EN). */
export const liveopsText = {
  ru: {
    title: "Инциденты",
    lead: "Вызовы судьи от участников и инциденты, записанные персоналом. Сверху — срочные и эскалированные, затем по времени.",
    empty: "Открытых инцидентов нет.",
    kinds: { referee_call: "Вызов судьи", technical: "Техника", conduct: "Поведение", no_show: "Неявка", schedule: "Расписание", other: "Другое" } as Record<string, string>,
    priorities: { urgent: "Срочно", high: "Высокий", normal: "Обычный", low: "Низкий" } as Record<string, string>,
    escalated: "Эскалирован",
    overdue: "без ответа",
    minutes: "мин",
    side: "сторона",
    match: "Матч",
    from: "от",
    assignee: "Ответственный",
    unassigned: "не назначен",
    takeIt: "Взять себе",
    more: "Ещё действия",
    assign: "Назначить",
    nobody: "Никому",
    priority: "Приоритет",
    save: "Сохранить",
    escalateNote: "Почему нужна помощь владельцев",
    escalate: "Эскалировать",
    resolveNote: "Ответ автору",
    resolve: "Закрыть",
    newTitle: "Записать инцидент",
    kind: "Вид",
    noMatch: "Без матча",
    message: "Что случилось",
    create: "Записать",
    resolvedTitle: "Закрытые за 7 дней",
    resolvedBy: "закрыл",
    noComment: "без комментария",
    pausedBanner: "Матч на паузе у судьи",
    pauseTitle: "Пауза матча",
    pauseReason: "Причина паузы (её увидят обе стороны)",
    pause: "Поставить на паузу",
    resume: "Продолжить матч",
    pauseNote: "Пока матч на паузе, стороны не могут отправить или подтвердить счёт, отметиться или получить неявку. Решение судьи снимает паузу.",
    overrideNote: "Обоснование обязательно, если решение расходится с отправленным счётом или закрывает спор.",
    remind: "Напомнить судье",
    remindNote: "Ответа нет дольше 5 минут: напоминание передаст вызов владельцам и администраторам пространства.",
    escalatedNote: "Вызов передан владельцам и администраторам пространства.",
  },
  en: {
    title: "Incidents",
    lead: "Participants' calls to the referee and incidents logged by staff. Urgent and escalated first, then by time.",
    empty: "No open incidents.",
    kinds: { referee_call: "Referee call", technical: "Technical", conduct: "Conduct", no_show: "No-show", schedule: "Schedule", other: "Other" } as Record<string, string>,
    priorities: { urgent: "Urgent", high: "High", normal: "Normal", low: "Low" } as Record<string, string>,
    escalated: "Escalated",
    overdue: "unanswered",
    minutes: "min",
    side: "side",
    match: "Match",
    from: "from",
    assignee: "Assignee",
    unassigned: "unassigned",
    takeIt: "Take it",
    more: "More actions",
    assign: "Assign",
    nobody: "Nobody",
    priority: "Priority",
    save: "Save",
    escalateNote: "Why the owners' help is needed",
    escalate: "Escalate",
    resolveNote: "Reply to the reporter",
    resolve: "Close",
    newTitle: "Log an incident",
    kind: "Kind",
    noMatch: "No match",
    message: "What happened",
    create: "Log",
    resolvedTitle: "Closed in the last 7 days",
    resolvedBy: "closed by",
    noComment: "no comment",
    pausedBanner: "The referee has paused this match",
    pauseTitle: "Match hold",
    pauseReason: "Reason (both sides see it)",
    pause: "Pause the match",
    resume: "Resume the match",
    pauseNote: "While paused, the sides cannot report or confirm a score, check in or be recorded as no-show. A referee decision ends the pause.",
    overrideNote: "A reason is required when the decision differs from the reported score or settles a dispute.",
    remind: "Remind the referee",
    remindNote: "No answer for over 5 minutes: a reminder passes the call to the space's owners and administrators.",
    escalatedNote: "The call went to the space's owners and administrators.",
  },
} satisfies Record<Locale, Record<string, unknown>>;
