/** Texts of streams, recordings, the media centre and overlays (MV-MEDIA-1), RU / EN. */
export const mediaText = {
  ru: {
    title: "Медиа",
    lead: "Трансляции идущих турниров, расписание эфиров и записи матчей. Ссылки назначают организаторы событий. Счётчиков зрителей нет: у портала нет таких данных.",
    live: "Сейчас идут",
    liveNote: "Турнир или матч сейчас идёт на портале; в эфире ли канал в эту минуту, портал не знает.",
    noLive: "Сейчас нет идущих событий с трансляцией.",
    upcoming: "Расписание",
    noUpcoming: "Запланированных трансляций нет.",
    vods: "Записи",
    noVods: "Записей пока нет.",
    allGames: "Все игры",
    show: "Показать",
    open: "Открыть: {platform}",
    play: "Смотреть здесь",
    playNote: "Плеер загрузится с сайта платформы только после нажатия.",
    event: "Трансляция события",
    matchStream: "Трансляция матча",
    vod: "Запись",
    when: "Начало",
    languages: { ru: "RU", en: "EN", other: "другой язык" } as Record<string, string>,
    creators: "Авторам и каналам",
    creatorsLead: "Хотите вести трансляции турниров портала? Оставьте заявку: она попадёт в рабочую очередь команды портала.",
    manage: "Трансляции и записи",
    manageLead:
      "Назначьте ссылку на эфир или запись всему событию или одному матчу. Ссылка появится на страницах турнира и матча и в разделе «Медиа»; игроки матча получат уведомление. Каналы Twitch и видео YouTube можно смотреть прямо на портале.",
    url: "Ссылка (https://)",
    label: "Подпись, например «Основной эфир»",
    kind: "Вид",
    kinds: { live: "Эфир", vod: "Запись" } as Record<string, string>,
    scope: "Что показывает",
    wholeEvent: "Всё событие",
    language: "Язык комментария",
    anyLanguage: "Не указан",
    startsAt: "Начало эфира (необязательно)",
    rights: "У организатора есть права на трансляцию игры и показ участников; участники приняли правила турнира",
    add: "Назначить",
    remove: "Удалить",
    none: "Ссылок пока нет.",
    by: "права подтвердил",
    overlay: "Оверлей для OBS",
    overlayLead:
      "Браузерный источник с прозрачным фоном: имена и счёт берутся из записи матча и обновляются каждые 10 секунд. Для своих инструментов — те же данные в JSON.",
    overlayMatch: "Матч",
    reported: "заявлено",
    official: "официально",
    final: "итог",
    noScore: "—",
    tbd: "Ожидается",
  },
  en: {
    title: "Media",
    lead: "Streams of events under way, the broadcast schedule and match recordings. Event organisers assign the links. There are no viewer counts: the portal has no such data.",
    live: "Under way",
    liveNote: "The tournament or match is under way on the portal; whether the channel is on air this minute, the portal does not know.",
    noLive: "No event with a stream is under way right now.",
    upcoming: "Schedule",
    noUpcoming: "No streams are scheduled.",
    vods: "Recordings",
    noVods: "No recordings yet.",
    allGames: "All games",
    show: "Show",
    open: "Open: {platform}",
    play: "Watch here",
    playNote: "The player loads from the platform's site only after you click.",
    event: "Event stream",
    matchStream: "Match stream",
    vod: "Recording",
    when: "Starts",
    languages: { ru: "RU", en: "EN", other: "other language" } as Record<string, string>,
    creators: "For creators and channels",
    creatorsLead: "Want to broadcast the portal's tournaments? Apply: the request goes to the portal team's work queue.",
    manage: "Streams and recordings",
    manageLead:
      "Assign a stream or recording link to the whole event or to one match. It shows on the tournament and match pages and in Media; the match's players are notified. Twitch channels and YouTube videos play right on the portal.",
    url: "Link (https://)",
    label: "Caption, e.g. “Main stream”",
    kind: "Type",
    kinds: { live: "Stream", vod: "Recording" } as Record<string, string>,
    scope: "Shows",
    wholeEvent: "The whole event",
    language: "Commentary language",
    anyLanguage: "Not set",
    startsAt: "Stream start (optional)",
    rights: "The organiser holds the rights to broadcast the game and show the participants; the participants accepted the tournament rules",
    add: "Assign",
    remove: "Remove",
    none: "No links yet.",
    by: "rights confirmed by",
    overlay: "OBS overlay",
    overlayLead: "A browser source with a transparent background: names and score come from the match record and refresh every 10 seconds. The same data as JSON for your own tools.",
    overlayMatch: "Match",
    reported: "reported",
    official: "official",
    final: "final",
    noScore: "—",
    tbd: "TBD",
  },
};
