import type { Locale } from "./i18n.ts";
import { gameBySlug } from "./games.ts";
import { countryName } from "./countries.ts";

/** Texts of portal-team messages and the system tab (MV-STAFF-1). */
export const messageText = {
  ru: {
    title: "Сообщения игрокам",
    lead: "Сообщение приходит в портал: уведомление и отдельная страница; email не используется. Операционное (правила, работы, безопасность) получают все в сегменте. Маркетинговое — только те, кто согласился на рассылки, и не больше {cap} маркетинговых сообщений одному человеку за {days} дней; остальные получают статус «пропущено» с причиной.",
    rights:
      "Маркетинговые пишет роль «маркетинг», операционные — «поддержка» или «инфраструктура». Отправка требует код второго фактора, подтверждённый в последние 15 минут.",
    create: "Новое сообщение",
    kind: "Тип",
    kinds: {
      operational: "Операционное",
      marketing: "Маркетинговое",
    } as Record<string, string>,
    subject: "Заголовок (3–120 символов)",
    body: "Текст (до 2000 символов)",
    audience: "Аудитория",
    audiences: {
      all: "Все активные аккаунты",
      players: "Игроки",
      organizers: "Организаторы",
    } as Record<string, string>,
    game: "Игра",
    country: "Страна",
    any: "Любая",
    active: "Заходили в портал",
    activeAny: "Не важно",
    activeDays: "за {n} дней",
    saveDraft: "Сохранить черновик",
    saveTemplate: "Сохранить как шаблон",
    save: "Сохранить",
    edit: "Изменить",
    drafts: "Черновики и шаблоны",
    noDrafts: "Черновиков и шаблонов нет.",
    sent: "Отправленные",
    noSent: "Сообщений ещё не отправляли.",
    draft: "Черновик",
    template: "Шаблон",
    reach: "Получат сейчас: {reach} из {total}",
    skippedConsent: "без согласия: {n}",
    skippedCap: "достигли лимита частоты: {n}",
    send: "Отправить",
    useTemplate: "Создать черновик по шаблону",
    copy: "Копия в черновики",
    asTemplate: "Сохранить как шаблон",
    remove: "Удалить",
    by: "автор",
    sentBy: "отправил",
    delivered: "доставлено",
    opened: "открыли",
    stat: {
      sent: "доставлено",
      skipped_consent: "без согласия",
      skipped_cap: "лимит частоты",
    } as Record<string, string>,
    readOnly: "Ваша роль может читать раздел, но не писать сообщения этого типа.",
    page: {
      from: "Сообщение команды MAXIMUS VEGAS",
      marketingNote: "Вы получили это сообщение, потому что согласились получать новости и анонсы. Отказаться можно в настройках.",
      settings: "Настройки согласий",
      operationalNote: "Это операционное сообщение о работе сервиса: оно приходит всем, кого касается.",
    },
  },
  en: {
    title: "Messages to players",
    lead: "A message arrives in the portal: a notification and its own page; email is not used. Everyone in the segment gets an operational message (rules, maintenance, safety). A marketing message reaches only people who agreed to receive news, and no more than {cap} marketing messages per person in {days} days; the rest get a skipped status with the reason.",
    rights:
      "Marketing messages are written by the marketing role, operational ones by support or infrastructure. Sending needs a second-factor code confirmed in the last 15 minutes.",
    create: "New message",
    kind: "Type",
    kinds: { operational: "Operational", marketing: "Marketing" } as Record<string, string>,
    subject: "Title (3–120 characters)",
    body: "Text (up to 2000 characters)",
    audience: "Audience",
    audiences: {
      all: "All active accounts",
      players: "Players",
      organizers: "Organisers",
    } as Record<string, string>,
    game: "Game",
    country: "Country",
    any: "Any",
    active: "Visited the portal",
    activeAny: "Any time",
    activeDays: "in {n} days",
    saveDraft: "Save draft",
    saveTemplate: "Save as template",
    save: "Save",
    edit: "Edit",
    drafts: "Drafts and templates",
    noDrafts: "No drafts or templates.",
    sent: "Sent",
    noSent: "No messages sent yet.",
    draft: "Draft",
    template: "Template",
    reach: "Would reach now: {reach} of {total}",
    skippedConsent: "without consent: {n}",
    skippedCap: "at the frequency cap: {n}",
    send: "Send",
    useTemplate: "New draft from template",
    copy: "Copy to drafts",
    asTemplate: "Save as template",
    remove: "Delete",
    by: "author",
    sentBy: "sent by",
    delivered: "delivered",
    opened: "opened",
    stat: {
      sent: "delivered",
      skipped_consent: "no consent",
      skipped_cap: "frequency cap",
    } as Record<string, string>,
    readOnly: "Your role can read this section but cannot write messages of this type.",
    page: {
      from: "Message from the MAXIMUS VEGAS team",
      marketingNote: "You received this message because you agreed to receive news and announcements. You can opt out in settings.",
      settings: "Consent settings",
      operationalNote: "This is an operational message about the service: everyone it concerns receives it.",
    },
  },
};

export function segmentLabel(
  lang: Locale,
  s: {
    audience?: string;
    game?: string;
    country?: string;
    activeDays?: number;
  },
) {
  const x = messageText[lang];
  const parts = [x.audiences[s.audience ?? "all"] ?? s.audience];
  if (s.game) parts.push(gameBySlug(s.game)?.name ?? s.game);
  if (s.country) parts.push(countryName(s.country, lang));
  if (s.activeDays) parts.push(`${x.active.toLowerCase()} ${x.activeDays.replace("{n}", String(s.activeDays))}`);
  return parts.join(" · ");
}

export const systemText = {
  ru: {
    title: "Состояние системы",
    lead: "Живые данные этого развёртывания: база, очереди, задержки, ошибки и регламентные задачи. Значения ключей не показываются — только есть ли настройка.",
    services: "Сервисы",
    database: "База данных",
    latency: "задержка {ms} мс",
    size: "размер",
    migration: "Схема",
    mail: "Почта",
    payments: "Приём оплат",
    connected: "подключена",
    notConnected: "не подключена",
    on: "включён",
    off: "выключен",
    queues: "Очереди и ошибки",
    mailQueue: "Письма в очереди",
    mailFailed: "Письма с ошибкой",
    hookQueue: "Webhook-доставки в очереди",
    hookFailed: "Webhook-доставки с ошибкой",
    oldest: "самое старое ждёт с",
    incidents: "Открытые инциденты матчей",
    quickQueue: "Игроков в очереди быстрого матча",
    runs: "Регламентные задачи",
    noRuns: "Регламентная задача ещё не запускалась на этой базе.",
    lastRun: "последний запуск",
    config: "Настройки (только наличие)",
    present: "есть",
    missing: "нет",
    configNames: {
      database: "Строка подключения к базе",
      secretKey: "Ключ шифрования секретов",
      cronSecret: "Секрет регламентных задач",
      siteUrl: "Адрес сайта",
    } as Record<string, string>,
    features: "Функции",
    featuresLead:
      "Выключение останавливает только начало нового: начатое можно завершить, покинуть или решить. Сотрудники портала продолжают пользоваться функцией, чтобы проверить исправление.",
    featureNames: {
      quick_match: "Быстрый матч и группы",
      challenges: "Вызовы 1v1",
      finder: "Поиск команды и игроков",
      scouting: "Скаутинг",
      clans: "Кланы и клановые войны",
      transfers: "Переходы игроков",
      venues: "Площадки и гостевые пропуска",
      integrations: "API, ключи и webhooks",
    } as Record<string, string>,
    enabled: "включена",
    disabled: "выключена",
    turnOff: "Выключить",
    turnOn: "Включить",
    note: "Заметка для коллег",
    changed: "изменил",
    maintenance: "Режим обслуживания",
    maintenanceLead:
      "Игроки и организаторы видят баннер и не могут выполнять действия; вход и выход работают. Сотрудники работают как обычно. Нужен код второго фактора, подтверждённый в последние 15 минут.",
    maintenanceOn: "Включить обслуживание",
    maintenanceOff: "Выключить обслуживание",
    maintenanceNote: "Текст для пользователей (до 300 символов)",
    maintenanceActive: "Обслуживание включено с",
  },
  en: {
    title: "System status",
    lead: "Live data of this deployment: database, queues, delays, errors and scheduled jobs. Key values are never shown — only whether a setting is present.",
    services: "Services",
    database: "Database",
    latency: "latency {ms} ms",
    size: "size",
    migration: "Schema",
    mail: "Email",
    payments: "Payment collection",
    connected: "connected",
    notConnected: "not connected",
    on: "on",
    off: "off",
    queues: "Queues and errors",
    mailQueue: "Emails queued",
    mailFailed: "Emails failed",
    hookQueue: "Webhook deliveries queued",
    hookFailed: "Webhook deliveries failed",
    oldest: "oldest waiting since",
    incidents: "Open match incidents",
    quickQueue: "Players in the quick-match queue",
    runs: "Scheduled jobs",
    noRuns: "The scheduled job has not run against this database yet.",
    lastRun: "last run",
    config: "Settings (presence only)",
    present: "set",
    missing: "not set",
    configNames: {
      database: "Database connection",
      secretKey: "Secret encryption key",
      cronSecret: "Scheduled job secret",
      siteUrl: "Site address",
    } as Record<string, string>,
    features: "Features",
    featuresLead:
      "Switching off stops only the start of something new: what is under way can be finished, left or decided. Portal staff keep using the feature to check a fix.",
    featureNames: {
      quick_match: "Quick match and parties",
      challenges: "1v1 challenges",
      finder: "Team and player finder",
      scouting: "Scouting",
      clans: "Clans and clan wars",
      transfers: "Player transfers",
      venues: "Venues and guest passes",
      integrations: "API, keys and webhooks",
    } as Record<string, string>,
    enabled: "on",
    disabled: "off",
    turnOff: "Switch off",
    turnOn: "Switch on",
    note: "Note for colleagues",
    changed: "changed by",
    maintenance: "Maintenance mode",
    maintenanceLead:
      "Players and organisers see a banner and cannot take actions; signing in and out works. Staff work as usual. Needs a second-factor code confirmed in the last 15 minutes.",
    maintenanceOn: "Start maintenance",
    maintenanceOff: "End maintenance",
    maintenanceNote: "Text for users (up to 300 characters)",
    maintenanceActive: "Maintenance on since",
  },
};
