import type { Locale } from "./i18n.ts";

/** Texts of quick match with parties, the ready check and ratings (RU / EN). */
export const quickText = {
  ru: {
    lead: "Один или группой до пяти игроков: портал подбирает реальных соперников того же размера по рейтингу и региону. Когда соперник найден, все игроки подтверждают готовность за 90 секунд — только тогда матч создаётся. Без ставок, ботов и выдуманных соперников.",
    search: "Поиск",
    game: "Игра",
    region: "Регион",
    regionHint: "необязательно; другой регион допускается после 2 минут ожидания",
    find: "Найти соперника",
    findParty: "Искать соперников для группы",
    leaderStarts: "Поиск для группы запускает лидер.",
    waiting: "ждут",
    queued: "Вы в очереди",
    queuedParty: "Группа в очереди",
    waited: "ожидание",
    min: "мин",
    sec: "с",
    window: "допуск разницы рейтинга",
    anyGap: "любая разница рейтинга",
    cancel: "Отменить поиск",
    keepOpen: "Держите страницу открытой: когда соперник найдётся, каждый игрок подтверждает готовность за 90 секунд, иначе очередь закроется на время.",
    cooldown: "Очередь недоступна до",
    cooldownWhy: "проверка готовности не подтверждена. Повторы за сутки удлиняют паузу: 5, 10, 20, 40, затем 60 минут.",
    checkTitle: "Соперник найден — подтвердите готовность",
    yourSide: "Ваша сторона",
    opponents: "Соперники",
    readyOf: "готовы",
    of: "из",
    ready: "Готов",
    decline: "Отказаться",
    youReady: "Вы готовы. Ждём остальных игроков.",
    answers: { ready: "готов", declined: "отказался", none: "ждём" } as Record<string, string>,
    why: "Почему этот соперник",
    size: "Размер",
    vs: "на",
    gap: "Разница среднего рейтинга сторон",
    allowed: "допуск",
    anyAfter: "любая после 5 минут ожидания",
    regionSame: "Регион совпадает",
    regionAny: "Регион не указан у одной из сторон",
    regionRelaxed: "Регионы разные — допущено после 2 минут ожидания",
    waitedLong: "Ожидание дольше",
    declineNote: "Отказ или молчание выводят вас из очереди и временно закрывают её; подтвердившие игроки возвращаются в очередь на прежнее место.",
    last: {
      matched: "Все подтвердили готовность — матч создан, он в списке ниже.",
      returned: "Прошлый матч не состоялся: кто-то не подтвердил готовность. Вы снова в очереди на прежнем месте.",
      removed: "Прошлый матч не состоялся: игрок вашей группы не подтвердил готовность, группа вышла из очереди.",
      dodged: "Вы не подтвердили готовность — очередь временно закрыта.",
    } as Record<string, string>,
    party: "Группа",
    partyLead: "Играйте вместе: лидер приглашает до четырёх игроков и запускает поиск. Группа встаёт в очередь целиком и ищет соперников того же размера.",
    createParty: "Создать группу",
    partyAfterSearch: "Группу можно создать после окончания поиска.",
    leader: "лидер",
    rating: "рейтинг",
    invite: "Пригласить",
    inviteLabel: "Имя пользователя",
    invited: "Приглашены",
    revoke: "Отозвать",
    remove: "Исключить",
    leave: "Выйти из группы",
    disband: "Распустить группу",
    incoming: "Приглашения в группу",
    accept: "Вступить",
    declineInvite: "Отклонить",
    players: "игроков",
    frozen: "Состав меняется после отмены поиска.",
    ratings: "Мой рейтинг быстрого матча",
    ratingsNote: "Рейтинг MV-RATING-1 меняют только быстрые матчи: старт 1000, первые 10 матчей игры — шаг крупнее. Вызовы 1v1 — товарищеские.",
    noRatings: "Рейтинг появится после первого быстрого матча с подтверждённым результатом.",
    matches: "матчей",
    peak: "пик",
    history: "История на странице профиля",
    myMatches: "Мои быстрые матчи",
    challengeSomeone: "Вызвать конкретного игрока",
    resultNote: "Результат сообщает и подтверждает лидер каждой стороны; спорный результат решает команда портала.",
  },
  en: {
    lead: "Alone or as a party of up to five: the portal finds real opponents of the same size by rating and region. When an opponent is found, every player confirms within 90 seconds — only then is the match created. No stakes, no bots, no invented opponents.",
    search: "Search",
    game: "Game",
    region: "Region",
    regionHint: "optional; another region is accepted after 2 minutes of waiting",
    find: "Find an opponent",
    findParty: "Find opponents for the party",
    leaderStarts: "The party leader starts the search.",
    waiting: "waiting",
    queued: "You are queued",
    queuedParty: "The party is queued",
    waited: "waiting",
    min: "min",
    sec: "s",
    window: "allowed rating gap",
    anyGap: "any rating gap",
    cancel: "Cancel the search",
    keepOpen: "Keep this page open: when an opponent is found, every player confirms within 90 seconds, or the queue closes for a while.",
    cooldown: "The queue is unavailable until",
    cooldownWhy: "a ready check was not confirmed. Repeats within a day lengthen the pause: 5, 10, 20, 40, then 60 minutes.",
    checkTitle: "Opponent found — confirm you are ready",
    yourSide: "Your side",
    opponents: "Opponents",
    readyOf: "ready",
    of: "of",
    ready: "Ready",
    decline: "Decline",
    youReady: "You are ready. Waiting for the other players.",
    answers: { ready: "ready", declined: "declined", none: "waiting" } as Record<string, string>,
    why: "Why this opponent",
    size: "Size",
    vs: "v",
    gap: "Gap between the sides' average ratings",
    allowed: "allowed",
    anyAfter: "any after 5 minutes of waiting",
    regionSame: "Same region",
    regionAny: "One side did not state a region",
    regionRelaxed: "Different regions — accepted after 2 minutes of waiting",
    waitedLong: "Longer wait",
    declineNote: "Declining or not answering takes you out of the queue and closes it for a while; players who confirmed return to the queue in their previous place.",
    last: {
      matched: "Everyone confirmed — the match is created and listed below.",
      returned: "The last match did not happen: someone did not confirm. You are back in the queue in your previous place.",
      removed: "The last match did not happen: a player of your party did not confirm, so the party left the queue.",
      dodged: "You did not confirm — the queue is closed for a while.",
    } as Record<string, string>,
    party: "Party",
    partyLead: "Play together: the leader invites up to four players and starts the search. The party queues as a whole and looks for opponents of the same size.",
    createParty: "Create a party",
    partyAfterSearch: "You can create a party once the search ends.",
    leader: "leader",
    rating: "rating",
    invite: "Invite",
    inviteLabel: "Username",
    invited: "Invited",
    revoke: "Withdraw",
    remove: "Remove",
    leave: "Leave the party",
    disband: "Disband the party",
    incoming: "Party invitations",
    accept: "Join",
    declineInvite: "Decline",
    players: "players",
    frozen: "The roster changes after the search is cancelled.",
    ratings: "My quick match rating",
    ratingsNote: "Only quick matches change the MV-RATING-1 rating: it starts at 1000 and moves faster in a game's first 10 matches. 1v1 challenges are friendly.",
    noRatings: "Your rating appears after your first quick match with a confirmed result.",
    matches: "matches",
    peak: "peak",
    history: "History on the profile page",
    myMatches: "My quick matches",
    challengeSomeone: "Challenge a specific player",
    resultNote: "Each side's leader reports and confirms the result; the portal team decides disputed results.",
  },
} satisfies Record<Locale, Record<string, unknown>>;

/** Texts of the rating block on a player's profile. */
export const ratingText = {
  ru: {
    title: "Рейтинг быстрого матча",
    note: "MV-RATING-1: старт 1000; меняется только по быстрым матчам с подтверждённым результатом.",
    matches: "матчей",
    wins: "побед",
    peak: "пик",
    recent: "Последние изменения",
    win: "победа",
    loss: "поражение",
    empty: "Быстрых матчей с подтверждённым результатом пока нет.",
  },
  en: {
    title: "Quick match rating",
    note: "MV-RATING-1: starts at 1000; changes only through quick matches with a confirmed result.",
    matches: "matches",
    wins: "wins",
    peak: "peak",
    recent: "Recent changes",
    win: "win",
    loss: "loss",
    empty: "No quick matches with a confirmed result yet.",
  },
} satisfies Record<Locale, Record<string, unknown>>;
