import type { Locale } from "./i18n.ts";

/** Texts of the scouting page (RU / EN). */
export const scoutText = {
  ru: {
    title: "Скаутинг",
    lead: "Поиск игроков по открытым профилям: игра, страна, рейтинг быстрого матча, объявление «ищу команду», недавняя активность. Сохраняйте фильтры и ведите список наблюдения — игрок не узнаёт, кто за ним наблюдает.",
    game: "Игра",
    anyGame: "Любая игра",
    country: "Страна",
    anyCountry: "Любая страна",
    minRating: "Рейтинг от",
    maxRating: "Рейтинг до",
    ratingHint: "Рейтинг считается по выбранной игре; без матчей — 1000.",
    lft: "Только ищущие команду",
    active: "Активность",
    anyTime: "За любое время",
    days: { 7: "за 7 дней", 30: "за 30 дней", 90: "за 90 дней" } as Record<string, string>,
    text: "Имя или имя пользователя",
    search: "Искать",
    reset: "Сбросить",
    results: "Найдено",
    firstN: "— показаны первые 40, уточните фильтр.",
    empty: "Под этот фильтр открытых профилей нет.",
    noQuery: "Задайте хотя бы одно условие — или посмотрите всех с открытым профилем.",
    rating: "рейтинг",
    matches: "матчей",
    tournaments: "турниров",
    lftBadge: "ищет команду",
    lastActive: "активность",
    never: "нет данных",
    watch: "Наблюдать",
    unwatch: "Не наблюдать",
    watching: "в списке",
    saveFilter: "Сохранить фильтр",
    filterName: "Название фильтра",
    save: "Сохранить",
    saved: "Мои фильтры",
    noSaved: "Сохранённых фильтров нет.",
    apply: "Применить",
    delete: "Удалить",
    watchlist: "Список наблюдения",
    noWatch: "Список пуст. Нажмите «Наблюдать» на карточке игрока.",
    note: "Заметка (видна только вам)",
    best: "лучший рейтинг",
    lftIn: "ищет команду",
    added: "добавлен",
    privacy: "Показываются только открытые профили. Если игрок закроет профиль, он исчезнет из поиска и списков наблюдения.",
  },
  en: {
    title: "Scouting",
    lead: "Find players among public profiles: game, country, quick match rating, a looking-for-team post, recent activity. Save filters and keep a watchlist — a player is not told who watches them.",
    game: "Game",
    anyGame: "Any game",
    country: "Country",
    anyCountry: "Any country",
    minRating: "Rating from",
    maxRating: "Rating to",
    ratingHint: "The rating is per the chosen game; without matches it counts as 1000.",
    lft: "Looking for a team only",
    active: "Activity",
    anyTime: "Any time",
    days: { 7: "in 7 days", 30: "in 30 days", 90: "in 90 days" } as Record<string, string>,
    text: "Name or username",
    search: "Search",
    reset: "Reset",
    results: "Found",
    firstN: "— the first 40 are shown; narrow the filter.",
    empty: "No public profiles match this filter.",
    noQuery: "Set at least one condition — or browse everyone with a public profile.",
    rating: "rating",
    matches: "matches",
    tournaments: "tournaments",
    lftBadge: "looking for a team",
    lastActive: "activity",
    never: "no data",
    watch: "Watch",
    unwatch: "Stop watching",
    watching: "on your list",
    saveFilter: "Save this filter",
    filterName: "Filter name",
    save: "Save",
    saved: "My filters",
    noSaved: "No saved filters.",
    apply: "Apply",
    delete: "Delete",
    watchlist: "Watchlist",
    noWatch: "The list is empty. Press “Watch” on a player's card.",
    note: "Note (only you see it)",
    best: "best rating",
    lftIn: "looking for a team",
    added: "added",
    privacy: "Only public profiles are shown. If a player makes their profile private, they leave search and every watchlist.",
  },
} satisfies Record<Locale, Record<string, unknown>>;
