import type { Locale } from "./i18n.ts";

/** Texts of transfers and roster history (RU / EN). */
export const transferText = {
  ru: {
    transfers: "Переходы",
    lead: "Переход из другой команды этой игры: предлагает владелец или капитан этой команды, соглашаются игрок и его команда. На ответ 7 дней. Оспорить состоявшийся переход можно 14 дней — решает команда портала.",
    propose: "Предложить переход",
    player: "Имя пользователя игрока",
    note: "Сообщение (необязательно)",
    send: "Отправить предложение",
    offerToYou: "Вам предлагают переход",
    from: "из",
    to: "в",
    accept: "Согласиться",
    decline: "Отказаться",
    cancel: "Отозвать",
    needYou: "Ждёт согласия вашей команды",
    waiting: "ждёт ответа",
    playerOk: "игрок согласен",
    teamOk: "команда согласна",
    until: "до",
    statuses: { proposed: "предложен", completed: "состоялся", declined: "отклонён", cancelled: "отозван", expired: "истёк", reversed: "отменён решением" } as Record<string, string>,
    dispute: "Оспорить переход",
    disputeReason: "Что не так (от 20 символов; решает команда портала)",
    disputeOpen: "спор на рассмотрении",
    disputeUpheld: "спор: переход в силе",
    disputeReversed: "спор: переход отменён",
    none: "Переходов не было.",
    history: "История состава",
    noHistory: "Изменений состава пока нет.",
    events: {
      joined: "вступил",
      left: "вышел",
      removed: "исключён",
      transferred_in: "перешёл в команду",
      transferred_out: "перешёл в другую команду",
      returned_in: "возвращён решением по спору",
      returned_out: "возвращён в прежнюю команду",
    } as Record<string, string>,
    teams: "Команды и переходы",
  },
  en: {
    transfers: "Transfers",
    lead: "A transfer from another team of this game: this team's owner or captain proposes, the player and their team agree. 7 days to answer. A completed transfer can be disputed for 14 days — the portal team decides.",
    propose: "Propose a transfer",
    player: "Player's username",
    note: "Message (optional)",
    send: "Send the proposal",
    offerToYou: "You are offered a transfer",
    from: "from",
    to: "to",
    accept: "Agree",
    decline: "Decline",
    cancel: "Withdraw",
    needYou: "Waiting for your team's consent",
    waiting: "waiting for an answer",
    playerOk: "player agreed",
    teamOk: "team agreed",
    until: "until",
    statuses: { proposed: "proposed", completed: "done", declined: "declined", cancelled: "withdrawn", expired: "expired", reversed: "reversed by a decision" } as Record<string, string>,
    dispute: "Dispute the transfer",
    disputeReason: "What is wrong (20 characters or more; the portal team decides)",
    disputeOpen: "dispute under review",
    disputeUpheld: "dispute: the transfer stands",
    disputeReversed: "dispute: the transfer was reversed",
    none: "No transfers yet.",
    history: "Roster history",
    noHistory: "No roster changes yet.",
    events: {
      joined: "joined",
      left: "left",
      removed: "removed",
      transferred_in: "transferred in",
      transferred_out: "transferred out",
      returned_in: "returned by a dispute decision",
      returned_out: "returned to the previous team",
    } as Record<string, string>,
    teams: "Teams and transfers",
  },
} satisfies Record<Locale, Record<string, unknown>>;
