import type { Locale } from "./i18n.ts";

/** Texts of venues and QR passes (RU / EN). */
export const venueText = {
  ru: {
    title: "Клубы и площадки",
    lead: "Подтверждённые площадки: киберспортивные клубы, арены, MAXIMUS Games House и Clubhouse. Адрес и статус каждой площадки проверены командой портала; турниры на площадке проходят с QR-пропуском.",
    city: "Город",
    anyCity: "Все города",
    search: "Название площадки",
    game: "Игра",
    games: "Игры на площадке",
    anyGame: "Все игры",
    anyKind: "Все типы",
    anyCountry: "Все страны",
    reset: "Сбросить фильтры",
    noResults: "Нет площадок по выбранным фильтрам.",
    limited: "Показаны первые 200 площадок. Уточните фильтры, чтобы найти нужную.",
    latitude: "Широта (необязательно)",
    longitude: "Долгота (необязательно)",
    coordinatesHelp: "Публичные координаты входа в площадку: укажите оба значения с точкой, до шести знаков после неё, или оставьте оба пустыми. Карта поддерживает широту от −85.051128 до 85.051128 и долготу от −180 до 180. Личные адреса здесь не указывайте.",
    gamesHelp: "Отметьте только игры, доступные на площадке. Изменения координат, игр или типа площадки требуют повторной проверки.",
    coordinates: "Координаты входа",
    noCoordinates: "Координаты не указаны; площадка доступна в списке.",
    showMap: "Показать карту",
    hideMap: "Скрыть карту",
    mapLead: "Карта загружается с OpenStreetMap после нажатия кнопки. Местоположение вашего устройства не запрашивается.",
    noMapPoints: "Среди найденных площадок пока нет подтверждённых координат для карты.",
    mapPartial: "На карте показаны только площадки с подтверждёнными координатами. Полный результат — в списке ниже.",
    mapLoading: "Загрузка карты…",
    mapError: "Не удалось загрузить карту. Список и ссылки на площадки доступны ниже.",
    tileError: "Подложка карты недоступна. Метки и список площадок остаются доступны.",
    mapSelect: "Показать площадку на карте",
    mapAll: "Все метки",
    mapOpen: "Открыть площадку",
    zoomIn: "Приблизить",
    zoomOut: "Отдалить",
    show: "Показать",
    none: "Подтверждённых площадок пока нет.",
    upcoming: "турниров впереди",
    owners: "Владельцам площадок",
    ownersLead:
      "Площадку добавляет владелец или администратор пространства организатора в разделе «Площадки» своего пространства; публикуется она после подтверждения адреса и статуса. Нет пространства — оставьте заявку.",
    kinds: { club: "Киберспортивный клуб", arena: "Арена", games_house: "MAXIMUS Games House", clubhouse: "Clubhouse", other: "Другое пространство" } as Record<
      string,
      string
    >,
    statuses: { draft: "черновик", submitted: "на проверке", confirmed: "подтверждена", rejected: "отклонена", suspended: "приостановлена" } as Record<
      string,
      string
    >,
    notPublic: "Площадка не опубликована: её видят только администраторы пространства и команда портала.",
    map: "Открыть на карте ↗",
    website: "Сайт",
    events: "Турниры на площадке",
    noEvents: "Ближайших турниров на площадке нет.",
    manage: "Площадки пространства",
    manageLead:
      "Добавьте площадку и отправьте её на проверку: команда портала подтверждает адрес и статус. Подтверждённую площадку можно выбрать для турнира; участники получают QR-пропуск. Смена названия, типа, адреса, координат или игр отправляет площадку на повторную проверку.",
    add: "Добавить площадку",
    name: "Название",
    kind: "Тип",
    address: "Адрес (улица, дом, этаж)",
    country: "Страна",
    description: "Описание (необязательно)",
    site: "Сайт (https://, необязательно)",
    save: "Сохранить",
    edit: "Изменить",
    submit: "Отправить на проверку",
    reviewNote: "Ответ команды портала",
    guest: "Гостевой пропуск",
    guestLead: "Пропуск на одного человека, от 1 минуты до 7 дней; проходит один раз.",
    username: "Имя пользователя",
    from: "С",
    until: "До",
    note: "Заметка (необязательно)",
    issue: "Выдать пропуск",
    activePasses: "Действующие пропуска",
    noPasses: "Действующих пропусков нет.",
    revoke: "Отозвать",
    checkins: "Последние проходы",
    noCheckins: "Проходов пока не было.",
    scanHow:
      "Как пропускать: откройте камеру телефона, наведите на QR участника и откройте ссылку, войдя в портал как участник пространства. Проход отмечается кнопкой; второй раз тот же пропуск не пройдёт.",
    results: {
      admitted: "пропущен",
      used: "уже использован",
      expired: "срок истёк",
      not_yet: "ещё не действует",
      revoked: "отозван",
      withdrawn: "заявка отозвана",
    } as Record<string, string>,
    eventPass: "QR-пропуск на площадку",
    eventPassLead: "Турнир проходит на площадке. Пропуск действует с 3 часов до начала и сутки после, проходит один раз.",
    getPass: "Получить QR-пропуск",
    showPass: "Показать пропуск",
    passes: "Мои пропуска",
    passesLead: "Покажите QR сотруднику площадки. Пропуск проходит один раз и только в своё время; скриншот не даёт второго прохода.",
    manualCode: "Если камера не читает код, сотрудник открывает эту ссылку:",
    noMyPasses: "Пропусков нет. Пропуск появляется у участника турнира на подтверждённой площадке или выдаётся площадкой.",
    validity: "действует",
    usedAt: "использован",
    passStatus: { active: "действует", used: "использован", revoked: "отозван" } as Record<string, string>,
    scanTitle: "Пропуск MAXIMUS VEGAS",
    scanPublic: "Это пропуск на площадку. Покажите его сотруднику площадки — он отметит проход.",
    scanForeign: "Пропуск выдан на другую площадку: отметить его могут только её сотрудники.",
    holder: "Участник",
    venue: "Площадка",
    event: "Турнир",
    admit: "Пропустить",
    unknown: "Такого пропуска нет.",
    stateNow: "Сейчас",
  },
  en: {
    title: "Clubs and venues",
    lead: "Confirmed venues: esports clubs, arenas, MAXIMUS Games House and Clubhouse. Each venue's address and status are checked by the portal team; tournaments at a venue use a QR pass.",
    city: "City",
    anyCity: "All cities",
    search: "Venue name",
    game: "Game",
    games: "Games at the venue",
    anyGame: "All games",
    anyKind: "All types",
    anyCountry: "All countries",
    reset: "Reset filters",
    noResults: "No venues match these filters.",
    limited: "Showing the first 200 venues. Refine the filters to find your venue.",
    latitude: "Latitude (optional)",
    longitude: "Longitude (optional)",
    coordinatesHelp: "Public coordinates of the venue entrance: enter both values with a decimal point and up to six decimal places, or leave both empty. The map supports latitude −85.051128 to 85.051128 and longitude −180 to 180. Do not enter a private home address.",
    gamesHelp: "Select only games available at the venue. Changes to coordinates, games or venue type require another review.",
    coordinates: "Entrance coordinates",
    noCoordinates: "No coordinates supplied; the venue is available in the list.",
    showMap: "Show map",
    hideMap: "Hide map",
    mapLead: "The map loads from OpenStreetMap after you press the button. Your device location is not requested.",
    noMapPoints: "None of the matching venues has confirmed coordinates for the map yet.",
    mapPartial: "Only venues with confirmed coordinates appear on the map. The full result is listed below.",
    mapLoading: "Loading map…",
    mapError: "The map could not load. The venue list and links remain available below.",
    tileError: "Map tiles are unavailable. Venue markers and the list remain available.",
    mapSelect: "Show a venue on the map",
    mapAll: "All markers",
    mapOpen: "Open venue",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    show: "Show",
    none: "No confirmed venues yet.",
    upcoming: "upcoming tournaments",
    owners: "For venue owners",
    ownersLead:
      "An owner or administrator of an organising space adds the venue in the space's “Venues” section; it is published once its address and status are confirmed. No space yet — leave a request.",
    kinds: { club: "Esports club", arena: "Arena", games_house: "MAXIMUS Games House", clubhouse: "Clubhouse", other: "Other space" } as Record<string, string>,
    statuses: { draft: "draft", submitted: "in review", confirmed: "confirmed", rejected: "rejected", suspended: "suspended" } as Record<string, string>,
    notPublic: "The venue is not published: only the space's administrators and the portal team see it.",
    map: "Open on the map ↗",
    website: "Website",
    events: "Tournaments at the venue",
    noEvents: "No upcoming tournaments at the venue.",
    manage: "The space's venues",
    manageLead:
      "Add a venue and send it for review: the portal team confirms its address and status. A confirmed venue can be chosen for a tournament; participants get a QR pass. Changing the name, type, address, coordinates or games sends the venue back for review.",
    add: "Add a venue",
    name: "Name",
    kind: "Type",
    address: "Address (street, building, floor)",
    country: "Country",
    description: "Description (optional)",
    site: "Website (https://, optional)",
    save: "Save",
    edit: "Edit",
    submit: "Send for review",
    reviewNote: "The portal team's answer",
    guest: "Guest pass",
    guestLead: "A pass for one person, from 1 minute to 7 days; it admits once.",
    username: "Username",
    from: "From",
    until: "Until",
    note: "Note (optional)",
    issue: "Issue the pass",
    activePasses: "Active passes",
    noPasses: "No active passes.",
    revoke: "Revoke",
    checkins: "Latest entries",
    noCheckins: "No entries yet.",
    scanHow:
      "How to admit: open the phone camera, point it at the participant's QR and open the link while signed in as a member of the space. Admission is marked with a button; the same pass will not get through twice.",
    results: {
      admitted: "admitted",
      used: "already used",
      expired: "expired",
      not_yet: "not valid yet",
      revoked: "revoked",
      withdrawn: "entry withdrawn",
    } as Record<string, string>,
    eventPass: "QR pass to the venue",
    eventPassLead: "The tournament is held at a venue. The pass is valid from 3 hours before the start until a day after, and admits once.",
    getPass: "Get the QR pass",
    showPass: "Show the pass",
    passes: "My passes",
    passesLead: "Show the QR to the venue's staff. A pass admits once and only in its time window; a screenshot does not get a second entry.",
    manualCode: "If the camera cannot read the code, the staff open this link:",
    noMyPasses: "No passes. A pass appears for a participant of a tournament at a confirmed venue, or is issued by a venue.",
    validity: "valid",
    usedAt: "used",
    passStatus: { active: "valid", used: "used", revoked: "revoked" } as Record<string, string>,
    scanTitle: "MAXIMUS VEGAS pass",
    scanPublic: "This is a venue pass. Show it to the venue's staff — they will mark the entry.",
    scanForeign: "The pass is for another venue: only its staff can mark it.",
    holder: "Participant",
    venue: "Venue",
    event: "Tournament",
    admit: "Admit",
    unknown: "No such pass.",
    stateNow: "Now",
  },
} satisfies Record<Locale, Record<string, unknown>>;

/** A map search link (no tiles or keys involved). */
export const mapLink = (address: string, city: string) => `https://www.openstreetmap.org/search?query=${encodeURIComponent(`${address}, ${city}`)}`;
