// Immutable catalog seed captured for migration 41; future edits go through the catalog service.
const seed = [
  {
    slug: "cs2",
    sort_order: 0,
    data: {
      slug: "cs2",
      name: "Counter-Strike 2",
      teamSize: 5,
      platforms: ["pc"],
      bracket: true,
      genre: { ru: "Тактический шутер", en: "Tactical shooter" },
      apiNote: {
        ru: "Автоматизация серверов, RCON, демо и восстановление матчей проверяется отдельно от интерфейса турнира. До подключения серверного контура результат подтверждается вручную.",
        en: "Server automation, RCON, demos and match recovery are verified separately from the tournament interface. Until the server contour is connected, results are confirmed manually.",
      },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "lol",
    sort_order: 1,
    data: {
      slug: "lol",
      name: "League of Legends",
      teamSize: 5,
      platforms: ["pc"],
      bracket: true,
      genre: { ru: "MOBA", en: "MOBA" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "valorant",
    sort_order: 2,
    data: {
      slug: "valorant",
      name: "VALORANT",
      teamSize: 5,
      platforms: ["pc"],
      bracket: true,
      genre: { ru: "Тактический шутер", en: "Tactical shooter" },
      apiNote: {
        ru: "Данные игрока доступны только при одобренном доступе издателя, входе через Riot Sign On и согласии игрока на показ данных.",
        en: "Player data requires approved publisher access, Riot Sign On and the player's consent to display data.",
      },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "dota2",
    sort_order: 3,
    data: {
      slug: "dota2",
      name: "Dota 2",
      teamSize: 5,
      platforms: ["pc"],
      bracket: true,
      genre: { ru: "MOBA", en: "MOBA" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "apex",
    sort_order: 4,
    data: {
      slug: "apex",
      name: "Apex Legends",
      teamSize: 3,
      platforms: ["pc", "console"],
      bracket: false,
      genre: { ru: "Королевская битва", en: "Battle royale" },
      mode: "battle_royale",
      formats: ["ffa", "leaderboard"],
    },
  },
  {
    slug: "pubg",
    sort_order: 5,
    data: {
      slug: "pubg",
      name: "PUBG: Battlegrounds",
      teamSize: 4,
      platforms: ["pc", "console"],
      bracket: false,
      genre: { ru: "Королевская битва", en: "Battle royale" },
      apiNote: {
        ru: "Официальный PUBG API не создаёт и не управляет custom matches: получение данных отделено от организации лобби. Данные PUBG Mobile через этот API недоступны.",
        en: "The official PUBG API does not create or manage custom matches: data retrieval is separate from lobby organisation. PUBG Mobile data is not available through this API.",
      },
      mode: "battle_royale",
      formats: ["ffa", "leaderboard"],
    },
  },
  {
    slug: "rocket-league",
    sort_order: 6,
    data: {
      slug: "rocket-league",
      name: "Rocket League",
      teamSize: 3,
      platforms: ["pc", "console"],
      bracket: true,
      genre: { ru: "Спортивная аркада", en: "Sports arcade" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "fortnite",
    sort_order: 7,
    data: {
      slug: "fortnite",
      name: "Fortnite",
      teamSize: 1,
      platforms: ["pc", "console", "mobile"],
      bracket: false,
      genre: { ru: "Королевская битва", en: "Battle royale" },
      mode: "battle_royale",
      formats: ["ffa", "leaderboard"],
    },
  },
  {
    slug: "mlbb",
    sort_order: 8,
    data: {
      slug: "mlbb",
      name: "Mobile Legends: Bang Bang",
      teamSize: 5,
      platforms: ["mobile"],
      bracket: true,
      genre: { ru: "Мобильная MOBA", en: "Mobile MOBA" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "smite2",
    sort_order: 9,
    data: {
      slug: "smite2",
      name: "SMITE 2",
      teamSize: 5,
      platforms: ["pc", "console"],
      bracket: true,
      genre: { ru: "MOBA", en: "MOBA" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "deadlock",
    sort_order: 10,
    data: {
      slug: "deadlock",
      name: "Deadlock",
      teamSize: 6,
      platforms: ["pc"],
      bracket: true,
      genre: { ru: "Командный шутер", en: "Team shooter" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "tf2",
    sort_order: 11,
    data: {
      slug: "tf2",
      name: "Team Fortress 2",
      teamSize: 6,
      platforms: ["pc"],
      bracket: true,
      genre: { ru: "Командный шутер", en: "Team shooter" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "trackmania",
    sort_order: 12,
    data: {
      slug: "trackmania",
      name: "Trackmania",
      scoring: "racing",
      teamSize: 1,
      platforms: ["pc", "console"],
      bracket: false,
      genre: { ru: "Гонки", en: "Racing" },
      mode: "racing",
      formats: ["ffa", "leaderboard"],
    },
  },
  {
    slug: "brawl-stars",
    sort_order: 13,
    data: {
      slug: "brawl-stars",
      name: "Brawl Stars",
      teamSize: 3,
      platforms: ["mobile"],
      bracket: true,
      genre: { ru: "Мобильный экшен", en: "Mobile action" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "cs16",
    sort_order: 14,
    data: {
      slug: "cs16",
      name: "Counter-Strike 1.6",
      teamSize: 5,
      platforms: ["pc"],
      bracket: true,
      legacy: true,
      genre: { ru: "Классический шутер", en: "Classic shooter" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
  {
    slug: "css",
    sort_order: 15,
    data: {
      slug: "css",
      name: "Counter-Strike: Source",
      teamSize: 5,
      platforms: ["pc"],
      bracket: true,
      legacy: true,
      genre: { ru: "Классический шутер", en: "Classic shooter" },
      mode: "head_to_head",
      formats: [
        "single_elimination",
        "double_elimination",
        "round_robin",
        "swiss",
        "groups",
        "gauntlet",
        "ffa",
        "leaderboard",
      ],
    },
  },
];
export const adminOperationsSchema = [
  `create table game_catalog(slug text primary key,data jsonb not null,retired boolean not null default false,
    version int not null default 1 check(version>0),sort_order int not null default 1000,
    updated_by uuid references users(id),updated_at timestamptz not null default now())`,
  `insert into game_catalog(slug,data,sort_order) select x.slug,x.data,x.sort_order
    from jsonb_to_recordset('${JSON.stringify(seed).replaceAll("'", "''")}'::jsonb) as x(slug text,data jsonb,sort_order int)`,
  `alter table applications drop constraint applications_status_check`,
  `alter table applications add constraint applications_status_check check(status in ('new','in_review','closed','approved','rejected'))`,
  `alter table applications add column decision text not null default ''`,
  `alter table applications add column decided_by uuid references users(id)`,
  `alter table applications add column decided_at timestamptz`,
  `alter table applications add column version int not null default 1`,
  `alter table sanction_appeals add column assigned_to uuid references users(id)`,
  `alter table sanction_appeals add column assigned_at timestamptz`,
  `alter table sponsors add column version int not null default 1`,
];
