/**
 * Ordered, append-only migrations. Never edit an applied migration; add a new one.
 * Each entry is a list of single statements so both node-postgres and PGlite run them.
 */
export type Migration = { id: number; name: string; statements: string[] };

export const migrations: Migration[] = [
  {
    id: 1,
    name: "core_portal",
    statements: [
      `create table users (
        id uuid primary key default gen_random_uuid(),
        email text not null unique,
        username text not null unique,
        display_name text not null,
        password_hash text not null,
        status text not null default 'active' check (status in ('active','suspended','deleted')),
        country text not null default '',
        bio text not null default '',
        profile_public boolean not null default true,
        adult_confirmed_at timestamptz not null,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      )`,
      `create table user_roles (
        user_id uuid not null references users(id) on delete cascade,
        role text not null check (role in ('admin','referee','support')),
        granted_by uuid references users(id),
        granted_at timestamptz not null default now(),
        primary key (user_id, role)
      )`,
      `create table sessions (
        id text primary key,
        user_id uuid not null references users(id) on delete cascade,
        created_at timestamptz not null default now(),
        last_seen_at timestamptz not null default now(),
        expires_at timestamptz not null,
        revoked_at timestamptz,
        user_agent text not null default ''
      )`,
      `create index sessions_user on sessions(user_id)`,
      `create table auth_attempts (
        id bigserial primary key,
        key text not null,
        ok boolean not null,
        at timestamptz not null default now()
      )`,
      `create index auth_attempts_key on auth_attempts(key, at)`,
      `create table linked_game_accounts (
        user_id uuid not null references users(id) on delete cascade,
        game text not null,
        handle text not null,
        verified boolean not null default false,
        created_at timestamptz not null default now(),
        primary key (user_id, game)
      )`,
      `create table organizations (
        id uuid primary key default gen_random_uuid(),
        slug text not null unique,
        name text not null,
        description text not null default '',
        created_by uuid not null references users(id),
        created_at timestamptz not null default now()
      )`,
      `create table org_members (
        org_id uuid not null references organizations(id) on delete cascade,
        user_id uuid not null references users(id) on delete cascade,
        role text not null check (role in ('owner','admin','referee')),
        added_at timestamptz not null default now(),
        primary key (org_id, user_id)
      )`,
      `create table teams (
        id uuid primary key default gen_random_uuid(),
        slug text not null unique,
        name text not null,
        tag text not null default '',
        game text not null,
        owner_id uuid not null references users(id),
        captain_id uuid not null references users(id),
        created_at timestamptz not null default now()
      )`,
      `create table team_members (
        team_id uuid not null references teams(id) on delete cascade,
        user_id uuid not null references users(id) on delete cascade,
        joined_at timestamptz not null default now(),
        primary key (team_id, user_id)
      )`,
      `create table team_invites (
        id uuid primary key default gen_random_uuid(),
        team_id uuid not null references teams(id) on delete cascade,
        user_id uuid not null references users(id) on delete cascade,
        invited_by uuid not null references users(id),
        status text not null default 'pending' check (status in ('pending','accepted','declined','revoked')),
        created_at timestamptz not null default now(),
        responded_at timestamptz
      )`,
      `create unique index team_invites_pending on team_invites(team_id, user_id) where status = 'pending'`,
      `create table tournaments (
        id uuid primary key default gen_random_uuid(),
        slug text not null unique,
        org_id uuid not null references organizations(id),
        name text not null,
        game text not null,
        format text not null default 'single_elimination' check (format in ('single_elimination')),
        participant_type text not null check (participant_type in ('solo','team')),
        team_size int not null default 1 check (team_size between 1 and 10),
        max_participants int not null check (max_participants between 2 and 512),
        check_in_required boolean not null default true,
        check_in_open boolean not null default false,
        region text not null default '',
        starts_at timestamptz not null,
        description text not null default '',
        rules text not null default '',
        status text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED','REGISTRATION_OPEN','REGISTRATION_CLOSED','IN_PROGRESS','PAUSED','COMPLETED','CANCELLED','ARCHIVED')),
        created_by uuid not null references users(id),
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        started_at timestamptz,
        completed_at timestamptz
      )`,
      `create index tournaments_status on tournaments(status, starts_at)`,
      `create table registrations (
        id uuid primary key default gen_random_uuid(),
        tournament_id uuid not null references tournaments(id) on delete cascade,
        user_id uuid references users(id),
        team_id uuid references teams(id),
        registered_by uuid not null references users(id),
        status text not null default 'registered' check (status in ('registered','waitlisted','withdrawn','disqualified','not_checked_in')),
        checked_in_at timestamptz,
        seed int,
        placement int,
        created_at timestamptz not null default now(),
        check ((user_id is null) <> (team_id is null))
      )`,
      `create unique index registrations_user on registrations(tournament_id, user_id) where user_id is not null and status <> 'withdrawn'`,
      `create unique index registrations_team on registrations(tournament_id, team_id) where team_id is not null and status <> 'withdrawn'`,
      `create table roster_entries (
        registration_id uuid not null references registrations(id) on delete cascade,
        tournament_id uuid not null references tournaments(id) on delete cascade,
        user_id uuid not null references users(id),
        captured_at timestamptz not null default now(),
        primary key (registration_id, user_id),
        unique (tournament_id, user_id)
      )`,
      `create table matches (
        id uuid primary key,
        tournament_id uuid not null references tournaments(id) on delete cascade,
        round int not null,
        position int not null,
        a_reg uuid references registrations(id),
        b_reg uuid references registrations(id),
        winner_reg uuid references registrations(id),
        score_a int,
        score_b int,
        status text not null default 'pending' check (status in ('pending','ready','in_progress','result_submitted','disputed','completed','cancelled')),
        outcome text check (outcome in ('played','bye','walkover','no_show','disqualification')),
        next_match_id uuid references matches(id),
        next_slot text check (next_slot in ('a','b')),
        scheduled_at timestamptz,
        room_code text not null default '',
        completed_at timestamptz,
        updated_at timestamptz not null default now(),
        unique (tournament_id, round, position)
      )`,
      `create table match_results (
        id uuid primary key default gen_random_uuid(),
        match_id uuid not null references matches(id) on delete cascade,
        version int not null,
        source text not null check (source in ('participant','official')),
        side text check (side in ('a','b')),
        submitted_by uuid not null references users(id),
        score_a int,
        score_b int,
        winner_reg uuid not null references registrations(id),
        outcome text not null default 'played',
        evidence_url text not null default '',
        note text not null default '',
        status text not null default 'pending' check (status in ('pending','confirmed','rejected','superseded')),
        decided_by uuid references users(id),
        decided_at timestamptz,
        created_at timestamptz not null default now(),
        unique (match_id, version)
      )`,
      `create table disputes (
        id uuid primary key default gen_random_uuid(),
        match_id uuid not null references matches(id) on delete cascade,
        opened_by uuid not null references users(id),
        reason text not null,
        status text not null default 'open' check (status in ('open','resolved')),
        resolution text not null default '',
        resolved_by uuid references users(id),
        created_at timestamptz not null default now(),
        resolved_at timestamptz
      )`,
      `create table applications (
        id uuid primary key default gen_random_uuid(),
        kind text not null,
        name text not null,
        email text not null,
        company text not null default '',
        message text not null default '',
        lang text not null,
        user_id uuid references users(id),
        status text not null default 'new' check (status in ('new','in_review','closed')),
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      )`,
      `create table notifications (
        id uuid primary key default gen_random_uuid(),
        user_id uuid not null references users(id) on delete cascade,
        kind text not null,
        data jsonb not null default '{}',
        read_at timestamptz,
        created_at timestamptz not null default now()
      )`,
      `create index notifications_user on notifications(user_id, created_at desc)`,
      `create table audit_log (
        id bigserial primary key,
        at timestamptz not null,
        actor_id uuid,
        action text not null,
        entity text not null,
        entity_id text not null,
        data jsonb not null default '{}',
        prev_hash text not null,
        hash text not null
      )`,
    ],
  },
  {
    id: 2,
    name: "formats_disputes_awards",
    statements: [
      // Formats: double elimination and leaderboard. Constraint changes only widen what is allowed.
      `alter table tournaments drop constraint if exists tournaments_format_check`,
      `alter table tournaments add constraint tournaments_format_check check (format in ('single_elimination','double_elimination','leaderboard'))`,
      `alter table tournaments add column scoring jsonb`,
      `alter table tournaments add column best_of int check (best_of between 1 and 50)`,
      `alter table tournaments add column submission_hours int check (submission_hours between 1 and 720)`,
      `alter table tournaments add column submission_deadline timestamptz`,
      `alter table tournaments add column region_lock text[] not null default '{}'`,
      `alter table tournaments add column prize_coins int not null default 0 check (prize_coins between 0 and 100000)`,
      `alter table tournaments add column prize_text text not null default ''`,
      `alter table tournaments add column livestream_url text not null default ''`,
      `alter table matches add column bracket text not null default 'W' check (bracket in ('W','L','GF'))`,
      `alter table matches drop constraint if exists matches_tournament_id_round_position_key`,
      `alter table matches add constraint matches_slot_key unique (tournament_id, bracket, round, position)`,
      `alter table matches add column loser_next_match_id uuid references matches(id)`,
      `alter table matches add column loser_next_slot text check (loser_next_slot in ('a','b'))`,
      `alter table matches add column a_void boolean not null default false`,
      `alter table matches add column b_void boolean not null default false`,
      `alter table matches add column a_checked_in_at timestamptz`,
      `alter table matches add column b_checked_in_at timestamptz`,
      `alter table matches drop constraint if exists matches_outcome_check`,
      `alter table matches add constraint matches_outcome_check check (outcome in ('played','bye','walkover','no_show','disqualification','decision'))`,
      // Post-result disputes: uphold or overturn a decided match.
      `alter table disputes add column kind text not null default 'pre_result' check (kind in ('pre_result','post_result'))`,
      `alter table disputes add column evidence_url text not null default ''`,
      `alter table disputes add column decision text check (decision in ('upheld','overturned'))`,
      `create unique index disputes_open_post on disputes(match_id) where status = 'open' and kind = 'post_result'`,
      `create index disputes_opened_by on disputes(opened_by, kind, decision)`,
      // Co-organisers of a single tournament.
      `create table tournament_organizers (
        tournament_id uuid not null references tournaments(id) on delete cascade,
        user_id uuid not null references users(id) on delete cascade,
        added_by uuid not null references users(id),
        added_at timestamptz not null default now(),
        primary key (tournament_id, user_id)
      )`,
      // Leaderboard score log.
      `create table score_entries (
        id uuid primary key default gen_random_uuid(),
        tournament_id uuid not null references tournaments(id) on delete cascade,
        registration_id uuid not null references registrations(id) on delete cascade,
        submitted_by uuid not null references users(id),
        source text not null check (source in ('participant','organizer')),
        kills int not null check (kills between 0 and 999),
        assists int not null check (assists between 0 and 999),
        deaths int not null check (deaths between 0 and 999),
        headshots int not null check (headshots between 0 and 999),
        damage int not null check (damage between 0 and 99999),
        distance int not null check (distance between 0 and 999999),
        placement int check (placement in (1,2,3)),
        match_ref text not null default '',
        evidence_url text not null default '',
        flags text[] not null default '{}',
        review text not null check (review in ('accepted','pending','approved','rejected')),
        reviewed_by uuid references users(id),
        reviewed_at timestamptz,
        review_note text not null default '',
        created_at timestamptz not null default now()
      )`,
      `create index score_entries_reg on score_entries(tournament_id, registration_id)`,
      `create unique index score_entries_match_ref on score_entries(tournament_id, registration_id, match_ref) where match_ref <> '' and review <> 'rejected'`,
      // Champion awards: idempotent per champion registration, never per tournament.
      `create table tournament_awards (
        tournament_id uuid not null references tournaments(id) on delete cascade,
        registration_id uuid not null references registrations(id),
        kind text not null check (kind in ('champion')),
        coins int not null check (coins >= 0),
        created_at timestamptz not null default now(),
        primary key (tournament_id, registration_id, kind)
      )`,
    ],
  },
  {
    id: 3,
    name: "progression_community_media",
    statements: [
      `alter table users add column country_code text check (country_code ~ '^[A-Z]{2}$')`,
      `alter table users add column avatar_color text not null default ''`,
      `alter table users add column onboarded_at timestamptz`,
      // Existing accounts never see the first-run flow.
      `update users set onboarded_at = created_at`,
      `alter table users add column referral_code text unique`,
      `create table wallets (
        user_id uuid primary key references users(id) on delete cascade,
        balance int not null default 0 check (balance >= 0),
        updated_at timestamptz not null default now()
      )`,
      `create table coin_ledger (
        id bigserial primary key,
        user_id uuid not null references users(id) on delete cascade,
        delta int not null check (delta <> 0),
        reason text not null,
        ref text not null default '',
        idem_key text not null unique,
        balance_after int not null,
        created_at timestamptz not null default now()
      )`,
      `create index coin_ledger_user on coin_ledger(user_id, id desc)`,
      `create table xp_events (
        id bigserial primary key,
        user_id uuid not null references users(id) on delete cascade,
        amount int not null check (amount > 0),
        reason text not null,
        game text not null default '',
        ref text not null default '',
        idem_key text not null unique,
        created_at timestamptz not null default now()
      )`,
      `create index xp_events_user on xp_events(user_id, game)`,
      `create table objective_claims (
        user_id uuid not null references users(id) on delete cascade,
        objective text not null,
        claimed_at timestamptz not null default now(),
        primary key (user_id, objective)
      )`,
      `create table pass_unlocks (
        user_id uuid not null references users(id) on delete cascade,
        season text not null,
        source text not null check (source in ('coins','membership')),
        unlocked_at timestamptz not null default now(),
        primary key (user_id, season)
      )`,
      `create table pass_claims (
        user_id uuid not null references users(id) on delete cascade,
        season text not null,
        tier int not null,
        track text not null check (track in ('free','premium')),
        claimed_at timestamptz not null default now(),
        primary key (user_id, season, tier, track)
      )`,
      `create table user_cosmetics (
        user_id uuid not null references users(id) on delete cascade,
        item text not null,
        source text not null check (source in ('shop','pass','objective','membership')),
        acquired_at timestamptz not null default now(),
        primary key (user_id, item)
      )`,
      `create table referral_redemptions (
        referee_id uuid primary key references users(id) on delete cascade,
        referrer_id uuid not null references users(id) on delete cascade,
        code text not null,
        created_at timestamptz not null default now(),
        referrer_rewarded_at timestamptz,
        check (referee_id <> referrer_id)
      )`,
      `create table challenges (
        id uuid primary key default gen_random_uuid(),
        kind text not null check (kind in ('challenge','quick')),
        game text not null,
        challenger_id uuid not null references users(id),
        opponent_id uuid not null references users(id),
        message text not null default '',
        status text not null default 'pending' check (status in ('pending','accepted','declined','cancelled','expired','reported','completed','disputed')),
        reported_by uuid references users(id),
        reported_winner uuid references users(id),
        score_challenger int check (score_challenger between 0 and 999),
        score_opponent int check (score_opponent between 0 and 999),
        winner_id uuid references users(id),
        evidence_url text not null default '',
        resolution text not null default '',
        resolved_by uuid references users(id),
        expires_at timestamptz not null,
        created_at timestamptz not null default now(),
        responded_at timestamptz,
        completed_at timestamptz,
        check (challenger_id <> opponent_id)
      )`,
      `create index challenges_challenger on challenges(challenger_id, created_at desc)`,
      `create index challenges_opponent on challenges(opponent_id, created_at desc)`,
      `create unique index challenges_open_pair on challenges(least(challenger_id, opponent_id), greatest(challenger_id, opponent_id), game) where status in ('pending','accepted','reported','disputed')`,
      `create table quick_queue (
        user_id uuid primary key references users(id) on delete cascade,
        game text not null,
        joined_at timestamptz not null default now(),
        expires_at timestamptz not null
      )`,
      `create index quick_queue_game on quick_queue(game, joined_at)`,
      `create table media (
        id uuid primary key default gen_random_uuid(),
        owner_id uuid references users(id) on delete set null,
        kind text not null check (kind in ('team_logo','team_banner','tournament_banner','evidence','sponsor_logo')),
        content_type text not null check (content_type in ('image/png','image/jpeg','image/webp')),
        bytes int not null check (bytes > 0 and bytes <= 2097152),
        sha256 text not null,
        data bytea not null,
        created_at timestamptz not null default now()
      )`,
      `create index media_owner on media(owner_id, created_at desc)`,
      `alter table teams add column logo_media_id uuid references media(id) on delete set null`,
      `alter table teams add column banner_media_id uuid references media(id) on delete set null`,
      `alter table tournaments add column banner_media_id uuid references media(id) on delete set null`,
      `alter table disputes add column evidence_media_id uuid references media(id) on delete set null`,
      `create table sponsors (
        id uuid primary key default gen_random_uuid(),
        name text not null,
        tier text not null check (tier in ('title','gold','silver','partner')),
        website_url text not null default '',
        logo_media_id uuid references media(id) on delete set null,
        active boolean not null default true,
        created_by uuid references users(id),
        created_at timestamptz not null default now()
      )`,
      `create table tournament_sponsors (
        tournament_id uuid not null references tournaments(id) on delete cascade,
        sponsor_id uuid not null references sponsors(id) on delete cascade,
        primary key (tournament_id, sponsor_id)
      )`,
    ],
  },
  {
    id: 4,
    name: "accounts_email_consents_mfa",
    statements: [
      `alter table users drop constraint if exists users_status_check`,
      `alter table users add constraint users_status_check check (status in ('active','suspended','deleted','pending'))`,
      `alter table users add column email_verified_at timestamptz`,
      `alter table users add column marketing_opt_in_at timestamptz`,
      `create table email_tokens (
        id text primary key,
        user_id uuid not null references users(id) on delete cascade,
        purpose text not null check (purpose in ('verify_email','reset_password','activate')),
        email text not null,
        expires_at timestamptz not null,
        used_at timestamptz,
        created_at timestamptz not null default now()
      )`,
      `create index email_tokens_user on email_tokens(user_id, purpose, created_at desc)`,
      `create table email_outbox (
        id uuid primary key default gen_random_uuid(),
        to_email text not null,
        template text not null,
        lang text not null,
        data jsonb not null default '{}',
        status text not null default 'pending' check (status in ('pending','sending','sent','failed','cancelled')),
        attempts int not null default 0,
        next_attempt_at timestamptz not null default now(),
        locked_until timestamptz,
        last_error text not null default '',
        provider text not null default '',
        provider_message_id text not null default '',
        dedupe_key text unique,
        user_id uuid references users(id) on delete set null,
        created_at timestamptz not null default now(),
        sent_at timestamptz
      )`,
      `create index email_outbox_due on email_outbox(status, next_attempt_at)`,
      `create table consents (
        id bigserial primary key,
        user_id uuid not null references users(id) on delete cascade,
        kind text not null check (kind in ('terms','privacy','marketing','membership_terms')),
        version text not null,
        granted boolean not null,
        source text not null,
        created_at timestamptz not null default now()
      )`,
      `create index consents_user on consents(user_id, kind, id desc)`,
      // Existing accounts accepted the 27 September 2026 terms and privacy notice at sign-up (required checkbox).
      `insert into consents (user_id, kind, version, granted, source, created_at)
         select id, 'terms', '2026-09-27', true, 'signup_checkbox', created_at from users where status <> 'deleted'`,
      `insert into consents (user_id, kind, version, granted, source, created_at)
         select id, 'privacy', '2026-09-27', true, 'signup_checkbox', created_at from users where status <> 'deleted'`,
      `alter table sessions add column mfa_at timestamptz`,
      `create table mfa_factors (
        user_id uuid primary key references users(id) on delete cascade,
        secret text not null,
        scheme text not null check (scheme in ('aes-256-gcm','plain')),
        confirmed_at timestamptz,
        last_step bigint not null default 0,
        created_at timestamptz not null default now()
      )`,
      `create table mfa_recovery_codes (
        user_id uuid not null references users(id) on delete cascade,
        code_hash text not null,
        used_at timestamptz,
        primary key (user_id, code_hash)
      )`,
    ],
  },
  {
    id: 5,
    name: "billing_offers_memberships",
    statements: [
      `create table offers (
        id uuid primary key default gen_random_uuid(),
        code text not null,
        version int not null,
        kind text not null check (kind in ('membership','pass_premium')),
        status text not null default 'proposed' check (status in ('proposed','active','retired')),
        title jsonb not null,
        benefits jsonb not null,
        exclusions jsonb not null,
        audience text not null default 'adult_account_holders',
        legal_recipient text not null,
        price_minor bigint check (price_minor > 0),
        currency text check (currency ~ '^[A-Z]{3}$'),
        exponent int check (exponent between 0 and 3),
        tax_treatment text,
        duration_days int check (duration_days between 1 and 1100),
        admission text not null default 'review' check (admission in ('review','self_service')),
        terms_text jsonb,
        refund_text jsonb,
        approval_ref text,
        approved_by uuid references users(id),
        approved_at timestamptz,
        created_by uuid references users(id),
        created_at timestamptz not null default now(),
        unique (code, version)
      )`,
      `create unique index offers_one_active on offers(code) where status = 'active'`,
      `create sequence membership_ref_seq`,
      `create table membership_applications (
        id uuid primary key default gen_random_uuid(),
        reference text not null unique,
        user_id uuid not null references users(id),
        offer_id uuid not null references offers(id),
        status text not null default 'submitted' check (status in ('submitted','under_review','awaiting_info','approved','declined','withdrawn')),
        objective text not null default '',
        lang text not null default 'ru' check (lang in ('ru','en')),
        decision_note text not null default '',
        decided_by uuid references users(id),
        decided_at timestamptz,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      )`,
      `create unique index membership_applications_open on membership_applications(user_id, offer_id) where status in ('submitted','under_review','awaiting_info')`,
      `create sequence invoice_number_seq`,
      `create table invoices (
        id uuid primary key default gen_random_uuid(),
        number text not null unique,
        user_id uuid not null references users(id),
        application_id uuid references membership_applications(id),
        offer_id uuid not null references offers(id),
        offer_snapshot jsonb not null,
        recipient text not null,
        amount_minor bigint not null check (amount_minor > 0),
        currency text not null check (currency ~ '^[A-Z]{3}$'),
        exponent int not null check (exponent between 0 and 3),
        tax_treatment text not null,
        terms_version text not null,
        lang text not null default 'ru' check (lang in ('ru','en')),
        status text not null default 'open' check (status in ('open','paid','void','refunded','partially_refunded','disputed')),
        refunded_minor bigint not null default 0 check (refunded_minor >= 0),
        issued_by uuid references users(id),
        created_at timestamptz not null default now(),
        paid_at timestamptz,
        voided_at timestamptz
      )`,
      `create unique index invoices_open_application on invoices(application_id) where status = 'open'`,
      `create index invoices_user on invoices(user_id, created_at desc)`,
      `create table payment_attempts (
        id uuid primary key default gen_random_uuid(),
        invoice_id uuid not null references invoices(id),
        user_id uuid not null references users(id),
        provider text not null,
        mode text not null check (mode in ('test','live')),
        provider_session_id text unique,
        provider_payment_id text,
        status text not null default 'created' check (status in ('created','open','processing','succeeded','failed','expired','canceled')),
        amount_minor bigint not null,
        currency text not null,
        idem_key text not null unique,
        terms_version text not null,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        expires_at timestamptz
      )`,
      `create unique index payment_attempts_active on payment_attempts(invoice_id) where status in ('created','open','processing')`,
      `create table provider_events (
        id text primary key,
        provider text not null,
        type text not null,
        livemode boolean not null,
        status text not null check (status in ('received','processed','ignored','failed')),
        error text not null default '',
        invoice_id uuid references invoices(id),
        payload_sha256 text not null,
        provider_created_at timestamptz,
        received_at timestamptz not null default now(),
        processed_at timestamptz
      )`,
      `create table ledger_entries (
        id bigserial primary key,
        invoice_id uuid not null references invoices(id),
        payment_attempt_id uuid references payment_attempts(id),
        kind text not null check (kind in ('charge','refund','dispute','dispute_reversal')),
        amount_minor bigint not null,
        currency text not null,
        provider_ref text not null,
        created_at timestamptz not null default now(),
        unique (kind, provider_ref)
      )`,
      `create table memberships (
        id uuid primary key default gen_random_uuid(),
        user_id uuid not null references users(id),
        offer_id uuid not null references offers(id),
        application_id uuid references membership_applications(id),
        invoice_id uuid unique references invoices(id),
        status text not null default 'pending' check (status in ('pending','active','suspended','expired','ended')),
        starts_at timestamptz,
        ends_at timestamptz,
        status_reason text not null default '',
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      )`,
      `create index memberships_user on memberships(user_id, status)`,
      // A proposed (not payable) membership structure. Commercial terms are NOT PROVIDED: stored as null.
      `insert into offers (code, version, kind, status, title, benefits, exclusions, legal_recipient)
       values ('vegas-membership', 1, 'membership', 'proposed',
         '{"ru":"Членство MAXIMUS VEGAS","en":"MAXIMUS VEGAS membership"}',
         '{"ru":["Премиальная линия сезонного пропуска","Знак участника и эксклюзивный цвет аватара в профиле"],"en":["Premium track of the season pass","Member badge and an exclusive avatar colour on your profile"]}',
         '{"ru":["Никакого преимущества в соревновании: посев, результаты, рейтинги и доступ к турнирам одинаковы для всех","Монеты, деньги и призы не начисляются"],"en":["No competitive advantage: seeding, results, rankings and tournament access are the same for everyone","No coins, cash or prizes are credited"]}',
         'MAXIMUS VEGAS L.L.C-FZ')`,
    ],
  },
];
