import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { GAMES } from "@/lib/games.ts";
import { rentalStatus } from "@/lib/rental-text.ts";
import { viewer } from "@/server/viewer.ts";
import { rentalNodeDetail } from "@/server/rentals.ts";
import { DomainError } from "@/server/errors.ts";
import { ActionForm,DbDown,Field,Flash,PageHead,type SearchParams } from "@/components/ui";
import { LocalTime } from "@/components/time";
import { RentalNodeKey } from "@/components/rental-node-key";
import { RentalStatusRefresh } from "@/components/rental-status";
export const metadata={title:"MAXIMUS · Server node"};
export default async function NodePage({params,searchParams}:{params:Promise<{lang:string;id:string}>;searchParams:SearchParams}){
  const {lang,id}=await params;if(!isLocale(lang)||!/^[a-f0-9-]{36}$/i.test(id))notFound();const T=(ru:string,en:string)=>lang==="ru"?ru:en,back=`/${lang}/server-rentals/nodes/${id}`;
  const {db,user}=await viewer();if(!db)return <DbDown lang={lang}/>;if(!user)redirect(`/${lang}/signin?next=${back}`);
  const {node,templates,leases}=await rentalNodeDetail(db,user,id).catch(e=>{if(e instanceof DomainError&&e.code==="not_found")notFound();throw e;});
  const online=node.ready&&node.heartbeat_at&&new Date(node.heartbeat_at).getTime()>Date.now()-45000;
  return <div className="container page"><Link className="text-link" href={`/${lang}/server-rentals`}>← {T("Игровые серверы","Game servers")}</Link><PageHead title={node.name} lead={`${node.region} · ${node.address}`}/><Flash lang={lang} params={await searchParams}/>
    <section className="card"><h2>{T("Состояние узла","Node status")}</h2><p>{rentalStatus(node.status,lang)} · {online?T("На связи","Connected"):T("Не готов к новым сеансам","Not ready for new sessions")}</p><p>{node.review_note}</p><p>{node.cpu_millis/1000} CPU · {node.memory_mb} MB RAM · {node.storage_mb} MB · {T("порты","ports")} {node.port_start}–{node.port_end}</p><p>{T("Последний ответ","Last response")}: <LocalTime iso={node.heartbeat_at} lang={lang}/></p><RentalStatusRefresh active={false} lang={lang}/><ActionForm action="rental.enabled" lang={lang} back={back} hidden={{node:id,enabled:String(!node.enabled)}}><p>{T("Пауза запрещает новые бронирования, сохраняя текущие сеансы.","Pausing prevents new reservations and preserves current sessions.")}</p><button className="btn btn-primary" disabled={!node.enabled&&node.status!=="approved"}>{node.enabled?T("Приостановить новые бронирования","Pause new reservations"):T("Разрешить новые бронирования","Enable new reservations")}</button></ActionForm></section>
    <RentalNodeKey id={id} lang={lang}/><p className="small muted">{T("Идентификатор узла","Node ID")}: <code>{id}</code>. <a className="text-link" href="https://github.com/MAXIMUS-NPiO/maximus-vegas/tree/main/server-agent" target="_blank" rel="noopener noreferrer">{T("Установка и проверка агента","Agent installation and verification")}</a></p>
    <h2>{T("Игровые шаблоны","Game templates")}</h2>{!templates.length&&<p>{T("Добавьте конфигурацию из локального файла агента.","Add a configuration from the local agent file.")}</p>}<div className="grid grid-2">{templates.map(t=><article className="card" key={t.id}><h3>{t.name}</h3><p>{rentalStatus(t.status,lang)} · {t.game}</p><p>{t.cpu_millis/1000} CPU · {t.memory_mb} MB RAM · {t.disk_mb} MB</p><p>{t.review_note}</p><p className="small" style={{overflowWrap:"anywhere"}}>{T("Идентификатор и отпечаток","Key and fingerprint")}: {t.local_key} · {t.fingerprint}</p><a className="text-link" href={t.evidence_url} rel="noopener noreferrer" target="_blank">{T("Подтверждающие материалы","Supporting evidence")}</a></article>)}</div>
    <details className="card section-tight"><summary>{T("Добавить шаблон для проверки","Submit a template for review")}</summary><p>{T("Скопируйте параметры из команды --describe агента. Образ и команда запуска задаются только в локальном файле оператора. Изменённой конфигурации нужен новый идентификатор и повторная проверка.","Copy the agent's --describe output. The image and startup command exist only in the operator's local file. A changed configuration needs a new key and another review.")}</p><ActionForm action="rental.template" lang={lang} back={back} hidden={{node:id}} className="grid grid-2">
      <Field label={T("Название шаблона","Template name")}><input name="name" maxLength={100} required/></Field><Field label={T("Игра","Game")}><select name="game">{GAMES.map(g=><option value={g.slug} key={g.slug}>{g.name}</option>)}</select></Field><Field label={T("Локальный идентификатор","Local key")}><input name="localKey" pattern="[a-z0-9](?:[a-z0-9_]|-){1,39}" maxLength={40} required/></Field><Field label={T("Отпечаток SHA-256","SHA-256 fingerprint")}><input name="fingerprint" pattern="[a-f0-9]{64}" maxLength={64} required/></Field><Field label={T("CPU, тысячные доли ядра","CPU, millicores")}><input name="cpuMillis" type="number" min="250" max="128000" required/></Field><Field label="RAM, MB"><input name="memoryMb" type="number" min="256" max="524288" required/></Field><Field label={T("Игровые данные, MB","Game data, MB")}><input name="diskMb" type="number" min="256" max="4194304" required/></Field><Field label={T("Ссылка на сведения об образе и правах","Image and rights evidence URL")}><input name="evidence" type="url" placeholder="https://" maxLength={1000} required/></Field><Field label={T("Игровые порты из --describe (JSON)","Game ports from --describe (JSON)")}><textarea name="ports" maxLength={2000} required placeholder={'[{"name":"game","container":27015,"protocol":"udp"}]'}/></Field><button className="btn btn-primary">{T("Отправить шаблон на проверку","Submit template for review")}</button>
    </ActionForm></details>
    <h2>{T("Сеансы узла","Node sessions")}</h2><ul className="list">{leases.map(l=><li key={l.id}><Link href={`/${lang}/server-rentals/sessions/${l.id}`}>{l.name}</Link><span>{l.released_at?T("Завершён","Released"):rentalStatus(l.observed,lang)} · <LocalTime iso={l.expires_at} lang={lang}/></span></li>)}</ul>
  </div>;
}
