import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { pageMeta } from "@/lib/meta.ts";
import { viewer } from "@/server/viewer.ts";
import { canStaff } from "@/server/access.ts";
import { errorCode } from "@/server/http.ts";
import { CASE_KINDS, myCases, staffCases, readCase, isParty } from "@/server/arbitration.ts";
import { ActionForm, DbDown, Field, Flash, PageHead, SignInPrompt, type SearchParams } from "@/components/ui";
import { LocalTime } from "@/components/time";
const labels:Record<string,[string,string]>={open:["Открыт","Open"],reviewing:["На рассмотрении","Under review"],decided:["Решение принято","Decision issued"],appealed:["Апелляция","Appeal"],closed:["Апелляция рассмотрена","Appeal decided"],marketplace:["Скины и сделки","Skins and transactions"],team:["Команда","Team"],tournament:["Турнир","Tournament"],account:["Аккаунт","Account"],other:["Другое","Other"],claim_supported:["Требование поддержано","Claim supported"],claim_rejected:["Требование отклонено","Claim rejected"],agreement:["Соглашение сторон","Party agreement"]};
export async function generateMetadata({params}:{params:Promise<{lang:string}>}){const {lang}=await params;return isLocale(lang)?pageMeta(lang,"arbitration",lang==="ru"?"Арбитраж":"Arbitration",undefined,{noindex:true}):{};}
export default async function Arbitration({params,searchParams}:{params:Promise<{lang:string}>;searchParams:SearchParams}){
 const {lang}=await params;if(!isLocale(lang))notFound();
 const t=(ru:string,en:string)=>lang==="ru"?ru:en,L=(v:string)=>labels[v]?.[lang==="ru"?0:1]??v,sp=await searchParams,base=`/${lang}/arbitration`;
 const {db,user,dbError}=await viewer();if(dbError||!db)return <div className="container page"><DbDown lang={lang}/></div>;
 if(!user)return <div className="container page"><PageHead title={t("Арбитраж","Arbitration")}/><SignInPrompt lang={lang} back={base}/></div>;
 const id=typeof sp.case==="string"&&/^[0-9a-f-]{36}$/i.test(sp.case)?sp.case:null,queue=sp.queue==="staff",back=id?`${base}?case=${id}`:queue?`${base}?queue=staff`:base;
 let detail:Awaited<ReturnType<typeof readCase>>|null=null,cases:Awaited<ReturnType<typeof myCases>>=[];
 try{if(id)detail=await readCase(db,user,id);else cases=queue?await staffCases(db,user):await myCases(db,user.id);}
 catch(e){const code=errorCode(e);if(code==="mfa_not_enrolled")redirect(`/${lang}/admin/security`);if(code==="mfa_required")redirect(`/${lang}/admin/mfa?next=${encodeURIComponent(back)}`);if(code==="forbidden"||code==="not_found")notFound();throw e;}
 const c=detail?.c,party=c?isParty(c,user.id):false,staff=canStaff(user,"disputes");
 const evidenceFields=<><Field label={t("Обстоятельства и требование / ответ","Facts and requested resolution / response")}><textarea name="body" required minLength={20} maxLength={4000} rows={5}/></Field><Field label={t("Ссылка на доказательство","Evidence link")}><input name="evidence" type="url" maxLength={500}/></Field></>;
 return <div className="container narrow page"><PageHead title={t("Арбитраж","Arbitration")} lead={t("Споры, доказательства и апелляции","Disputes, evidence and appeals")}>
 <Link className="btn btn-ghost btn-sm" href={base}>{t("Мои дела","My cases")}</Link><Link className="btn btn-ghost btn-sm" href={`/${lang}/marketplace`}>Skins Marketplace</Link>
 {staff?<Link className="btn btn-ghost btn-sm" href={`${base}?queue=staff`}>{t("Очередь рассмотрения","Review queue")}</Link>:null}</PageHead><Flash lang={lang} params={sp}/>
 <p className="notice">{t("Это внутреннее рассмотрение споров платформой. Решение здесь само по себе не переводит деньги и не возвращает скины.","This is the platform's internal dispute process. A decision here does not itself transfer funds or return skins.")}</p>
 {c&&detail?<>
 <section className="card stack"><h2 className="h3">{c.title}</h2><p>{L(c.category)} · {L(c.status)}</p>{c.outcome?<strong>{L(c.outcome)}</strong>:null}
 <p className="small">{t("Срок для ответа второй стороны:","Other party's response due:")} <LocalTime iso={c.response_due} lang={lang}/></p><p className="small muted">{t("Доказательства видны обеим сторонам и уполномоченным сотрудникам. Не размещайте пароли и платёжные реквизиты.","Evidence is visible to both parties and authorised staff. Do not include passwords or payment credentials.")}</p></section>
 <section className="section-tight stack"><h2 className="h3">{t("История дела","Case history")}</h2>{detail.entries.map(e=><article className="card stack-sm" key={e.id}><p className="small muted">@{e.username} · <LocalTime iso={e.created_at} lang={lang}/></p><p className="prewrap">{e.kind==="assigned"?t("Назначен сотрудник для рассмотрения","Reviewer assigned"):e.body}</p>{e.evidence_url?<a href={e.evidence_url} rel="noopener noreferrer nofollow" target="_blank">{t("Открыть доказательство","Open evidence")}</a>:null}</article>)}</section>
 {party&&["open","reviewing","appealed"].includes(c.status)?<ActionForm action="arbitration.evidence" lang={lang} back={back} hidden={{id:c.id}} className="card form-card">{evidenceFields}<button className="btn btn-primary">{t("Добавить в дело","Add to case")}</button></ActionForm>:null}
 {party&&c.status==="decided"?<ActionForm action="arbitration.appeal" lang={lang} back={back} hidden={{id:c.id}} className="card form-card"><h2 className="h3">{t("Апелляция другому сотруднику","Appeal to another reviewer")}</h2>{evidenceFields}<button className="btn btn-primary">{t("Подать апелляцию","Submit appeal")}</button></ActionForm>:null}
 {staff&&!party&&c.first_reviewer!==user.id&&!c.assigned_to&&["open","appealed"].includes(c.status)?<ActionForm action="arbitration.claim" lang={lang} back={back} hidden={{id:c.id}}><button className="btn btn-primary">{t("Принять к рассмотрению","Take case")}</button></ActionForm>:null}
 {staff&&!party&&c.assigned_to===user.id&&["reviewing","appealed"].includes(c.status)?<ActionForm action="arbitration.decide" lang={lang} back={back} hidden={{id:c.id}} className="card form-card"><h2 className="h3">{t("Обоснованное решение","Reasoned decision")}</h2><p className="small">{t("Решение возможно после ответа второй стороны либо окончания срока ответа. Проверьте отсутствие конфликта интересов.","A decision requires the other party's response or expiry of the response period. Check for conflicts of interest.")}</p><Field label={t("Исход","Outcome")}><select name="outcome">{["claim_supported","claim_rejected","agreement"].map(o=><option key={o} value={o}>{L(o)}</option>)}</select></Field><Field label={t("Обоснование","Reasons")}><textarea name="body" required minLength={20} maxLength={4000} rows={5}/></Field><button className="btn btn-primary">{t("Зафиксировать решение","Record decision")}</button></ActionForm>:null}
 </>:<><section className="section-tight stack"><h2 className="h3">{queue?t("Очередь рассмотрения","Review queue"):t("Мои дела","My cases")}</h2>{!cases.length?<p>{t("Дел пока нет.","No cases yet.")}</p>:cases.map(row=><Link className="card" key={row.id} href={`${base}?case=${row.id}`}><strong>{row.title}</strong><p>{L(row.category)} · {L(row.status)}</p></Link>)}</section>
 {!queue?<section className="section-tight"><h2 className="h3">{t("Открыть спор","Open a dispute")}</h2><p className="small">{t("Укажите зарегистрированного участника. Он получит уведомление внутри платформы и доступ к делу. Для ответа отводится 72 часа.","Name a registered participant. They receive an in-platform notification and access to the case. The response period is 72 hours.")}</p>
 <p><Link href={`/${lang}/conduct`}>{t("Нарушения правил и санкции","Conduct and sanctions")}</Link> · <Link href={`/${lang}/gameday`}>{t("Спор о результате матча","Match result dispute")}</Link></p>
 <ActionForm action="arbitration.open" lang={lang} back={base} className="card form-card"><Field label={t("Категория","Category")}><select name="category">{CASE_KINDS.map(k=><option key={k} value={k}>{L(k)}</option>)}</select></Field><Field label={t("Имя пользователя второй стороны","Other party's username")}><input name="username" required minLength={3} maxLength={24}/></Field><Field label={t("Предмет спора","Subject")}><input name="title" required minLength={5} maxLength={150}/></Field>{evidenceFields}<button className="btn btn-primary">{t("Открыть дело","Open case")}</button></ActionForm></section>:null}</>}
 </div>;
}
