import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { GAMES } from "@/lib/games.ts";
import { rentalStatus } from "@/lib/rental-text.ts";
import { viewer } from "@/server/viewer.ts";
import { rentalOverview } from "@/server/rentals.ts";
import { ActionForm,Check,DbDown,Field,Flash,PageHead,one,type SearchParams } from "@/components/ui";
import { LocalTime } from "@/components/time";
export const metadata={title:"MAXIMUS · Dedicated game servers"};
export default async function ServerRentals({params,searchParams}:{params:Promise<{lang:string}>;searchParams:SearchParams}){
  const {lang}=await params;if(!isLocale(lang))notFound();const T=(ru:string,en:string)=>lang==="ru"?ru:en,back=`/${lang}/server-rentals`,sp=await searchParams;
  const {db,user}=await viewer();if(!db)return <DbDown lang={lang}/>;const data=await rentalOverview(db,user?.id),game=one(sp.game),region=one(sp.region);
  const offers=data.offers.filter(t=>(!game||t.game===game)&&(!region||t.region.toLowerCase().includes(region.toLowerCase())));
  return <div className="container page"><PageHead title={T("Выделенные игровые серверы","Dedicated game servers")} lead={T("Выберите подтверждённый узел и игровой шаблон. Управляйте сеансом, журналом и локальными резервными копиями.","Choose a reviewed node and game template. Manage the session, logs and local backups.")}/><Flash lang={lang} params={sp}/>
    <p className="notice">{T("Платная аренда пока не подключена. Доступные сеансы предоставляются бесплатно на 30–240 минут. Остановка сохраняет резервирование; завершение или истечение срока удаляет игровые данные и локальные копии после подтверждения узлом.","Paid rentals are not connected. Available sessions are free for 30–240 minutes. Stopping keeps the reservation; releasing or expiry removes game data and local backups after node confirmation.")}</p>
    <form method="get" className="grid grid-3"><Field label={T("Игра","Game")}><select name="game" defaultValue={game}><option value="">{T("Все игры","All games")}</option>{GAMES.map(g=><option key={g.slug} value={g.slug}>{g.name}</option>)}</select></Field><Field label={T("Регион","Region")}><input name="region" maxLength={60} defaultValue={region}/></Field><button className="btn btn-ghost">{T("Применить фильтры","Apply filters")}</button></form>
    <h2>{T("Доступные конфигурации","Available configurations")}</h2>{!offers.length&&<p className="notice">{T("Сейчас нет свободных конфигураций от подтверждённых узлов. Оператор может зарегистрировать свой узел ниже.","No free configurations from reviewed nodes are available right now. Operators can register a node below.")}</p>}
    <div className="grid grid-2">{offers.map(t=><article className="card" key={t.id}><h3>{t.name}</h3><p>{GAMES.find(g=>g.slug===t.game)?.name} · {t.region} · {t.node_name}</p><p>{t.cpu_millis/1000} CPU · {t.memory_mb} MB RAM · {t.disk_mb} MB {T("игровых данных","game data")}</p><a className="text-link" href={t.evidence_url} rel="noopener noreferrer" target="_blank">{T("Подтверждение конфигурации и прав","Configuration and rights evidence")}</a>{user?<ActionForm action="rental.allocate" lang={lang} back={back} hidden={{template:t.id}}><Field label={T("Длительность, минуты","Duration, minutes")}><input type="number" name="minutes" min="30" max="240" defaultValue="60" required/></Field><Field label={T("Начать через, минуты (0 — сейчас; до 24 часов)","Start in minutes (0 = now; up to 24 hours)")}><input type="number" name="delayMinutes" min="0" max="1440" defaultValue="0" required/></Field><p className="muted">{T("Ресурсы резервируются сразу, включая время ожидания запуска.","Resources are reserved immediately, including the wait before the scheduled start.")}</p><Check name="consent" required label={T("Согласен с временем сеанса, удалением данных при завершении и обработкой игровых данных оператором выбранного узла.","I accept the session duration, data deletion on release and processing of game data by the selected node operator.")}/><button className="btn btn-primary">{T("Зарезервировать сервер","Reserve server")}</button></ActionForm>:<Link className="btn btn-primary" href={`/${lang}/signin?next=${back}`}>{T("Войти для резервирования","Sign in to reserve")}</Link>}</article>)}</div>
    {user&&<><h2>{T("Мои сеансы","My sessions")}</h2>{!data.leases.length&&<p>{T("Сеансов пока нет.","No sessions yet.")}</p>}<ul className="list">{data.leases.map(l=><li key={l.id}><Link href={`${back}/sessions/${l.id}`}>{l.name}</Link><span>{l.released_at?T("Завершён","Released"):rentalStatus(l.observed,lang)} · <LocalTime iso={l.expires_at} lang={lang}/></span></li>)}</ul><h2>{T("Мои узлы","My nodes")}</h2><ul className="list">{data.nodes.map(n=><li key={n.id}><Link href={`${back}/nodes/${n.id}`}>{n.name}</Link><span>{rentalStatus(n.status,lang)}</span></li>)}</ul>
      <details className="card section-tight"><summary>{T("Зарегистрировать узел","Register a node")}</summary><p>{T("Параметры должны соответствовать отдельному Linux-узлу с настроенным агентом. Проверка команды портала обязательна до публикации.","The capacity must match a dedicated Linux node with a configured agent. Portal review is required before publication.")}</p><ActionForm action="rental.node" lang={lang} back={back} className="grid grid-2">
        <Field label={T("Название","Name")}><input name="name" maxLength={80} required/></Field><Field label={T("Регион","Region")}><input name="region" maxLength={60} required/></Field><Field label={T("Адрес игровых подключений","Game connection address")}><input name="address" placeholder="games.example.org" maxLength={253} required/></Field><Field label={T("CPU, тысячные доли ядра","CPU, millicores")}><input type="number" name="cpuMillis" min="1000" max="256000" defaultValue="4000" required/></Field><Field label="RAM, MB"><input type="number" name="memoryMb" min="512" max="1048576" defaultValue="8192" required/></Field><Field label={T("Место под данные и копии, MB","Data and backup capacity, MB")}><input type="number" name="storageMb" min="1024" max="16777216" defaultValue="32768" required/></Field><Field label={T("Первый игровой порт","First game port")}><input name="portStart" type="number" min="1024" max="65000" defaultValue="27015" required/></Field><Field label={T("Последний игровой порт","Last game port")}><input name="portEnd" type="number" min="1024" max="65535" defaultValue="27030" required/></Field><Check name="consent" required label={T("Уполномочен предоставлять ресурсы и запускать выбранные игры; подтверждаю настройки изоляции и доступность игровых портов.","I am authorised to provide these resources and run the selected games, and confirm isolation settings and reachable game ports.")}/><button className="btn btn-primary">{T("Отправить узел на проверку","Submit node for review")}</button>
      </ActionForm></details></>}
    {!user&&<Link className="btn btn-primary" href={`/${lang}/signin?next=${back}`}>{T("Войти как игрок или оператор","Sign in as a player or operator")}</Link>}
  </div>;
}
