import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { viewer } from "@/server/viewer.ts";
import { communityPeople } from "@/server/community.ts";
import { clanOf } from "@/server/clans.ts";
import { myTeamDesk } from "@/server/my-teams.ts";
import { myMatches } from "@/server/social.ts";
import { MemberAvatar } from "@/components/member-avatar";
import { ActionForm, DbDown, Field, Flash, PageHead, one, type SearchParams } from "@/components/ui";
export const metadata = { title: "MAXIMUS · Community", robots: { index: false, follow: false } };
export default async function Community({ params, searchParams }: { params: Promise<{ lang: string }>; searchParams: SearchParams }) {
  const { lang } = await params; if (!isLocale(lang)) notFound();
  const T = (a: string, b: string) => lang === "ru" ? a : b, back = `/${lang}/community`, sp = await searchParams;
  const { db, user } = await viewer(); if (!db) return <DbDown lang={lang} />; if (!user) redirect(`/${lang}/signin?next=${back}`);
  const [people, teamDesk, clan, conversations] = await Promise.all([communityPeople(db, user), myTeamDesk(db, user), clanOf(db, user.id), myMatches(db, user.id)]);
  return <div className="container page"><PageHead title={T("Среди своих", "Among your people")} lead={T("Приходите играть. Находите товарищей. Общайтесь в своём ритме — здесь есть место вашей команде, вашим интересам и вам.", "Come to play. Find your people. Connect at your own pace — there is room for your team, your interests and you.")}><Link className="btn btn-primary" href={`${back}/chat`}>{T("Общий чат", "Global chat")}</Link><Link className="btn btn-ghost" href={`/${lang}/my-teams#invite-player`}>{T("Пригласить игрока", "Invite a player")}</Link></PageHead><Flash lang={lang} params={sp} />
    <nav className="row wrap" aria-label={T("Разделы сообщества", "Community sections")}><a className="btn btn-ghost btn-sm" href="#friends">{T("Друзья", "Friends")}</a><a className="btn btn-ghost btn-sm" href="#conversations">{T("Личные сообщения", "Direct messages")}</a><a className="btn btn-ghost btn-sm" href="#rooms">{T("Мои чаты", "My chats")}</a><Link className="btn btn-ghost btn-sm" href={`${back}/support`}>{T("Поддержка и ПСИХОЛОГИНЯ", "Support & PSYCHOLOGYNYA")}</Link><Link className="btn btn-ghost btn-sm" href={`/${lang}/settings#avatar`}>{T("Мой аватар", "My avatar")}</Link></nav>
    <div className="grid grid-3 section-tight" id="rooms"><Link className="card card-link" href={`${back}/chat`}><h2 className="h3">{T("Общая гостиная", "Community lounge")}</h2><p>{T("Представиться, обсудить игру, позвать компанию на вечер.", "Introduce yourself, talk about a game, find company for the evening.")}</p></Link><Link className="card card-link" href={`/${lang}/finder`}><h2 className="h3">{T("Найти свою команду", "Find your team")}</h2><p>{T("Игроки и составы по игре, роли и языку общения.", "Players and rosters by game, role and language.")}</p></Link><Link className="card card-link" href={clan ? `/${lang}/clans/${clan.slug}` : `/${lang}/clans`}><h2 className="h3">{clan ? `[${clan.tag}] ${clan.name}` : T("Кланы и союзы", "Clans & alliances")}</h2><p>{T("Общий флаг, союзники и спортивное соперничество по согласию обеих сторон.", "A shared banner, allies and sporting rivalry agreed by both sides.")}</p></Link></div>
    {(teamDesk.teams.length > 0 || clan) && <section className="section-tight"><h2>{T("Чаты моих команд и клана", "My team & clan chats")}</h2><div className="row wrap">{teamDesk.teams.map(t => <Link key={t.id} className="btn btn-ghost" href={`${back}/chat?scope=team&id=${t.id}`}>{t.name}</Link>)}{clan && <Link className="btn btn-ghost" href={`${back}/chat?scope=clan&id=${clan.id}`}>[{clan.tag}] {clan.name}</Link>}</div><p className="small muted">{T("Эти комнаты доступны только текущим участникам состава.", "These rooms are available only to current roster members.")}</p></section>}
    <section className="section-tight" id="friends"><h2>{T("Мои друзья", "My friends")}</h2><ActionForm action="community.friend" lang={lang} back={`${back}#friends`} className="card stack-sm"><Field label={T("Добавить друга по @username", "Add a friend by @username")}><input name="username" defaultValue={one(sp.username).slice(0, 25)} required pattern="@?[A-Za-z0-9_]{3,24}" maxLength={25} autoCapitalize="none" autoCorrect="off" placeholder="@player_name" /></Field><button className="btn btn-primary">{T("Отправить заявку в друзья", "Send friend request")}</button><p className="small muted">{T("После подтверждения откроются личная переписка и доступные звонки. Для дружбы не нужно создавать анкету знакомств.", "After acceptance, direct messages and available calls open. A dating profile is not required for friendship.")}</p></ActionForm>
      {!!people.requests.length && <div className="card section-tight"><h3>{T("Заявки в друзья", "Friend requests")}</h3><ul className="list">{people.requests.map(r => <li className="row wrap" key={r.id}><span className="grow">{r.display_name} · @{r.username}<small className="muted"> · {r.incoming ? T("хочет добавить вас", "would like to add you") : T("ждём ответа", "awaiting response")}</small></span>{r.incoming ? <><ActionForm action="community.friend_respond" lang={lang} back={`${back}#friends`} hidden={{ id: r.id, accept: "1" }}><button className="btn btn-primary btn-sm">{T("Принять в друзья", "Accept friend")}</button></ActionForm><ActionForm action="community.friend_respond" lang={lang} back={`${back}#friends`} hidden={{ id: r.id, accept: "0" }}><button className="btn btn-ghost btn-sm">{T("Отклонить", "Decline")}</button></ActionForm></> : <ActionForm action="community.friend_cancel" lang={lang} back={`${back}#friends`} hidden={{ id: r.id }}><button className="btn btn-ghost btn-sm">{T("Отменить заявку", "Cancel request")}</button></ActionForm>}</li>)}</ul></div>}
      <div className="grid grid-3 section-tight">{people.friends.map(f => <Link className="card card-link" key={f.id} href={`/${lang}/dating/${f.id}`}><div className="row"><MemberAvatar name={f.display_name} mediaId={f.avatar_media_id} size="lg" /><h3>{f.display_name}</h3></div><p>@{f.username}</p><strong>{f.unread ? `${T("Новых сообщений", "New messages")}: ${f.unread}` : T("Написать / позвонить", "Message / call")}</strong></Link>)}</div>{!people.friends.length && <p className="muted">{T("Ваши друзья появятся здесь после принятия заявки. Можно начать с общего чата или знакомого игрока.", "Friends appear here after a request is accepted. Start with the global chat or a player you know.")}</p>}
    </section>
    <section className="section-tight" id="conversations"><h2>{T("Личные сообщения", "Direct messages")}</h2>{conversations.length ? <ul className="list">{conversations.map(m => <li key={m.id}><Link href={`/${lang}/dating/${m.id}`}>{m.display_name}</Link><span>{m.status === "closed" ? T("Общение закрыто", "Conversation closed") : m.unread ? `${T("Новых", "New")}: ${m.unread}` : T("Открыть переписку", "Open conversation")}</span></li>)}</ul> : <p className="muted">{T("Переписки появятся после взаимного подтверждения.", "Conversations appear after mutual acceptance.")}</p>}</section>
    <div className="grid grid-2 section-tight"><Link className="card card-link" href={`${back}/support`}><h2 className="h3">{T("Есть с кем поговорить", "Someone to talk to")}</h2><p>{T("Ведущие сообщества помогают освоиться. ПСИХОЛОГИНЯ — отдельное направление профессиональной поддержки с проверкой специалистов.", "Community hosts help you feel at home. PSYCHOLOGYNYA is a separate professional-support direction with practitioner checks.")}</p></Link><Link className="card card-link" href={`/${lang}/dating`}><h2 className="h3">{T("Знакомиться ближе · 18+", "Connect more personally · 18+")}</h2><p>{T("Отдельная добровольная анкета: общие интересы, дружба или отношения. Вы сами выбираете цель и собеседника.", "A separate opt-in profile: shared interests, friendship or relationships. You choose your intent and connections.")}</p></Link></div>
    <p className="notice">{T("Соперничаем в игре, уважаем человека. Можно отказаться от общения, заблокировать участника или передать конкретное сообщение модератору. Возвращайтесь тогда, когда вам удобно.", "Compete in the game, respect the person. You can decline contact, block a member or report a specific message. Return whenever it suits you.")}</p>
    {!!people.blocks.length && <details className="section-tight"><summary>{T("Заблокированные участники", "Blocked members")}</summary>{people.blocks.map(p => <ActionForm key={p.subject_id} action="social.unblock" lang={lang} back={back} hidden={{ user: p.subject_id }} className="row"><span>{p.display_name}</span><button className="btn btn-ghost btn-sm">{T("Разблокировать", "Unblock")}</button></ActionForm>)}</details>}
  </div>;
}
