import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { GAMES } from "@/lib/games.ts";
import { viewer } from "@/server/viewer.ts";
import { venueView } from "@/server/venues.ts";
import { canManageOrg } from "@/server/access.ts";
import { requireStaffMfa } from "@/server/mfa.ts";
import { clubView } from "@/server/clubhouse.ts";
import { ActionForm, Check, DbDown, Field, Flash, PageHead, type SearchParams } from "@/components/ui";
import { LocalTime } from "@/components/time";
import { OfflineScanner } from "@/components/offline-scanner";
export const metadata = { title: "MAXIMUS · Clubhouse workspace", robots: { index: false, follow: false } };
export default async function Clubhouse({ params, searchParams }: { params: Promise<{ lang: string; slug: string }>; searchParams: SearchParams }) {
  const { lang, slug } = await params; if (!isLocale(lang)) notFound();
  const T = (ru: string, en: string) => lang === "ru" ? ru : en, back = `/${lang}/clubhouse/${slug}`;
  const { db, user } = await viewer(); if (!db) return <DbDown lang={lang} />; if (!user) redirect(`/${lang}/signin?next=${back}`);
  const venue = (await venueView(db, slug, user))?.venue; if (!venue || !(await canManageOrg(db, venue.org_id, user))) notFound();
  try { await requireStaffMfa(db, user); } catch { redirect(`/${lang}/admin/mfa?next=${back}`); }
  const data = await clubView(db, venue.id, user.id), hidden = { venue: venue.id };
  const bookings = await db.query<{ id: string; display_name: string; name: string; starts_at: Date; ends_at: Date; status: string }>("select b.id,u.display_name,s.name,b.starts_at,b.ends_at,b.status from station_bookings b join club_stations s on s.id=b.station_id join users u on u.id=b.user_id where s.venue_id=$1 and b.ends_at>now()-interval '7 days' order by b.starts_at limit 200", [venue.id]);
  const attendees = await db.query<{ id: string; display_name: string; title: string; status: string }>("select r.id,u.display_name,e.title,r.status from club_rsvps r join club_events e on e.id=r.event_id join users u on u.id=r.user_id where e.venue_id=$1 and e.ends_at>now()-interval '7 days' order by e.starts_at,r.created_at limit 500", [venue.id]);
  const gifts = await db.query<{ id: string; title: string; quantity: number; active: boolean }>("select id,title,quantity,active from pass_rewards where venue_id=$1 order by created_at desc limit 100", [venue.id]);
  const hourText = (m: number) => `${String(Math.floor(m / 60) % 24).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`;
  return <div className="container page"><Link href={`/${lang}/venues/${slug}`} className="text-link">← {T("Страница площадки", "Venue page")}</Link><PageHead title={venue.name} eyebrow="CLUBHOUSE" lead={T("Расписание, станции, события и вход участников", "Opening hours, stations, events and member check-in")} /><Flash lang={lang} params={await searchParams} />
    {venue.status !== "confirmed" && <p className="notice">{T("Публикация и новые бронирования доступны после подтверждения площадки.", "Publishing and new reservations require a verified venue.")}</p>}
    <section className="grid grid-2"><article className="card"><h2>{T("Часы работы", "Opening hours")}</h2><ActionForm action="club.hours" lang={lang} back={back} hidden={hidden}><Field label={T("Часовой пояс IANA (например, Asia/Dubai)", "IANA time zone (for example Asia/Dubai)")}><input name="timeZone" required maxLength={64} defaultValue={data.hours?.time_zone ?? "UTC"} /></Field><Field label={T("Открытие", "Opens")}><input type="time" name="opensAt" required defaultValue={hourText(data.hours?.opens ?? 600)} /></Field><Field label={T("Закрытие (00:00 — полночь)", "Closes (00:00 means midnight)")}><input type="time" name="closesAt" required defaultValue={hourText(data.hours?.closes ?? 1320)} /></Field><fieldset><legend>{T("Рабочие дни", "Open days")}</legend>{(lang === "ru" ? ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"] : ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]).map((d, i) => <Check key={i} name="weekdays" value={String(i)} defaultChecked={data.hours?.weekdays.includes(i) ?? true} label={d} />)}</fieldset><p className="small muted">{T("Изменение часов применяется к новым броням. Существующие брони отменяйте отдельно.", "Hours apply to new reservations. Cancel existing reservations separately if necessary.")}</p><button className="btn btn-primary">{T("Сохранить часы", "Save hours")}</button></ActionForm></article>
    <article className="card"><h2>{T("Станции", "Stations")}</h2><ActionForm action="club.station" lang={lang} back={back} hidden={hidden}><Field label={T("Название станции", "Station name")}><input name="name" minLength={2} maxLength={60} required /></Field><Field label={T("Оборудование", "Equipment")}><textarea name="equipment" maxLength={500} /></Field><button className="btn btn-primary">{T("Добавить станцию", "Add station")}</button></ActionForm>{data.stations.map(s => <div key={s.id} className="row section-tight"><span>{s.name} · {s.active ? T("Открыта", "Open") : T("Закрыта", "Closed")}</span><ActionForm action="club.station_status" lang={lang} back={back} hidden={{ station: s.id, active: s.active ? "false" : "true" }}><button className="btn btn-ghost btn-sm">{s.active ? T("Закрыть и отменить будущие брони", "Close and cancel upcoming reservations") : T("Открыть", "Open")}</button></ActionForm></div>)}</article></section>
    <section className="card section-tight"><h2>{T("Создать событие", "Create event")}</h2><ActionForm action="club.event" lang={lang} back={back} hidden={{ ...hidden, timeZone: data.hours?.time_zone ?? "UTC" }}><div className="grid grid-2"><Field label={T("Название", "Title")}><input name="title" required minLength={2} maxLength={100} /></Field><Field label={T("Формат", "Type")}><select name="kind"><option value="social">{T("Встреча", "Meetup")}</option><option value="training">{T("Обучение", "Training")}</option><option value="talent">{T("Просмотр талантов", "Talent session")}</option><option value="competition">{T("Соревнование", "Competition")}</option></select></Field><Field label={T("Игра", "Game")}><select name="game"><option value="">{T("Без привязки", "Any")}</option>{GAMES.map(g => <option key={g.slug} value={g.slug}>{g.name}</option>)}</select></Field><Field label={T("Количество мест", "Capacity")}><input name="capacity" type="number" min="1" max="5000" required /></Field><Field label={`${T("Начало", "Start")} · ${data.hours?.time_zone ?? "UTC"}`}><input name="startsAt" type="datetime-local" required /></Field><Field label={T("Окончание", "End")}><input name="endsAt" type="datetime-local" required /></Field></div><Field label={T("Программа и условия участия", "Programme and participation terms")}><textarea name="description" minLength={10} maxLength={2000} required /></Field><Check name="freeEntry" required label={T("Подтверждаю бесплатное участие и право проводить это событие на площадке.", "I confirm free entry and authorisation to hold this event at the venue.")} /><button className="btn btn-primary">{T("Опубликовать событие", "Publish event")}</button></ActionForm>
    {data.events.map(e => <div key={e.id} className="card section-tight"><strong>{e.title}</strong><p><LocalTime iso={e.starts_at} lang={lang} /> · {e.reserved}/{e.capacity}</p>{e.status === "published" && <div className="row">{["cancelled", "completed"].map(status => <ActionForm key={status} action="club.event_status" lang={lang} back={back} hidden={{ event: e.id, status }}><button className="btn btn-ghost" disabled={status === "completed" && new Date(e.ends_at).getTime() > Date.now()}>{status === "cancelled" ? T("Отменить событие", "Cancel event") : T("Завершить событие", "Complete event")}</button></ActionForm>)}</div>}</div>)}</section>
    <section className="section-tight"><h2>{T("Брони и участники", "Reservations and attendees")}</h2>{bookings.map(b => <article key={b.id} className="card"><h3>{b.name} · {b.display_name}</h3><p><LocalTime iso={b.starts_at} lang={lang} /> — <LocalTime iso={b.ends_at} lang={lang} /> · {b.status}</p>{["reserved", "checked_in"].includes(b.status) && <div className="row">{["cancelled", ...(b.status === "checked_in" ? ["completed"] : ["no_show"])].map(status => <ActionForm key={status} action="club.booking_status" lang={lang} back={back} hidden={{ booking: b.id, status }}><button className="btn btn-ghost btn-sm">{({ cancelled: T("Отменить", "Cancel"), completed: T("Завершить", "Complete"), no_show: T("Отметить неявку", "Mark no-show") })[status]}</button></ActionForm>)}</div>}</article>)}<ul>{attendees.map(a => <li key={a.id}>{a.title} · {a.display_name} · {a.status}</li>)}</ul></section>
    <OfflineScanner venueId={venue.id} userId={user.id} lang={lang} />
    <section className="card section-tight"><h2>{T("Подарки сезонного Pass", "Season Pass gifts")}</h2><p>{T("Размещайте только реальные остатки и подтверждённые условия выдачи. Монеты участников не списываются.", "List only actual stock with confirmed collection terms. Member coins are never debited.")}</p><ActionForm action="reward.create" lang={lang} back={back} hidden={hidden}><Field label={T("Название подарка", "Gift title")}><input name="title" maxLength={100} minLength={2} required /></Field><Field label={T("Описание, срок и условия получения", "Description, collection deadline and terms")}><textarea name="description" minLength={10} maxLength={1000} required /></Field><div className="grid grid-2"><Field label={T("Уровень Pass", "Pass tier")}><input name="tier" type="number" min="1" max="20" required /></Field><Field label={T("Подтверждённый остаток", "Confirmed stock")}><input name="quantity" type="number" min="1" max="10000" required /></Field></div><button className="btn btn-primary">{T("Разместить подарок", "List gift")}</button></ActionForm><ul>{gifts.map(g => <li key={g.id}>{g.title} · {g.quantity}</li>)}</ul><h3>{T("Подтвердить выдачу", "Confirm collection")}</h3><ActionForm action="reward.collect" lang={lang} back={back}><Field label={T("Номер резерва участника", "Member reservation reference")}><input name="claim" required /></Field><Field label={T("Код, показанный участником", "Code shown by member")}><input name="code" required autoComplete="off" /></Field><button className="btn btn-primary">{T("Подарок передан участнику", "Gift handed to member")}</button></ActionForm></section>
  </div>;
}
