import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { rentalStatus } from "@/lib/rental-text.ts";
import { viewer } from "@/server/viewer.ts";
import { rentalLeaseDetail } from "@/server/rentals.ts";
import { DomainError } from "@/server/errors.ts";
import { ActionForm,DbDown,Field,Flash,PageHead,type SearchParams } from "@/components/ui";
import { LocalTime } from "@/components/time";
import { RentalStatusRefresh } from "@/components/rental-status";
export const metadata={title:"MAXIMUS · Game server session"};
export default async function SessionPage({params,searchParams}:{params:Promise<{lang:string;id:string}>;searchParams:SearchParams}){
  const {lang,id}=await params;if(!isLocale(lang)||!/^[a-f0-9-]{36}$/i.test(id))notFound();const T=(ru:string,en:string)=>lang==="ru"?ru:en,back=`/${lang}/server-rentals/sessions/${id}`;
  const {db,user}=await viewer();if(!db)return <DbDown lang={lang}/>;if(!user)redirect(`/${lang}/signin?next=${back}`);
  const {lease:l,jobs,backups,access,role}=await rentalLeaseDetail(db,user,id).catch(e=>{if(e instanceof DomainError&&e.code==="not_found")notFound();throw e;});
  const restartReady=!l.last_command_at||new Date(l.last_command_at).getTime()+30000<=Date.now();
  const active=!l.released_at&&l.desired!=="released"&&new Date(l.expires_at).getTime()>Date.now(),busy=jobs.some(j=>["pending","running"].includes(j.status)),manage=role!=="viewer",copy=active&&!busy&&["owner","operator"].includes(role!)&&l.desired==="stopped"&&l.observed==="stopped";
  return <div className="container page"><Link className="text-link" href={`/${lang}/server-rentals`}>← {T("Игровые серверы","Game servers")}</Link><PageHead title={l.name} lead={l.region}/><Flash lang={lang} params={await searchParams}/>
    {!l.released_at&&new Date(l.expires_at).getTime()<=Date.now()&&<p className="notice">{T("Время резервирования истекло. Ожидается подтверждение очистки от узла.","The reservation has expired. Waiting for the node to confirm cleanup.")}</p>}
    <section className="card"><h2>{T("Состояние сеанса","Session status")}</h2><p>{T("Подтверждено узлом","Observed on node")}: <strong>{l.released_at?T("Завершён; данные удалены","Released; data deleted"):rentalStatus(l.observed,lang)}</strong></p><p>{T("Запрошено","Requested")}: {rentalStatus(l.desired,lang)}</p><p>{T("Плановый запуск","Scheduled start")}: <LocalTime iso={l.starts_at} lang={lang}/> · {T("Завершение","Expiry")}: <LocalTime iso={l.expires_at} lang={lang}/></p><p>{T("Последний ответ узла","Last node response")}: <LocalTime iso={l.observed_at} lang={lang}/></p>{(!l.observed_at||new Date(l.observed_at).getTime()<Date.now()-45000)&&!l.released_at&&<p className="notice">{T("Свежего подтверждения от узла нет. Показанное состояние может быть устаревшим; ресурсы удерживаются до подтверждения очистки.","There is no recent node confirmation. The displayed state may be stale; resources stay reserved until cleanup is confirmed.")}</p>}<p>{l.note}</p><p>{l.cpu_millis/1000} CPU · {l.memory_mb} MB RAM · {l.disk_mb} MB</p><RentalStatusRefresh active={!l.released_at} lang={lang}/>
      {active&&manage&&<div className="row">{(["start","stop","restart"] as const).map(command=><ActionForm key={command} action={`rental.${command}`} lang={lang} back={back} hidden={{lease:id}}><button className="btn btn-ghost" disabled={busy||(command==="restart"&&!restartReady)||(command==="start"&&l.desired==="running")||(command==="stop"&&l.desired==="stopped")}>{({start:T("Запустить","Start"),stop:T("Остановить","Stop"),restart:T("Перезапустить","Restart")})[command]}</button></ActionForm>)}</div>}
      {active&&manage&&!restartReady&&<p className="small muted">{T("Перезапуск доступен через 30 секунд после предыдущей команды.","Restart becomes available 30 seconds after the previous command.")}</p>}
      {!l.released_at&&l.desired!=="released"&&["owner","node"].includes(role!)&&<ActionForm action="rental.release" lang={lang} back={back} hidden={{lease:id}}><p>{T("Завершение удаляет игровые данные и все локальные копии. Остановка сохраняет их только до конца резервирования.","Releasing deletes game data and all local backups. Stopping keeps them only until the reservation ends.")}</p><button className="btn btn-ghost">{T("Завершить и удалить данные","Release and delete data")}</button></ActionForm>}
    </section>
    {active&&l.observed==="running"&&<section className="card section-tight"><h2>{T("Игровое подключение","Game connection")}</h2><ul className="list">{l.ports.map(p=><li key={p.name}><span>{p.name} · {p.protocol.toUpperCase()}</span><code>{l.address}:{p.host}</code></li>)}</ul><p className="muted">{T("Используйте указанный адрес в игровом клиенте. Подключение зависит от доступности портов и совместимости игры.","Use the address in your game client. Connectivity depends on reachable ports and game compatibility.")}</p></section>}
    <section className="card section-tight"><h2>{T("Локальные резервные копии","Local backups")}</h2><p>{T("До трёх копий в пределах текущего сеанса. Копирование и восстановление доступны после подтверждённой остановки. Копии хранятся на этом же узле и удаляются при завершении или истечении срока.","Up to three backups within this session. Backup and restore require a confirmed stop. Backups live on the same node and are deleted on release or expiry.")}</p>{["owner","operator"].includes(role!)&&<ActionForm action="rental.backup" lang={lang} back={back} hidden={{lease:id}}><button className="btn btn-primary" disabled={!copy||backups.length>=3}>{T("Создать резервную копию","Create backup")}</button></ActionForm>}<ul className="list">{backups.map(b=><li key={b.id}><span><LocalTime iso={b.created_at} lang={lang}/> · {Math.ceil(Number(b.bytes)/1024)} KB</span>{["owner","operator"].includes(role!)&&<ActionForm action="rental.restore" lang={lang} back={back} hidden={{lease:id,backup:b.id}}><button className="btn btn-ghost" disabled={!copy}>{T("Восстановить эту копию","Restore this backup")}</button></ActionForm>}</li>)}</ul><p className="small muted">{T("Восстановление заменяет текущие игровые данные выбранной копией.","Restoring replaces current game data with the selected backup.")}</p>{jobs.map(j=><p key={j.id}>{j.kind==="backup"?T("Копирование","Backup"):T("Восстановление","Restore")} · {rentalStatus(j.status,lang)} · {j.note}</p>)}</section>
    <section className="card section-tight"><h2>{T("Журнал узла","Node log")}</h2><p className="muted">{T("Журнал виден владельцу сеанса, оператору узла и участникам с выданным доступом. Не публикуйте в нём пароли и персональные данные.","Logs are visible to the session owner, node operator and granted participants. Keep passwords and personal information out of logs.")}</p><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",maxHeight:360,overflowY:"auto"}}>{l.logs||T("Журнал пока пуст.","No logs yet.")}</pre></section>
    <section className="card section-tight"><h2>{T("Доступ команды","Team access")}</h2><p>{T("Просмотр открывает состояние, адрес и журнал. Управление также разрешает запуск, остановку, перезапуск и восстановление данных. Завершение сеанса и выдача доступа остаются у владельца.","View access includes status, connection address and logs. Operators can also start, stop, restart and restore data. The session owner keeps release and access management rights.")}</p><ul className="list">{access.map(a=><li key={a.user_id}><span>@{a.username} · {a.role==="viewer"?T("Просмотр","View"):T("Управление","Operate")}</span>{role==="owner"&&active&&<ActionForm action="rental.access" lang={lang} back={back} hidden={{lease:id,username:a.username,role:"remove"}}><button className="btn btn-ghost">{T("Отозвать доступ","Revoke access")}</button></ActionForm>}</li>)}</ul>{role==="owner"&&active&&<ActionForm action="rental.access" lang={lang} back={back} hidden={{lease:id}}><Field label={T("Имя пользователя участника","Participant username")}><input name="username" maxLength={24} required/></Field><Field label={T("Права","Permission")}><select name="role"><option value="viewer">{T("Просмотр","View")}</option><option value="operator">{T("Управление","Operate")}</option></select></Field><button className="btn btn-primary">{T("Предоставить доступ","Grant access")}</button></ActionForm>}</section>
  </div>;
}
