import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { GAMES } from "@/lib/games.ts";
import { viewer } from "@/server/viewer.ts";
import { statsOverview } from "@/server/statistics.ts";
import { anchorConfiguration } from "@/server/stats-anchor.ts";
import { ActionForm, Check, DbDown, Field, Flash, PageHead, type SearchParams } from "@/components/ui";
import { LocalTime } from "@/components/time";
import { StatsVerifier } from "@/components/stats-verifier";
export const metadata = { title: "MAXIMUS · Verifiable statistics", robots: { index: false, follow: false } };
export default async function Statistics({ params, searchParams }: { params: Promise<{ lang: string }>; searchParams: SearchParams }) {
  const { lang } = await params; if (!isLocale(lang)) notFound(); const T = (ru: string, en: string) => lang === "ru" ? ru : en, back = `/${lang}/statistics`;
  const { db, user } = await viewer(); if (!db) return <DbDown lang={lang} />; if (!user) redirect(`/${lang}/signin?next=${back}`);
  const data = await statsOverview(db, user.id), anchoring = anchorConfiguration();
  const status = (s: string) => ({ pending: T("Ожидает проверки", "Pending review"), verified: T("Привязка подтверждена источником", "Link verified by source"), confirmed: T("Подтверждено организатором", "Reviewed by organiser"), rejected: T("Отклонено", "Rejected"), revoked: T("Доступ отозван", "Revoked") })[s] ?? s;
  return <div className="container page"><PageHead title={T("Проверяемая статистика", "Verifiable statistics")} lead={T("Подписанные данные партнёров, история активности и снимки записей с независимой проверкой целостности.", "Signed partner data, activity history and record snapshots with independent integrity checks.")}><Link className="btn btn-ghost" href={`${back}/sources`}>{T("Кабинет источника данных", "Data-source workspace")}</Link></PageHead><Flash lang={lang} params={await searchParams} />
    <section className="section-tight"><h2>{T("Подключить источник", "Connect a source")}</h2>{!data.sources.length && <p className="notice">{T("Подтверждённых источников пока нет. Заявки партнёров проверяются до начала приёма данных.", "There are no approved sources yet. Partner applications are reviewed before data intake starts.")}</p>}<div className="grid grid-2">{data.sources.map(s => <article className="card" key={s.id}><h3>{s.name}</h3><a className="text-link" href={s.evidence_url} target="_blank" rel="noopener noreferrer">{T("Сведения об источнике", "Source information")} ↗</a><ActionForm action="stats.link" lang={lang} back={back} hidden={{ source: s.id }}><Field label={T("Игра", "Game")}><select name="game">{s.games.map(g => <option key={g} value={g}>{GAMES.find(x => x.slug === g)?.name ?? g}</option>)}</select></Field><Field label={T("Ваш игровой ник у этого источника", "Your game handle at this source")}><input name="handle" maxLength={100} required /></Field><Check name="consent" required label={T("Разрешаю получать статистику этого ника. Источник должен подтвердить, что он принадлежит мне, и вернуть код привязки.", "I consent to receiving this handle's statistics. The source must verify that I own it and return the linking challenge.")} /><button className="btn btn-primary">{T("Получить код привязки", "Get linking code")}</button></ActionForm></article>)}</div>
    {data.links.map(l => <article className="card section-tight" key={l.id}><h3>{l.name} · {l.game} · {l.handle}</h3><p>{status(l.status)}</p>{l.challenge && <><p>{T("Передайте этот одноразовый код источнику после входа в свой игровой аккаунт. Код действует сутки.", "Give this one-time challenge to the source after signing in to your game account. It is valid for one day.")}</p><code className="break-all">{l.challenge}</code></>}{l.status !== "revoked" && <ActionForm action="stats.unlink" lang={lang} back={back} hidden={{ link: l.id }}><button className="btn btn-ghost">{T("Отозвать доступ", "Revoke access")}</button></ActionForm>}</article>)}</section>
    <section className="section-tight"><h2>{T("Полученные записи", "Received records")}</h2>{!data.observations.length && <p>{T("Подписанные записи появятся после подключения источника.", "Signed records appear after a source is connected.")}</p>}{data.observations.map(o => <article className="card" key={o.id}><h3>{o.name} · {o.game}</h3><p>{o.match_ref} · <LocalTime iso={o.played_at} lang={lang} /></p><dl className="facts">{Object.entries(o.metrics).map(([key, value]) => <div key={key}><dt>{({ kills: T("Убийства", "Kills"), assists: T("Ассисты", "Assists"), deaths: T("Смерти", "Deaths"), headshots: T("Попадания в голову", "Headshots"), damage: T("Урон", "Damage"), placement: T("Место", "Placement"), score: T("Очки", "Score"), durationSeconds: T("Длительность, с", "Duration, s") })[key] ?? key}</dt><dd>{value}</dd></div>)}</dl><p>{status(o.status)}</p>{o.review_note && <p>{o.review_note}</p>}</article>)}</section>
    <section className="card section-tight"><h2>{T("Создать снимок записей", "Create a record snapshot")}</h2><p>{T("Снимок включает подтверждённую статистику источников, начисления XP, внутренние монеты и записи ваших оплаченных счетов за выбранный период. Идентификаторы плательщика и платёжные реквизиты не публикуются. Монеты не являются деньгами.", "The snapshot includes reviewed source statistics, XP, internal coins and your paid-invoice records for the selected period. Payer identity and payment details are not published. Coins are not money.")}</p><ActionForm action="stats.snapshot" lang={lang} back={back} className="grid grid-3"><Field label={T("С даты (UTC, необязательно)", "From date (UTC, optional)")}><input name="from" type="date" /></Field><Field label={T("По дату включительно (UTC)", "Through date (UTC, inclusive)")}><input name="until" type="date" /></Field><button className="btn btn-primary">{T("Сохранить снимок", "Save snapshot")}</button></ActionForm><p className="small muted">{T("Не более 5 снимков в сутки. Если объём слишком велик, выберите меньший период; записи не обрезаются.", "Up to 5 snapshots daily. If the data is too large, choose a shorter period; records are never silently truncated.")}</p></section>
    {data.snapshots.map(s => <article className="card section-tight" key={s.id}><h3><LocalTime iso={s.created_at} lang={lang} /> · {s.leaf_count} {T("записей", "records")}</h3><p className="mono break-all">{s.root}</p><p>{s.signature ? T("Снимок подписан ключом портала", "Snapshot signed by the portal key") : T("Контрольная сумма готова; ключ подписи портала пока не подключён", "Integrity commitment ready; portal signing key is not connected yet")}</p><div className="row"><a className="btn btn-primary" href={`/api/statistics/proofs/${s.id}`}>{T("Скачать записи и доказательство", "Download records and proof")}</a><ActionForm action="stats.share" lang={lang} back={back} hidden={{ snapshot: s.id, shared: s.shared ? "false" : "true" }}><button className="btn btn-ghost">{s.shared ? T("Закрыть публичную ссылку", "Disable public link") : T("Открыть публичную контрольную сумму", "Share public commitment")}</button></ActionForm></div>{s.shared && <><p className="small">{T("Другие пользователи увидят только контрольную сумму, количество записей и подпись. Сами записи доступны только вам.", "Other users see only the commitment, record count and signature. The records remain accessible only to you.")}</p><Link className="text-link" href={`${back}/proof/${s.id}`}>{T("Открыть публичную проверку", "Open public proof")}</Link>{anchoring && <details><summary>{T("Проверить уже выполненную запись в блокчейн", "Verify an existing blockchain transaction")}</summary><p>{T("Портал проверяет квитанцию и код контракта. Отправки транзакции или списания средств здесь нет.", "The portal checks the receipt and contract code. It does not send a transaction or spend funds.")}</p><ActionForm action="stats.anchor" lang={lang} back={back} hidden={{ snapshot: s.id }}><Field label={T("Хеш транзакции", "Transaction hash")}><input name="transaction" pattern="0x[a-fA-F0-9]{64}" required /></Field><button className="btn btn-ghost">{T("Проверить включение", "Verify inclusion")}</button></ActionForm></details>}</>}</article>)}
    {!anchoring && <p className="notice">{T("Блокчейн-якорь не подключён: сеть и развёрнутый контракт ещё не настроены. Контрольная сумма сама по себе не означает запись в блокчейне.", "Blockchain anchoring is not connected: a network and deployed contract have not been configured. An integrity commitment alone is not a blockchain record.")}</p>}
    <StatsVerifier lang={lang} />
  </div>;
}
