import Link from "next/link";
import type { Locale } from "@/lib/i18n.ts";
import type { Database } from "@/server/db.ts";
import { clubView } from "@/server/clubhouse.ts";
import { ActionForm, Field } from "./ui";
import { LocalTime } from "./time";
export async function ClubhousePublic({ db, venueId, slug, userId, manager, lang }: { db: Database; venueId: string; slug: string; userId?: string; manager: boolean; lang: Locale }) {
  const data = await clubView(db, venueId, userId), T = (ru: string, en: string) => lang === "ru" ? ru : en, back = `/${lang}/venues/${slug}`;
  const status = (s: string) => ({ reserved: T("Место подтверждено", "Reserved"), waitlisted: T("В листе ожидания", "Waitlisted"), attended: T("Посещение отмечено", "Attended"), checked_in: T("Вы на площадке", "Checked in"), cancelled: T("Отменено", "Cancelled"), completed: T("Завершено", "Completed"), no_show: T("Неявка", "No-show") })[s] ?? s;
  return <section className="section-tight" id="clubhouse"><div className="row-between"><h2>Clubhouse</h2>{manager && <Link className="btn btn-ghost" href={`/${lang}/clubhouse/${slug}`}>{T("Управление площадкой", "Venue workspace")}</Link>}</div>
    <h3>{T("Встречи, тренировки и просмотры талантов", "Meetups, training and talent sessions")}</h3>
    {!data.events.length && <p>{T("Площадка ещё не добавила события.", "The venue has not added events yet.")}</p>}
    <div className="grid grid-2">{data.events.map(e => <article key={e.id} className="card"><h3>{e.title}</h3><p className="prewrap">{e.description}</p><p><LocalTime iso={e.starts_at} lang={lang} /> — <LocalTime iso={e.ends_at} lang={lang} /></p><p>{T("Бесплатное участие", "Free entry")} · {e.reserved}/{e.capacity} {T("мест занято", "places taken")}</p>{e.status === "published" && new Date(e.starts_at).getTime() > Date.now() ? userId ? e.mine && e.mine !== "cancelled" ? <><p>{status(e.mine)}</p><ActionForm action="club.rsvp_cancel" lang={lang} back={back} hidden={{ event: e.id }}><button className="btn btn-ghost">{T("Отменить участие", "Cancel RSVP")}</button></ActionForm></> : <ActionForm action="club.rsvp" lang={lang} back={back} hidden={{ event: e.id }}><button className="btn btn-primary">{e.reserved < e.capacity ? T("Участвовать", "Attend") : T("Встать в лист ожидания", "Join waiting list")}</button></ActionForm> : <Link href={`/${lang}/signin?next=${back}`} className="btn btn-primary">{T("Войти и записаться", "Sign in to RSVP")}</Link> : <p>{e.status === "cancelled" ? status("cancelled") : e.mine ? status(e.mine) : T("Запись завершена", "Registration ended")}</p>}</article>)}</div>
    <h3 className="section-tight">{T("Бронирование станций", "Station reservations")}</h3>
    {data.hours && <p>{T("Время бронирования указывайте в часовом поясе площадки:", "Enter reservation times in the venue's time zone:")} <strong>{data.hours.time_zone}</strong>. {T("Бронирование бесплатно, на 30 минут — 8 часов, не более чем за 30 дней.", "Reservations are free, for 30 minutes to 8 hours, up to 30 days ahead.")}</p>}
    {!data.stations.some(s => s.active) && <p>{T("Площадка ещё не открыла бронирование станций.", "The venue has not opened station reservations yet.")}</p>}
    <div className="grid grid-2">{data.stations.filter(s => s.active).map(s => <article key={s.id} className="card"><h4>{s.name}</h4><p>{s.equipment}</p><details><summary>{T("Занятые интервалы", "Booked times")}</summary>{data.availability.filter(b => b.station_id === s.id).map((b, i) => <p key={i}><LocalTime iso={b.starts_at} lang={lang} /> — <LocalTime iso={b.ends_at} lang={lang} /></p>)}{!data.availability.some(b => b.station_id === s.id) && <p>{T("Бронирований пока нет", "No reservations yet")}</p>}</details>{userId && data.hours ? <ActionForm action="club.book" lang={lang} back={back} hidden={{ station: s.id, timeZone: data.hours.time_zone }}><Field label={T("Начало", "Start")}><input name="startsAt" type="datetime-local" required /></Field><Field label={T("Окончание", "End")}><input name="endsAt" type="datetime-local" required /></Field><button className="btn btn-primary">{T("Забронировать", "Reserve")}</button></ActionForm> : !userId && <Link href={`/${lang}/signin?next=${back}`}>{T("Войти для бронирования", "Sign in to reserve")}</Link>}</article>)}</div>
    {!!data.bookings.length && <><h3>{T("Ваши бронирования", "Your reservations")}</h3>{data.bookings.map(b => <article className="card" key={b.id}><strong>{b.name} · {status(b.status)}</strong><p><LocalTime iso={b.starts_at} lang={lang} /> — <LocalTime iso={b.ends_at} lang={lang} /></p>{b.status === "reserved" && <ActionForm action="club.booking_status" lang={lang} back={back} hidden={{ booking: b.id, status: "cancelled" }}><button className="btn btn-ghost">{T("Отменить бронь", "Cancel reservation")}</button></ActionForm>}</article>)}</>}
    {userId && <Link className="btn btn-ghost section-tight" href={`/${lang}/passes`}>{T("Открыть мои QR-пропуска", "Open my QR passes")}</Link>}
  </section>;
}
