import type { Locale } from "@/lib/i18n.ts";
import type { Database } from "@/server/db.ts";
import type { SessionUser } from "@/server/auth.ts";
import { requireSection } from "@/server/access.ts";
import type { CommunityHost } from "@/server/community-hosts.ts";
import { ActionForm, Field } from "./ui";
import { LocalTime } from "./time";
type Props = { db: Database; user: SessionUser; lang: Locale; back: string };
export async function CommunityHostsAdmin({ db, user, lang, back }: Props) {
  requireSection(user, "academy"); const T = (ru: string, en: string) => lang === "ru" ? ru : en;
  const rows = await db.query<CommunityHost>("select h.*,u.username,u.display_name from community_hosts h join users u on u.id=h.user_id order by (h.status='pending') desc,h.updated_at desc limit 100");
  return <section className="section-tight"><h2 className="h3">{T("Ведущие и психологи сообщества", "Community hosts & practitioners")}</h2><p className="small muted">{T("Проверьте личность, организацию, квалификацию, право практиковать в указанном регионе и страницу записи. Психологическая практика требует отдельной проверки специалиста и учреждения. Не одобряйте собственную карточку.", "Verify identity, organisation, qualifications, permission to practise in the stated location and the booking page. Psychological practice needs separate practitioner and facility review. Do not approve your own profile.")}</p>
    {rows.length ? rows.map(p => <details key={p.user_id} className="card disclosure"><summary>{p.display_name} · {p.role} · {p.status}</summary><p>{p.bio}</p><p>{p.languages} · {p.jurisdiction} · {p.organisation} · {p.credential}</p><p className="row">{p.credential_url && <a href={p.credential_url} target="_blank" rel="noopener noreferrer">{T("Проверка квалификации ↗", "Credential source ↗")}</a>}{p.booking_url && <a href={p.booking_url} target="_blank" rel="noopener noreferrer">{T("Условия и запись ↗", "Terms and booking ↗")}</a>}</p><p className="small">{p.review_note}</p>
      {p.user_id !== user.id && <ActionForm action="community.host_review" lang={lang} back={back} hidden={{ user: p.user_id, version: String(p.version) }} className="stack-sm"><Field label={T("Решение", "Decision")}><select name="status"><option value="rejected">{T("Вернуть на доработку", "Reject for corrections")}</option><option value="verified">{T("Подтвердить и опубликовать", "Verify and publish")}</option><option value="suspended">{T("Приостановить", "Suspend")}</option></select></Field><Field label={T("Проверка действует до — не позже окончания документов", "Review valid until — no later than credential expiry")}><input name="until" type="date" /></Field><Field label={T("Обоснование и источники проверки", "Review evidence and sources")}><textarea name="note" required minLength={20} maxLength={1000} /></Field><label className="check"><input name="verified" type="checkbox" value="1" />{T("Подтверждаю проверку всех указанных сведений и применимых разрешений", "I verified the stated details and applicable permissions")}</label><button className="btn btn-primary">{T("Сохранить решение", "Save decision")}</button></ActionForm>}</details>) : <p>{T("Заявок пока нет", "No applications yet")}</p>}</section>;
}
export async function CommunityReportsAdmin({ db, user, lang, back }: Props) {
  requireSection(user, "conduct"); const T = (ru: string, en: string) => lang === "ru" ? ru : en;
  const rows = await db.query<{ id: string; reporter_id: string; subject_id: string; reporter: string; subject: string; reason: string; excerpt: string; created_at: Date }>("select r.*,a.username as reporter,b.username as subject from community_reports r join users a on a.id=r.reporter_id join users b on b.id=r.subject_id where r.status='open' order by r.created_at limit 100");
  return <section className="section-tight"><h2 className="h3">{T("Жалобы из чатов сообщества", "Community chat reports")}</h2>{rows.length ? rows.map(r => <article key={r.id} className="card stack-sm"><p>@{r.reporter} → @{r.subject} · <LocalTime iso={r.created_at} lang={lang} /></p><p className="prewrap">{r.reason}</p><blockquote className="prewrap">{r.excerpt}</blockquote>{![r.reporter_id,r.subject_id].includes(user.id) && <ActionForm action="community.report_review" lang={lang} back={back} hidden={{ report: r.id }} className="stack-sm"><Field label={T("Решение модератора", "Moderator decision")}><textarea name="decision" minLength={10} maxLength={1000} required /></Field><label className="check"><input name="remove" type="checkbox" value="1" />{T("Удалить сообщение из чата", "Remove message from chat")}</label><button className="btn btn-primary">{T("Закрыть жалобу", "Resolve report")}</button></ActionForm>}</article>) : <p>{T("Открытых жалоб нет", "No open reports")}</p>}</section>;
}
