import type { Database } from "@/server/db.ts";
import type { Locale } from "@/lib/i18n.ts";
import type { RentalNode,RentalTemplate } from "@/server/rentals.ts";
import { rentalStatus } from "@/lib/rental-text.ts";
import { ActionForm,Field } from "./ui";
export async function RentalAdmin({db,lang,back}:{db:Database;lang:Locale;back:string}){
  const T=(ru:string,en:string)=>lang==="ru"?ru:en;
  const [nodes,templates]=await Promise.all([db.query<RentalNode&{username:string}>("select n.*,u.username from rental_nodes n join users u on u.id=n.owner_id where u.status='active' order by (n.status='pending') desc,n.created_at desc limit 100"),db.query<RentalTemplate&{node_name:string}>("select t.*,n.name node_name from rental_templates t join rental_nodes n on n.id=t.node_id join users u on u.id=n.owner_id where u.status='active' order by (t.status='pending') desc,t.created_at desc limit 100")]);
  const decision=<><Field label={T("Решение","Decision")}><select name="decision"><option value="approved">{T("Подтвердить","Approve")}</option><option value="suspended">{T("Приостановить","Suspend")}</option></select></Field><Field label={T("Проверенные факты и основание","Verified facts and reason")}><textarea name="note" minLength={10} maxLength={1000} required/></Field><button className="btn btn-primary">{T("Сохранить решение","Save decision")}</button></>;
  return <section className="section-tight"><h2>{T("Выделенные игровые серверы","Dedicated game servers")}</h2><p className="muted">{T("Проверьте владельца, ограничения ресурсов, остановку при потере связи, квоты хранения, сетевые порты, образ и права на игру. Свой узел или шаблон нельзя подтвердить самому. Изменение решения по узлу завершает его текущие сеансы.","Verify the owner, resource limits, loss-of-contact shutdown, storage quotas, network ports, image and game rights. Owners cannot approve their own node or template. Changing a node decision releases its current sessions.")}</p>{!nodes.length&&<p>{T("Заявок пока нет.","No applications yet.")}</p>}<div className="grid grid-2">{nodes.map(n=><article className="card" key={n.id}><h3>{n.name} · @{n.username}</h3><p>{rentalStatus(n.status,lang)} · {n.region} · {n.address}</p><p>{n.cpu_millis/1000} CPU · {n.memory_mb} MB RAM · {n.storage_mb} MB · {n.port_start}–{n.port_end}</p><p>{n.review_note}</p><ActionForm action="rental.node_review" lang={lang} back={back} hidden={{node:n.id}}>{decision}</ActionForm></article>)}</div><h3>{T("Шаблоны","Templates")}</h3><div className="grid grid-2">{templates.map(t=><article className="card" key={t.id}><h4>{t.name} · {t.node_name}</h4><p>{rentalStatus(t.status,lang)} · {t.game} · {t.cpu_millis/1000} CPU · {t.memory_mb} MB RAM · {t.disk_mb} MB</p><p className="small" style={{overflowWrap:"anywhere"}}>{t.local_key} · {t.fingerprint}</p><ul>{t.ports.map(p=><li key={p.name} style={{overflowWrap:"anywhere"}}>{p.name} · {p.container}/{p.protocol}</li>)}</ul><a className="text-link" href={t.evidence_url} target="_blank" rel="noopener noreferrer">{T("Материалы для проверки","Review evidence")}</a><p>{t.review_note}</p><ActionForm action="rental.template_review" lang={lang} back={back} hidden={{template:t.id}}>{decision}</ActionForm></article>)}</div></section>;
}
