import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { GAMES } from "@/lib/games.ts";
import { viewer } from "@/server/viewer.ts";
import { socialProfile, discover, myMatches, SOCIAL_CONSENT } from "@/server/social.ts";
import { ActionForm, Check, DbDown, Field, Flash, PageHead, one, type SearchParams } from "@/components/ui";
export const metadata = { title: "MAXIMUS · Gamer connections 18+", robots: { index: false, follow: false } };

export default async function Dating({ params, searchParams }: { params: Promise<{ lang: string }>; searchParams: SearchParams }) {
  const { lang } = await params; if (!isLocale(lang)) notFound();
  const T = (ru: string, en: string) => lang === "ru" ? ru : en, sp = await searchParams, back = `/${lang}/dating`;
  const { db, user } = await viewer(); if (!db) return <DbDown lang={lang} />;
  if (!user) redirect(`/${lang}/signin?next=${back}`);
  const [profile, matches, blocks] = await Promise.all([socialProfile(db, user.id), myMatches(db, user.id), db.query<{ subject_id: string; display_name: string }>("select b.subject_id,u.display_name from social_blocks b join users u on u.id=b.subject_id where b.user_id=$1", [user.id])]);
  const candidates = profile?.visible && !user.restricted ? await discover(db, user, { city: one(sp.city), game: one(sp.game), minAge: one(sp.minAge), maxAge: one(sp.maxAge) }).catch(() => []) : [];
  const intents: Record<string, string> = { gaming: T("Совместная игра", "Gaming together"), friendship: T("Дружба", "Friendship"), dating: T("Знакомства", "Dating") };
  return <div className="container page"><PageHead eyebrow="18+" title={T("Знакомства среди игроков", "Gamer connections")} lead={T("Отдельный добровольный профиль. Вы выбираете цель знакомства; переписка доступна только после взаимного выбора.", "A separate opt-in profile. Choose what you are looking for; messaging opens only after a mutual match.")} /><Flash lang={lang} params={sp} />
    <details className="card" open={!profile?.visible}><summary>{profile?.visible ? T("Изменить профиль знакомства", "Edit connection profile") : T("Создать или включить профиль", "Create or enable profile")}</summary>
      <ActionForm action="social.profile" lang={lang} back={back} className="stack">
        <div className="grid grid-2"><Field label={T("Цель", "Intent")}><select name="intent" defaultValue={profile?.intent ?? "gaming"}>{Object.entries(intents).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field><Field label={T("Возраст", "Age")}><input name="age" type="number" min="18" max="100" required defaultValue={profile?.age} /></Field><Field label={T("Город (необязательно)", "City (optional)")}><input name="city" maxLength={80} defaultValue={profile?.city} /></Field><Field label={T("Любимая игра", "Preferred game")}><select name="game" defaultValue={profile?.game ?? ""}><option value="">{T("Любая", "Any")}</option>{GAMES.map(g => <option key={g.slug} value={g.slug}>{g.name}</option>)}</select></Field></div>
        <Field label={T("Языки общения", "Languages")}><input name="languages" maxLength={100} defaultValue={profile?.languages} /></Field>
        <Field label={T("Игровые предпочтения: режим, время, стиль", "Gaming preferences: mode, schedule, play style")}><textarea name="gamingPreferences" maxLength={400} defaultValue={profile?.gaming_preferences} /></Field>
        <Field label={T("Пожелания к знакомству", "Connection preferences")}><textarea name="relationshipPreferences" maxLength={400} defaultValue={profile?.relationship_preferences} /></Field>
        <Field label={T("О себе", "About you")}><textarea name="bio" minLength={10} maxLength={600} required defaultValue={profile?.bio} /></Field>
        <Check name="consent" required label={T(`Мне 18 лет или больше. Я добровольно разрешаю показывать эти сведения другим участникам с такой же целью знакомства. Понимаю, что могу скрыть профиль и закрыть общение в любой момент (${SOCIAL_CONSENT}).`, `I am 18 or older. I voluntarily allow these details to be shown to members with the same connection intent. I can hide my profile and close conversations at any time (${SOCIAL_CONSENT}).`)} />
        <p className="small muted">{T("Не указывайте адрес проживания, документы или финансовые данные. Жалоба автоматически блокирует общение; относящееся к жалобе сообщение увидит модератор.", "Do not include your home address, identity documents or financial details. Reporting blocks contact; a moderator can see the reported message.")}</p>
        <button className="btn btn-primary">{T("Сохранить и показать профиль", "Save and show profile")}</button>
      </ActionForm>
    </details>
    {profile?.visible && <ActionForm action="social.withdraw" lang={lang} back={back} className="section-tight"><button className="btn btn-ghost">{T("Скрыть профиль и закрыть переписки", "Hide profile and close conversations")}</button></ActionForm>}
    <section className="section-tight"><h2>{T("Ваши совпадения", "Your matches")}</h2>{matches.length ? <ul className="list">{matches.map(m => <li key={m.id}><Link href={`${back}/${m.id}`}>{m.display_name}</Link><span>{m.status === "closed" ? T("Общение закрыто", "Conversation closed") : m.unread ? `${T("Новых", "New")}: ${m.unread}` : T("Совпадение", "Match")}</span></li>)}</ul> : <p>{T("После взаимного выбора здесь появится переписка.", "Conversations appear here after a mutual match.")}</p>}</section>
    {profile?.visible && <section className="section-tight"><h2>{intents[profile.intent]}</h2><form method="get" className="grid grid-3"><Field label={T("Город", "City")}><input name="city" defaultValue={one(sp.city)} maxLength={80} /></Field><Field label={T("Игра", "Game")}><select name="game" defaultValue={one(sp.game)}><option value="">{T("Любая", "Any")}</option>{GAMES.map(g => <option key={g.slug} value={g.slug}>{g.name}</option>)}</select></Field><Field label={T("Возраст от", "Age from")}><input name="minAge" type="number" min="18" max="100" defaultValue={one(sp.minAge) || "18"} /></Field><Field label={T("Возраст до", "Age to")}><input name="maxAge" type="number" min="18" max="100" defaultValue={one(sp.maxAge) || "100"} /></Field><button className="btn btn-ghost">{T("Применить фильтры", "Apply filters")}</button><Link className="btn btn-ghost" href={back}>{T("Сбросить", "Reset")}</Link></form>
      {!candidates.length && <p className="notice">{T("Подходящих профилей пока нет. Измените фильтры или вернитесь позже.", "No profiles match yet. Adjust the filters or return later.")}</p>}
      <div className="grid grid-2">{candidates.map(p => <article className="card" key={p.user_id}><h3>{p.display_name}, {p.age}</h3><p className="muted">{p.city} · {p.languages} · {GAMES.find(g => g.slug === p.game)?.name}</p><p className="prewrap">{p.bio}</p><p>{p.gaming_preferences}</p><p>{p.relationship_preferences}</p><div className="row"><ActionForm action="social.like" lang={lang} back={back} hidden={{ user: p.user_id }}><button className="btn btn-primary">{T("Хочу познакомиться", "Interested")}</button></ActionForm><ActionForm action="social.block" lang={lang} back={back} hidden={{ user: p.user_id }}><button className="btn btn-ghost">{T("Блокировать", "Block")}</button></ActionForm></div><details><summary>{T("Пожаловаться", "Report")}</summary><ActionForm action="social.report" lang={lang} back={back} hidden={{ user: p.user_id }}><Field label={T("Причина", "Reason")}><textarea name="reason" minLength={10} maxLength={1200} required /></Field><button className="btn btn-ghost">{T("Отправить жалобу и заблокировать", "Report and block")}</button></ActionForm></details></article>)}</div>
    </section>}
    {!!blocks.length && <details className="section-tight"><summary>{T("Заблокированные профили", "Blocked profiles")}</summary>{blocks.map(b => <ActionForm key={b.subject_id} action="social.unblock" lang={lang} back={back} hidden={{ user: b.subject_id }} className="row"><span>{b.display_name}</span><button className="btn btn-ghost btn-sm">{T("Разблокировать", "Unblock")}</button></ActionForm>)}</details>}
  </div>;
}
