import assert from "node:assert/strict";
import { mkdir,readFile,writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { chromium } from "playwright-core";
const BASE="http://127.0.0.1:3110";
const env={...process.env,DATABASE_URL:"",POSTGRES_URL:"",NEON_DATABASE_URL:"",MAIL_TRANSPORT:"",MAIL_FROM:"",RESEND_API_KEY:"",SMTP_URL:"",MV_EXPERIENCE_DISABLED:"1",STEAM_WEB_API_KEY:"",FACEIT_API_KEY:"",MV_DATA_DIR:"/tmp/c30-browser-acceptance",MV_EMBEDDED_DB:"1",MV_LOCAL:"1",NEXT_PUBLIC_SITE_URL:BASE,MV_COMMUNITY_VOICE_ENABLED:"",LIVEKIT_URL:"",MV_TURN_URLS:"",MV_TURN_SECRET:"",MV_BROADCAST_ENABLED:"",STRIPE_SECRET_KEY:"",STRIPE_WEBHOOK_SECRET:""};
const run=args=>new Promise((resolve,reject)=>{const p=spawn(process.execPath,args,{env,stdio:"inherit"});p.on("error",reject);p.on("exit",code=>code===0?resolve():reject(new Error(`Child exit ${code}`)));});
await mkdir("artifacts/c30-screens",{recursive:true});await run(["--experimental-strip-types","scripts/community-fixture.ts"]);
const fixture=JSON.parse(await readFile("artifacts/c30-fixture.json","utf8"));
const server=spawn(process.execPath,["node_modules/next/dist/bin/next","start","--hostname","127.0.0.1","--port","3110"],{env,stdio:"pipe"});let logs="",browser;
server.stdout.on("data",b=>logs+=b);server.stderr.on("data",b=>logs+=b);
const checks=[],errors=[];const mark=s=>{checks.push(s);console.log(`PASS ${s}`);};
const post=(context,route,data)=>context.request.post(BASE+route,{headers:{origin:BASE},data});
try{
 let ready=false;for(let i=0;i<60;i++){if(server.exitCode!==null)throw new Error("Server exited");try{if((await fetch(BASE+"/ru/signin")).status===200){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true});
 const guest=await browser.newContext();assert.equal((await post(guest,"/api/community/chat",{action:"read",scope:"global"})).status(),401);assert.equal((await guest.request.get(BASE+"/api/cron/community")).status(),404);const target=`/ru/community/chat?scope=team&id=${fixture.team.id}`;const signin=await guest.request.get(BASE+target,{maxRedirects:0});assert.equal(new URL(signin.headers().location,BASE).searchParams.get("next"),target);await guest.close();mark("Anonymous chat denied and voice worker requires authentication");
 async function context(prefix){const c=await browser.newContext({storageState:`artifacts/c30-${prefix}-state.json`,viewport:{width:1440,height:1000}});await c.route("**/*",r=>new URL(r.request().url()).origin===BASE?r.continue():r.abort());await c.addInitScript(()=>{window.__micRequests=0;navigator.mediaDevices.getUserMedia=async()=>{window.__micRequests++;throw new DOMException("Denied","NotAllowedError");};});return c;}
 const captain=await context("captain"),player=await context("player"),page=await captain.newPage(),other=await player.newPage();
 for(const p of[page,other]){p.on("pageerror",e=>errors.push(e.message));p.on("response",r=>{if(r.status()>=500)errors.push(`${r.status()} ${new URL(r.url()).pathname}`);});}
 await page.goto(BASE+"/ru/hub");await page.locator('.account-menu > summary').click();await page.locator('.account-panel').getByRole("link",{name:"Мои команды и приглашения",exact:true}).click();await page.getByRole("heading",{name:"Мои команды и приглашения",exact:true}).waitFor();await page.locator(`#invitation-${fixture.prior}`).waitFor();mark("Account dropdown directly opens personal teams, prior reservations and invitation controls");
 const invite=page.locator('[data-invitation-composer]');await invite.getByLabel("Email получателя",{exact:true}).fill("recipient@example.test");await invite.locator('input[name="username"]').fill(`@${fixture.next}`);await invite.getByRole("button",{name:"Сохранить приглашение в очередь",exact:true}).click();
 await invite.getByText("Приглашение сохранено в очереди отправки",{exact:true}).waitFor();
 const reserved=page.locator(`#invitation-${fixture.next}`);await reserved.waitFor();await page.reload();await reserved.waitFor();await page.locator('#delivery-status').getByText("recipient@example.test",{exact:true}).waitFor();mark("Email is provided before reservation and exact queued recipient persists after reload; no mail sent");
 for(const lang of["ru","en"])for(const width of[390,1440]){
  await page.setViewportSize({width,height:1000});await page.goto(`${BASE}/${lang}/my-teams`);await page.getByRole("heading",{name:lang==="ru"?"Мои команды и приглашения":"My teams & invitations",exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`artifacts/c30-screens/teams-${lang}-${width}.png`,fullPage:true});
  await page.goto(`${BASE}/${lang}/community`);await page.getByRole("heading",{name:lang==="ru"?"Среди своих":"Among your people",exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`artifacts/c30-screens/community-${lang}-${width}.png`,fullPage:true});
 }mark("RU/EN team desk and community home render at 390 and 1440 px without overflow");
 await page.goto(BASE+"/ru/my-teams");await page.getByLabel("Игроку на сайте",{exact:true}).check();await page.locator('[data-invitation-composer] input[name="username"]').fill(`@${fixture.player}`);await page.locator('[data-invitation-composer]').getByRole("button",{name:"Отправить приглашение игроку",exact:true}).click();await page.locator('#outgoing').getByRole("link",{name:`@${fixture.player}`,exact:true}).waitFor();
 await other.goto(BASE+"/ru/my-teams");await other.locator('#incoming').getByRole("button",{name:"Вступить в команду",exact:true}).click();await other.getByRole("link",{name:"Чат нашей команды",exact:true}).waitFor();mark("Existing player receives and accepts a team invitation, then reaches the private team chat");
 await page.goto(BASE+`/ru/community?username=${fixture.player}#friends`);assert.equal(await page.locator('form[action*="community.friend"] input[name="username"]').inputValue(),fixture.player);await page.getByRole("button",{name:"Отправить заявку в друзья",exact:true}).click();
 await other.goto(BASE+"/ru/community");await other.getByRole("button",{name:"Принять в друзья",exact:true}).click();await other.getByLabel("Ваше сообщение",{exact:true}).fill("Private message between friends");await other.locator('form[action*="social.message"] button').click();await other.getByText("Private message between friends",{exact:true}).waitFor();assert.match(other.url(),/\/dating\/[0-9a-f-]+/);mark("Friend requests open a working private conversation without a dating profile");
 await page.goto(BASE+"/ru/community/chat");await page.getByLabel("Ваше сообщение",{exact:true}).fill("Hello from the community acceptance");await page.getByRole("button",{name:"Отправить в чат",exact:true}).click();await page.getByText("Hello from the community acceptance",{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>window.__micRequests),0);assert.ok(await page.getByRole("button",{name:"Войти в голосовую комнату",exact:true}).isDisabled());
 const badOrigin=await captain.request.post(BASE+"/api/community/chat",{headers:{origin:"https://invalid.example"},data:{action:"read",scope:"global"}});assert.equal(badOrigin.status(),400);
 await other.goto(BASE+"/ru/community/chat");const message=other.getByRole("listitem").filter({hasText:"Hello from the community acceptance"});await message.locator('summary').click();await message.getByLabel("Причина жалобы",{exact:true}).fill("Isolated report acceptance check");await message.getByRole("button",{name:"Передать сообщение модератору и заблокировать",exact:true}).click();await message.waitFor({state:"detached"});mark("Shared chat sends and reports real stored messages; block hides contact; voice never captures automatically");
 await page.goto(BASE+"/ru/settings#avatar");await page.locator('input[name="avatar"]').setInputFiles("artifacts/c30-avatar.png");await page.getByText("Изображение готово к загрузке",{exact:true}).waitFor();await page.getByRole("button",{name:"Сохранить аватар",exact:true}).click();const avatar=page.locator('#avatar img');await avatar.waitFor();assert.ok(await avatar.evaluate(el=>el.complete&&el.naturalWidth>0));const src=await avatar.getAttribute("src");assert.equal((await player.request.get(BASE+src)).status(),404);assert.equal((await captain.request.get(BASE+src)).status(),200);mark("Photo upload renders and avatar endpoint respects bilateral blocking");
 await page.goto(BASE+"/ru/community/support");await page.getByText(/Проверенных ведущих и специалистов пока нет/).waitFor();await page.getByRole("heading",{name:"ПСИХОЛОГИНЯ · профессиональная поддержка",exact:true}).waitFor();assert.equal(await page.getByRole("link",{name:"Условия и запись у специалиста ↗",exact:true}).count(),0);await page.setViewportSize({width:390,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:"artifacts/c30-screens/support-ru-390.png",fullPage:true});
 const policy=(await captain.request.get(BASE+"/ru/community/chat")).headers()["permissions-policy"];assert.match(policy,/microphone=\(self\)/);assert.match(policy,/camera=\(\)/);assert.deepEqual(errors,[]);mark("Support shows the real empty directory and qualification requirements; scoped voice policy; no browser errors");
 await writeFile("artifacts/c30-browser-report.json",JSON.stringify({checks,errors,externalVoiceVerified:false,noEmailsSent:true},null,2));
}finally{await browser?.close();server.kill("SIGTERM");await writeFile("artifacts/c30-server.log",logs);}
