/** Complete member/operator flows against isolated local PostgreSQL + HTTP agent adapter. */
import assert from "node:assert/strict";
import { readFile,writeFile,rename,mkdir } from "node:fs/promises";
import { spawn } from "node:child_process";
import { chromium } from "playwright-core";
const BASE=process.env.BASE??"http://127.0.0.1:3100";
if(!/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(BASE))throw Error("Local fixture only");
const f=JSON.parse(await readFile("artifacts/c25-fixture.json","utf8")),errors=[],checks=[];
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true});
const pages={};let driver,control;
const mark=s=>{checks.push(s);console.log(`PASS ${s}`);};
async function go(p,path){const r=await p.goto(BASE+path);assert.ok(r&&r.status()<400,`${path}: ${r?.status()}`);await p.waitForLoadState("load");}
async function submit(p,action,fields={},selector){
  if(action==="rental.access"&&fields.username)selector="form[action^='/api/a/rental.access?']:has(select[name=role])";
  const form=selector?p.locator(selector):p.locator(`form[action^='/api/a/${action}?']`).first();assert.equal(await form.count(),1,`Missing ${action}`);
  const details=form.locator("xpath=ancestor::details");for(let i=0;i<await details.count();i++)if(await details.nth(i).getAttribute("open")===null)await details.nth(i).locator(":scope > summary").click();
  for(const [name,value] of Object.entries(fields)){const el=form.locator(`[name='${name}']`).first(),type=await el.getAttribute("type");if(type==="checkbox")await el.setChecked(Boolean(value));else if(type==="hidden")assert.ok(await el.inputValue()===String(value));else if(await el.evaluate(e=>e.tagName)==="SELECT")await el.selectOption(String(value));else await el.fill(String(value));}
  await Promise.all([p.waitForNavigation(),form.locator("button:not([type=button])").first().click()]);assert.equal(new URL(p.url()).searchParams.get("e"),null,`${action} failed: ${new URL(p.url()).searchParams.get("e")}`);
}
async function eventually(fn,label,timeout=18000){const end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await new Promise(r=>setTimeout(r,300));}throw Error(`Timed out: ${label}`);}
async function status(){try{return JSON.parse(await readFile("artifacts/c25-agent-status.json","utf8"));}catch{return {};}}
async function saveControl(){await writeFile("artifacts/c25-agent-control.tmp",JSON.stringify(control),{mode:0o600});await rename("artifacts/c25-agent-control.tmp","artifacts/c25-agent-control.json");}
async function snapshot(p,path,label){for(const lang of ["en","ru"])for(const width of [390,1440]){await p.setViewportSize({width,height:960});await go(p,path.replace("/en/",`/${lang}/`));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1,`${label} ${lang} ${width} overflow`);await p.screenshot({path:`artifacts/c25-screens/${label}-${lang}-${width}.png`,fullPage:true});}await p.setViewportSize({width:1440,height:1000});}
try{
  await mkdir("artifacts/c25-screens",{recursive:true});
  for(const [name,account] of Object.entries(f.accounts)){const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:["clipboard-read","clipboard-write"]});await context.addCookies([{name:"mv_session",value:account.token,url:BASE,httpOnly:true,sameSite:"Lax"}]);const p=await context.newPage();pages[name]=p;p.on("pageerror",e=>errors.push(`${name}: ${e.message}`));p.on("console",m=>{if(m.type()==="error")errors.push(`${name}: ${m.text()}`);});p.on("response",r=>{if(r.status()>=500)errors.push(`${name}: ${r.status()} ${new URL(r.url()).pathname}`);});}
  const {owner:o,alice:a,bob:b,staff:s}=pages;
  await go(o,"/en/server-rentals");await submit(o,"rental.node",{name:"Browser node",region:"Local acceptance",address:"games.example.org",cpuMillis:2000,memoryMb:2048,storageMb:10240,portStart:27015,portEnd:27016,consent:true});
  const nodePath=new URL(o.url()).pathname,nodeId=nodePath.split("/").at(-1);
  await go(s,"/en/admin?tab=system");await submit(s,"rental.node_review",{decision:"approved",note:"Independent review of local browser adapter fixture"},`form[action^='/api/a/rental.node_review?']:has(input[value='${nodeId}'])`);
  await go(o,nodePath);await o.getByRole("button",{name:"Create or rotate key",exact:true}).click();await o.locator("input[type=password]").waitFor();const key=await o.locator("input[type=password]").inputValue();assert.ok(/^mvr_/.test(key));
  await o.getByRole("button",{name:"Copy key",exact:true}).click();assert.ok(await o.evaluate(()=>navigator.clipboard.readText())===key);await o.getByRole("button",{name:"Hide",exact:true}).click();assert.equal(await o.locator("input[type=password]").count(),0);
  await submit(o,"rental.enabled");await submit(o,"rental.template",{name:f.template.name,game:f.template.game,localKey:f.template.localKey,fingerprint:f.fingerprint,cpuMillis:f.template.cpuMillis,memoryMb:f.template.memoryMb,diskMb:f.template.diskMb,ports:JSON.stringify(f.template.ports),evidence:"https://example.org/local-fixture"});
  await go(s,"/en/admin?tab=system");await submit(s,"rental.template_review",{decision:"approved",note:"Local pinned manifest checked; no production game claim"});
  control={portal:BASE,key,template:f.template,config:{nodeId,cpuMillis:2000,memoryMb:2048,storageMb:10240,portStart:27015,portEnd:27016}};await saveControl();driver=spawn("python3",["scripts/rental-agent-fixture.py","artifacts/c25-agent-control.json"],{stdio:["ignore","ignore","pipe"]});let driverError="";driver.stderr.on("data",d=>{driverError+=d;});
  await eventually(async()=>{if(driver.exitCode!==null)throw Error(`Agent adapter exited ${driver.exitCode}: ${driverError}`);return (await status()).status==="connected";},"agent connection");mark("Node registration/review, template registration/review, one-time key copy/hide, enabled node and real HTTP heartbeat");
  await go(a,"/en/server-rentals");await a.locator("form[method=get] select[name=game]").selectOption("cs2");await a.locator("form[method=get] input[name=region]").fill("Local acceptance");await Promise.all([a.waitForNavigation(),a.getByRole("button",{name:"Apply filters",exact:true}).click()]);assert.match(await a.locator("body").innerText(),/Browser dedicated server/);
  await snapshot(a,new URL(a.url()).pathname+new URL(a.url()).search,"catalogue");await go(a,"/en/server-rentals");await submit(a,"rental.allocate",{minutes:60,delayMinutes:0,consent:true});const leasePath=new URL(a.url()).pathname;
  await eventually(async()=>{await a.getByRole("button",{name:"Refresh status",exact:true}).click();return await a.getByRole("heading",{name:"Game connection",exact:true}).count()>0;},"server started");assert.match(await a.locator("body").innerText(),/games\.example\.org:27015/);mark("Game/region filters → reserve → agent starts correct manifest → real connection address and logs");
  await snapshot(a,leasePath,"session-running");await snapshot(o,nodePath,"node");await snapshot(s,"/en/admin?tab=system","review");await go(a,leasePath);
  await submit(a,"rental.access",{username:f.accounts.bob.user.username,role:"viewer"});await go(b,leasePath);assert.equal(await b.getByRole("button",{name:"Stop",exact:true}).count(),0);
  await submit(a,"rental.access",{username:f.accounts.bob.user.username,role:"operator"});await go(b,leasePath);assert.equal(await b.getByRole("button",{name:"Release and delete data",exact:true}).count(),0);await submit(b,"rental.stop");
  await eventually(async()=>{await a.getByRole("button",{name:"Refresh status",exact:true}).click();return await a.getByRole("button",{name:"Create backup",exact:true}).isEnabled();},"confirmed stop");
  await submit(a,"rental.backup");await eventually(async()=>{await a.getByRole("button",{name:"Refresh status",exact:true}).click();return await a.getByRole("button",{name:"Restore this backup",exact:true}).count()>0;},"backup receipt");
  await submit(a,"rental.restore");await eventually(async()=>{await a.getByRole("button",{name:"Refresh status",exact:true}).click();return await a.getByRole("button",{name:"Start",exact:true}).isEnabled();},"restore receipt");assert.equal((await status()).restores,1);
  await snapshot(a,leasePath,"backup");await go(a,leasePath);await submit(a,"rental.start");await eventually(async()=> (await status()).running===1,"resumed game");
  await eventually(async()=>await a.getByRole("button",{name:"Restart",exact:true}).isEnabled(),"restart cooldown",45000);await submit(a,"rental.restart");await eventually(async()=> (await status()).starts>=3,"explicit restart");
  await submit(a,"rental.access",{},`form[action^='/api/a/rental.access?']:has(input[value='remove'])`);assert.equal((await b.context().request.get(BASE+leasePath)).status(),404);mark("Viewer/operator permissions → confirmed stop → backup/restore → start/restart → immediate access revocation");
  await submit(o,"rental.enabled");await go(b,"/en/server-rentals");assert.match(await b.locator("body").innerText(),/No free configurations/);await go(o,nodePath);await submit(o,"rental.enabled");
  await go(b,"/en/server-rentals");await submit(b,"rental.allocate",{minutes:30,delayMinutes:60,consent:true});const scheduledPath=new URL(b.url()).pathname;
  await eventually(async()=>{await b.getByRole("button",{name:"Refresh status",exact:true}).click();return (await b.locator("body").innerText()).includes("Scheduled start is pending");},"scheduled stop");assert.equal((await status()).running,1);await submit(b,"rental.release");
  await eventually(async()=>{await b.getByRole("button",{name:"Refresh status",exact:true}).click();return (await b.locator("body").innerText()).includes("Released; data deleted");},"scheduled cleanup");mark("Node pause/resume and future booking holds resources without early start; release receives cleanup acknowledgement");
  await go(a,leasePath);await submit(a,"rental.release");await eventually(async()=>{await a.getByRole("button",{name:"Refresh status",exact:true}).click();return (await a.locator("body").innerText()).includes("Released; data deleted");},"full cleanup");assert.equal((await status()).volumes,0);assert.equal(await a.getByRole("button",{name:"Restore this backup",exact:true}).count(),0);mark("Final release removes game volumes and backups; endpoint confirms cleanup before releasing capacity");
  await go(o,nodePath);await o.getByRole("button",{name:"Create or rotate key",exact:true}).click();await o.locator("input[type=password]").waitFor();const rotated=await o.locator("input[type=password]").inputValue();assert.ok(rotated!==key);await eventually(async()=>(await status()).status==="HTTPError","old key rejected");control.key=rotated;await saveControl();await eventually(async()=>(await status()).status==="connected","rotated key accepted");
  await o.getByRole("button",{name:"Revoke key",exact:true}).click();await eventually(async()=>(await status()).status==="HTTPError","revoked key rejected");assert.equal((await status()).running,0);mark("Credential rotation and revocation reject the old agent key over HTTP");
  await go(s,"/en/admin?tab=system");await submit(s,"rental.template_review",{decision:"suspended",note:"Local acceptance complete; fixture template disabled"});await submit(s,"rental.node_review",{decision:"suspended",note:"Local acceptance complete; fixture node disabled"},`form[action^='/api/a/rental.node_review?']:has(input[value='${nodeId}'])`);
  const guest=await browser.newPage();await go(guest,"/ru/server-rentals");await guest.getByRole("link",{name:"Войти как игрок или оператор",exact:true}).click();await guest.waitForURL("**/ru/signin?**");assert.match(guest.url(),/\/ru\/signin/);await guest.close();
  assert.deepEqual(errors,[]);mark("Review suspension, guest sign-in link, twenty populated RU/EN desktop/mobile screenshots without overflow or browser errors");
  await writeFile("artifacts/c25-browser-results.json",JSON.stringify({checks,errors,paths:{nodePath,leasePath,scheduledPath}},null,2));console.log(`PASS ${checks.length} complete browser scenarios`);
}finally{driver?.kill("SIGTERM");await browser.close();}
