import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { isLocale } from "@/lib/i18n.ts";
import { GAMES } from "@/lib/games.ts";
import { viewer } from "@/server/viewer.ts";
import { isAdmin } from "@/server/access.ts";
import { requireStaffMfa } from "@/server/mfa.ts";
import type { StatsSource } from "@/server/statistics.ts";
import { ActionForm, Check, DbDown, Field, Flash, PageHead, type SearchParams } from "@/components/ui";
export const metadata = { title: "MAXIMUS · Data-source workspace", robots: { index: false, follow: false } };
export default async function Sources({ params, searchParams }: { params: Promise<{ lang: string }>; searchParams: SearchParams }) {
  const { lang } = await params; if (!isLocale(lang)) notFound(); const T = (ru: string, en: string) => lang === "ru" ? ru : en, back = `/${lang}/statistics/sources`;
  const { db, user } = await viewer(); if (!db) return <DbDown lang={lang} />; if (!user) redirect(`/${lang}/signin?next=${back}`);
  try { await requireStaffMfa(db, user); } catch { redirect(`/${lang}/admin/mfa?next=${back}`); }
  const orgs = await db.query<{ id: string; name: string }>("select o.id,o.name from organizations o where $2 or exists(select 1 from org_members m where m.org_id=o.id and m.user_id=$1 and m.role in('owner','admin')) order by o.name limit 100", [user.id, isAdmin(user)]);
  const ids = orgs.map(o => o.id), sources = await db.query<StatsSource>("select * from stats_sources where org_id=any($1::uuid[]) order by created_at desc", [ids]);
  const queue = await db.query<{ id: string; user_id: string; username: string; source: string; game: string; match_ref: string; metrics: Record<string, number> }>("select o.id,o.user_id,u.username,s.name as source,o.game,o.match_ref,o.metrics from stats_observations o join stats_sources s on s.id=o.source_id join users u on u.id=o.user_id where s.org_id=any($1::uuid[]) and o.status='pending' order by o.created_at limit 200", [ids]);
  const status = (s: string) => s === "approved" ? T("Источник подтверждён", "Source approved") : s === "pending" ? T("Ожидает проверки", "Pending review") : T("Источник приостановлен", "Source suspended");
  return <div className="container page"><Link className="text-link" href={`/${lang}/statistics`}>← {T("Статистика", "Statistics")}</Link><PageHead title={T("Кабинет источника данных", "Data-source workspace")} lead={T("Привяжите проверяемый источник к своему пространству организатора. Закрытый ключ остаётся у источника, портал получает только открытый ключ.", "Link an accountable data source to your organising space. The private signing key stays with the source; the portal receives only its public key.")} /><Flash lang={lang} params={await searchParams} />
    {!orgs.length ? <Link className="btn btn-primary" href={`/${lang}/organizer`}>{T("Создать пространство организатора", "Create an organising space")}</Link> : <details className="card"><summary>{T("Добавить источник", "Add source")}</summary><ActionForm action="stats.source" lang={lang} back={back}><Field label={T("Пространство организатора", "Organising space")}><select name="org">{orgs.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><Field label={T("Название источника", "Source name")}><input name="name" minLength={2} maxLength={80} required /></Field><Field label={T("Ссылка на сведения об операторе и разрешённом доступе к данным", "Operator and authorised data-access information URL")}><input name="evidence" type="url" required placeholder="https://" /></Field><Field label={T("Открытый ключ Ed25519 (PEM)", "Ed25519 public key (PEM)")}><textarea name="publicKey" maxLength={1000} minLength={40} required rows={5} /></Field><fieldset><legend>{T("Разрешённые игры", "Permitted games")}</legend>{GAMES.map(g => <Check key={g.slug} name="games" value={g.slug} label={g.name} />)}</fieldset><button className="btn btn-primary">{T("Передать на проверку", "Submit for review")}</button></ActionForm></details>}
    <section className="section-tight"><h2>{T("Ваши источники", "Your sources")}</h2>{sources.map(s => <article className="card section-tight" key={s.id}><h3>{s.name}</h3><p>{status(s.status)}</p><code className="break-all">{s.id}</code><p>{s.games.join(", ")}</p><p>{s.review_note}</p><details><summary>{T("Заменить ключ", "Rotate key")}</summary><p>{T("После замены источник снова проходит проверку, существующие привязки игроков отзываются.", "After rotation, the source is reviewed again and existing player links are revoked.")}</p><ActionForm action="stats.rotate" lang={lang} back={back} hidden={{ source: s.id }}><Field label={T("Новый открытый ключ", "New public key")}><textarea name="publicKey" required minLength={40} maxLength={1000} /></Field><button className="btn btn-ghost">{T("Заменить и отозвать старый ключ", "Replace and revoke old key")}</button></ActionForm></details></article>)}</section>
    <section className="section-tight"><h2>{T("Записи на проверке", "Records for review")}</h2>{!queue.length && <p>{T("Ожидающих записей нет", "No pending records")}</p>}{queue.map(r => <article className="card" key={r.id}><h3>{r.source} · @{r.username}</h3><p>{r.game} · {r.match_ref}</p><pre className="prewrap">{JSON.stringify(r.metrics, null, 2)}</pre><ActionForm action="stats.record_review" lang={lang} back={back} hidden={{ record: r.id }}><Field label={T("Решение", "Decision")}><select name="status"><option value="confirmed">{T("Подтвердить по доказательствам", "Confirm from evidence")}</option><option value="rejected">{T("Отклонить", "Reject")}</option></select></Field><Field label={T("Основание решения", "Decision reason")}><textarea name="note" required minLength={10} maxLength={1000} /></Field><button className="btn btn-primary" disabled={r.user_id === user.id}>{T("Сохранить решение", "Save decision")}</button></ActionForm></article>)}</section>
    <a className="text-link" href="https://github.com/MAXIMUS-NPiO/maximus-vegas/blob/main/docs/STATISTICS_PROTOCOL.md" target="_blank" rel="noopener">{T("Протокол подписи и подключения", "Signing and integration protocol")} ↗</a>
  </div>;
}
